/* AboutDialog.c generated by valac 0.36.7, the Vala compiler
 * generated from AboutDialog.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <float.h>
#include <math.h>
#include <glib/gi18n-lib.h>
#include <stdio.h>


#define GRANITE_GTK_PATCH_TYPE_ABOUT_DIALOG (granite_gtk_patch_about_dialog_get_type ())
#define GRANITE_GTK_PATCH_ABOUT_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_GTK_PATCH_TYPE_ABOUT_DIALOG, GraniteGtkPatchAboutDialog))
#define GRANITE_GTK_PATCH_ABOUT_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_GTK_PATCH_TYPE_ABOUT_DIALOG, GraniteGtkPatchAboutDialogClass))
#define GRANITE_GTK_PATCH_IS_ABOUT_DIALOG(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_GTK_PATCH_TYPE_ABOUT_DIALOG))
#define GRANITE_GTK_PATCH_IS_ABOUT_DIALOG_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_GTK_PATCH_TYPE_ABOUT_DIALOG))
#define GRANITE_GTK_PATCH_ABOUT_DIALOG_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_GTK_PATCH_TYPE_ABOUT_DIALOG, GraniteGtkPatchAboutDialogClass))

typedef struct _GraniteGtkPatchAboutDialog GraniteGtkPatchAboutDialog;
typedef struct _GraniteGtkPatchAboutDialogClass GraniteGtkPatchAboutDialogClass;
typedef struct _GraniteGtkPatchAboutDialogPrivate GraniteGtkPatchAboutDialogPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define GRANITE_TYPE_TEXT_STYLE (granite_text_style_get_type ())

#define GRANITE_WIDGETS_TYPE_WRAP_LABEL (granite_widgets_wrap_label_get_type ())
#define GRANITE_WIDGETS_WRAP_LABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_WIDGETS_TYPE_WRAP_LABEL, GraniteWidgetsWrapLabel))
#define GRANITE_WIDGETS_WRAP_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_WIDGETS_TYPE_WRAP_LABEL, GraniteWidgetsWrapLabelClass))
#define GRANITE_WIDGETS_IS_WRAP_LABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_WIDGETS_TYPE_WRAP_LABEL))
#define GRANITE_WIDGETS_IS_WRAP_LABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_WIDGETS_TYPE_WRAP_LABEL))
#define GRANITE_WIDGETS_WRAP_LABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_WIDGETS_TYPE_WRAP_LABEL, GraniteWidgetsWrapLabelClass))

typedef struct _GraniteWidgetsWrapLabel GraniteWidgetsWrapLabel;
typedef struct _GraniteWidgetsWrapLabelClass GraniteWidgetsWrapLabelClass;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
enum  {
	GRANITE_GTK_PATCH_ABOUT_DIALOG_ACTIVATE_LINK_SIGNAL,
	GRANITE_GTK_PATCH_ABOUT_DIALOG_NUM_SIGNALS
};
static guint granite_gtk_patch_about_dialog_signals[GRANITE_GTK_PATCH_ABOUT_DIALOG_NUM_SIGNALS] = {0};

struct _GraniteGtkPatchAboutDialog {
	GtkDialog parent_instance;
	GraniteGtkPatchAboutDialogPrivate * priv;
};

struct _GraniteGtkPatchAboutDialogClass {
	GtkDialogClass parent_class;
	gboolean (*activate_link) (GraniteGtkPatchAboutDialog* self, const gchar* uri);
};

struct _GraniteGtkPatchAboutDialogPrivate {
	gchar** _artists;
	gint _artists_length1;
	gint __artists_size_;
	gchar** _authors;
	gint _authors_length1;
	gint __authors_size_;
	gchar* _comments;
	gchar* _copyright;
	gchar** _documenters;
	gint _documenters_length1;
	gint __documenters_size_;
	gchar* _license;
	GtkLicense _license_type;
	GdkPixbuf* _logo;
	gchar* _logo_icon_name;
	gchar* _program_name;
	gchar* _translator_credits;
	gchar* _version;
	gchar* _website;
	gchar* _website_label;
	GtkImage* logo_image;
	GtkLabel* name_label;
	GtkLabel* copyright_label;
	GtkLabel* comments_label;
	GtkLabel* authors_label;
	GtkLabel* artists_label;
	GtkLabel* documenters_label;
	GtkLabel* translators_label;
	GtkLabel* license_label;
	GtkLabel* website_url_label;
	GtkButton* close_button;
};

typedef enum  {
	GRANITE_TEXT_STYLE_TITLE,
	GRANITE_TEXT_STYLE_H1,
	GRANITE_TEXT_STYLE_H2,
	GRANITE_TEXT_STYLE_H3
} GraniteTextStyle;


static gpointer granite_gtk_patch_about_dialog_parent_class = NULL;

GType granite_gtk_patch_about_dialog_get_type (void) G_GNUC_CONST;
#define GRANITE_GTK_PATCH_ABOUT_DIALOG_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GRANITE_GTK_PATCH_TYPE_ABOUT_DIALOG, GraniteGtkPatchAboutDialogPrivate))
enum  {
	GRANITE_GTK_PATCH_ABOUT_DIALOG_0_PROPERTY,
	GRANITE_GTK_PATCH_ABOUT_DIALOG_ARTISTS_PROPERTY,
	GRANITE_GTK_PATCH_ABOUT_DIALOG_AUTHORS_PROPERTY,
	GRANITE_GTK_PATCH_ABOUT_DIALOG_COMMENTS_PROPERTY,
	GRANITE_GTK_PATCH_ABOUT_DIALOG_COPYRIGHT_PROPERTY,
	GRANITE_GTK_PATCH_ABOUT_DIALOG_DOCUMENTERS_PROPERTY,
	GRANITE_GTK_PATCH_ABOUT_DIALOG_LICENSE_PROPERTY,
	GRANITE_GTK_PATCH_ABOUT_DIALOG_LICENSE_TYPE_PROPERTY,
	GRANITE_GTK_PATCH_ABOUT_DIALOG_LOGO_PROPERTY,
	GRANITE_GTK_PATCH_ABOUT_DIALOG_LOGO_ICON_NAME_PROPERTY,
	GRANITE_GTK_PATCH_ABOUT_DIALOG_PROGRAM_NAME_PROPERTY,
	GRANITE_GTK_PATCH_ABOUT_DIALOG_TRANSLATOR_CREDITS_PROPERTY,
	GRANITE_GTK_PATCH_ABOUT_DIALOG_VERSION_PROPERTY,
	GRANITE_GTK_PATCH_ABOUT_DIALOG_WEBSITE_PROPERTY,
	GRANITE_GTK_PATCH_ABOUT_DIALOG_WEBSITE_LABEL_PROPERTY
};
#define GRANITE_GTK_PATCH_ABOUT_DIALOG_STYLESHEET "\n" \
"        * {\n" \
"            -GtkDialog-action-area-border: 12px;\n" \
"            -GtkDialog-button-spacing: 10px;\n" \
"            -GtkDialog-content-area-border: 0;\n" \
"        }\n" \
"    "
GraniteGtkPatchAboutDialog* granite_gtk_patch_about_dialog_new (void);
GraniteGtkPatchAboutDialog* granite_gtk_patch_about_dialog_construct (GType object_type);
GtkCssProvider* granite_widgets_utils_set_theming (GtkWidget* widget, const gchar* stylesheet, const gchar* class_name, gint priority);
GType granite_text_style_get_type (void) G_GNUC_CONST;
void granite_widgets_utils_apply_text_style_to_label (GraniteTextStyle text_style, GtkLabel* label);
GraniteWidgetsWrapLabel* granite_widgets_wrap_label_new (const gchar* str);
GraniteWidgetsWrapLabel* granite_widgets_wrap_label_construct (GType object_type, const gchar* str);
GType granite_widgets_wrap_label_get_type (void) G_GNUC_CONST;
static void __lambda4_ (GraniteGtkPatchAboutDialog* self);
static void ___lambda4__gtk_button_clicked (GtkButton* _sender, gpointer self);
static gchar* granite_gtk_patch_about_dialog_set_string_from_string_array (GraniteGtkPatchAboutDialog* self, const gchar* title, gchar** peoples, int peoples_length1, gboolean tooltip);
static void granite_gtk_patch_about_dialog_update_logo_image (GraniteGtkPatchAboutDialog* self);
const gchar* granite_gtk_patch_about_dialog_get_logo_icon_name (GraniteGtkPatchAboutDialog* self);
GdkPixbuf* granite_gtk_patch_about_dialog_get_logo (GraniteGtkPatchAboutDialog* self);
static void granite_gtk_patch_about_dialog_update_license (GraniteGtkPatchAboutDialog* self);
GtkLicense granite_gtk_patch_about_dialog_get_license_type (GraniteGtkPatchAboutDialog* self);
static void granite_gtk_patch_about_dialog_set_generic_license (GraniteGtkPatchAboutDialog* self, const gchar* url, const gchar* license_type);
const gchar* granite_gtk_patch_about_dialog_get_license (GraniteGtkPatchAboutDialog* self);
static void granite_gtk_patch_about_dialog_set_name_and_version (GraniteGtkPatchAboutDialog* self);
const gchar* granite_gtk_patch_about_dialog_get_program_name (GraniteGtkPatchAboutDialog* self);
const gchar* granite_gtk_patch_about_dialog_get_version (GraniteGtkPatchAboutDialog* self);
static void granite_gtk_patch_about_dialog_update_website (GraniteGtkPatchAboutDialog* self);
const gchar* granite_gtk_patch_about_dialog_get_website (GraniteGtkPatchAboutDialog* self);
const gchar* granite_gtk_patch_about_dialog_get_website_label (GraniteGtkPatchAboutDialog* self);
gchar** granite_gtk_patch_about_dialog_get_artists (GraniteGtkPatchAboutDialog* self, int* result_length1);
void granite_gtk_patch_about_dialog_set_artists (GraniteGtkPatchAboutDialog* self, gchar** value, int value_length1);
static gchar** _vala_array_dup1 (gchar** self, int length);
gchar** granite_gtk_patch_about_dialog_get_authors (GraniteGtkPatchAboutDialog* self, int* result_length1);
void granite_gtk_patch_about_dialog_set_authors (GraniteGtkPatchAboutDialog* self, gchar** value, int value_length1);
static gchar** _vala_array_dup2 (gchar** self, int length);
const gchar* granite_gtk_patch_about_dialog_get_comments (GraniteGtkPatchAboutDialog* self);
void granite_gtk_patch_about_dialog_set_comments (GraniteGtkPatchAboutDialog* self, const gchar* value);
const gchar* granite_gtk_patch_about_dialog_get_copyright (GraniteGtkPatchAboutDialog* self);
void granite_gtk_patch_about_dialog_set_copyright (GraniteGtkPatchAboutDialog* self, const gchar* value);
gchar** granite_gtk_patch_about_dialog_get_documenters (GraniteGtkPatchAboutDialog* self, int* result_length1);
void granite_gtk_patch_about_dialog_set_documenters (GraniteGtkPatchAboutDialog* self, gchar** value, int value_length1);
static gchar** _vala_array_dup3 (gchar** self, int length);
void granite_gtk_patch_about_dialog_set_license (GraniteGtkPatchAboutDialog* self, const gchar* value);
void granite_gtk_patch_about_dialog_set_license_type (GraniteGtkPatchAboutDialog* self, GtkLicense value);
void granite_gtk_patch_about_dialog_set_logo (GraniteGtkPatchAboutDialog* self, GdkPixbuf* value);
void granite_gtk_patch_about_dialog_set_logo_icon_name (GraniteGtkPatchAboutDialog* self, const gchar* value);
void granite_gtk_patch_about_dialog_set_program_name (GraniteGtkPatchAboutDialog* self, const gchar* value);
const gchar* granite_gtk_patch_about_dialog_get_translator_credits (GraniteGtkPatchAboutDialog* self);
void granite_gtk_patch_about_dialog_set_translator_credits (GraniteGtkPatchAboutDialog* self, const gchar* value);
void granite_gtk_patch_about_dialog_set_version (GraniteGtkPatchAboutDialog* self, const gchar* value);
void granite_gtk_patch_about_dialog_set_website (GraniteGtkPatchAboutDialog* self, const gchar* value);
void granite_gtk_patch_about_dialog_set_website_label (GraniteGtkPatchAboutDialog* self, const gchar* value);
static gboolean granite_gtk_patch_about_dialog_real_activate_link (GraniteGtkPatchAboutDialog* self, const gchar* uri);
static void g_cclosure_user_marshal_BOOLEAN__STRING (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void granite_gtk_patch_about_dialog_finalize (GObject * obj);
static void _vala_granite_gtk_patch_about_dialog_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_granite_gtk_patch_about_dialog_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


/**
     * Creates a new Granite.AboutDialog
     */
static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void __lambda4_ (GraniteGtkPatchAboutDialog* self) {
	gtk_dialog_response ((GtkDialog*) self, (gint) GTK_RESPONSE_CANCEL);
}


static void ___lambda4__gtk_button_clicked (GtkButton* _sender, gpointer self) {
	__lambda4_ ((GraniteGtkPatchAboutDialog*) self);
}


GraniteGtkPatchAboutDialog* granite_gtk_patch_about_dialog_construct (GType object_type) {
	GraniteGtkPatchAboutDialog * self = NULL;
	GtkCssProvider* _tmp0_;
	GtkCssProvider* _tmp1_;
	GtkBox* content_area = NULL;
	GtkBox* _tmp2_;
	GtkBox* _tmp3_;
	GtkBox* action_area = NULL;
	GtkWidget* _tmp4_;
	GtkBox* _tmp5_;
	GtkBox* content_hbox = NULL;
	GtkBox* _tmp6_;
	GtkBox* content_right_box = NULL;
	GtkBox* _tmp7_;
	GtkScrolledWindow* content_scrolled = NULL;
	GtkAdjustment* _tmp8_;
	GtkAdjustment* _tmp9_;
	GtkScrolledWindow* _tmp10_;
	GtkScrolledWindow* _tmp11_;
	GtkBox* content_scrolled_vbox = NULL;
	GtkBox* _tmp12_;
	GtkBox* title_vbox = NULL;
	GtkBox* _tmp13_;
	GtkBox* logo_vbox = NULL;
	GtkBox* _tmp14_;
	GtkImage* _tmp15_;
	GtkImage* _tmp16_;
	GtkBox* _tmp17_;
	GtkBox* _tmp18_;
	GtkImage* _tmp19_;
	GtkLabel* _tmp20_;
	GtkLabel* _tmp21_;
	GtkLabel* _tmp22_;
	GtkLabel* _tmp23_;
	GtkLabel* _tmp24_;
	GtkLabel* _tmp25_;
	GtkLabel* _tmp26_;
	GtkLabel* _tmp27_;
	GtkLabel* _tmp28_;
	GtkLabel* _tmp29_;
	GtkLabel* _tmp30_;
	GtkLabel* _tmp31_;
	GtkLabel* _tmp32_;
	GtkLabel* _tmp33_;
	GtkLabel* _tmp34_;
	GtkLabel* _tmp35_;
	GtkLabel* _tmp36_;
	GtkLabel* _tmp37_;
	GtkLabel* _tmp38_;
	GtkLabel* _tmp39_;
	GtkLabel* _tmp40_;
	GtkLabel* _tmp41_;
	GtkLabel* _tmp42_;
	GtkLabel* _tmp43_;
	GtkLabel* _tmp44_;
	GtkLabel* _tmp45_;
	GtkLabel* _tmp46_;
	GtkLabel* _tmp47_;
	GtkLabel* _tmp48_;
	GraniteWidgetsWrapLabel* _tmp49_;
	GtkLabel* _tmp50_;
	GtkLabel* _tmp51_;
	GtkLabel* _tmp52_;
	GtkLabel* _tmp53_;
	GtkLabel* _tmp54_;
	GtkBox* _tmp55_;
	GtkBox* _tmp56_;
	GtkBox* _tmp57_;
	GtkBox* _tmp58_;
	GtkLabel* _tmp59_;
	GtkBox* _tmp60_;
	GtkBox* _tmp61_;
	GtkLabel* _tmp62_;
	GtkLabel* _tmp63_;
	GtkLabel* _tmp64_;
	GtkLabel* _tmp65_;
	GtkLabel* _tmp66_;
	GtkLabel* _tmp67_;
	GtkLabel* _tmp68_;
	GtkLabel* _tmp69_;
	GtkButton* _tmp70_;
	GtkButton* _tmp71_;
	GtkButton* _tmp72_;
	GtkButton* _tmp73_;
	self = (GraniteGtkPatchAboutDialog*) g_object_new (object_type, NULL);
	gtk_window_set_title ((GtkWindow*) self, "");
	gtk_window_set_has_resize_grip ((GtkWindow*) self, FALSE);
	gtk_window_set_resizable ((GtkWindow*) self, FALSE);
	gtk_window_set_deletable ((GtkWindow*) self, FALSE);
	gtk_dialog_set_default_response ((GtkDialog*) self, (gint) GTK_RESPONSE_CANCEL);
	_tmp0_ = granite_widgets_utils_set_theming ((GtkWidget*) self, GRANITE_GTK_PATCH_ABOUT_DIALOG_STYLESHEET, NULL, GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
	_tmp1_ = _tmp0_;
	_g_object_unref0 (_tmp1_);
	_tmp2_ = (GtkBox*) gtk_dialog_get_content_area ((GtkDialog*) self);
	_tmp3_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp2_, gtk_box_get_type (), GtkBox));
	content_area = _tmp3_;
	_tmp4_ = gtk_dialog_get_action_area ((GtkDialog*) self);
	_tmp5_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp4_, gtk_box_get_type (), GtkBox));
	action_area = _tmp5_;
	_tmp6_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 12);
	g_object_ref_sink (_tmp6_);
	content_hbox = _tmp6_;
	_tmp7_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp7_);
	content_right_box = _tmp7_;
	_tmp8_ = gtk_adjustment_new ((gdouble) 0, (gdouble) 0, (gdouble) 100, (gdouble) 1, (gdouble) 10, (gdouble) 0);
	g_object_ref_sink (_tmp8_);
	_tmp9_ = _tmp8_;
	_tmp10_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, _tmp9_);
	g_object_ref_sink (_tmp10_);
	_tmp11_ = _tmp10_;
	_g_object_unref0 (_tmp9_);
	content_scrolled = _tmp11_;
	_tmp12_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp12_);
	content_scrolled_vbox = _tmp12_;
	_tmp13_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp13_);
	title_vbox = _tmp13_;
	_tmp14_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp14_);
	logo_vbox = _tmp14_;
	gtk_scrolled_window_set_shadow_type (content_scrolled, GTK_SHADOW_NONE);
	g_object_set (content_scrolled, "hscrollbar-policy", GTK_POLICY_NEVER, NULL);
	g_object_set (content_scrolled, "vscrollbar-policy", GTK_POLICY_AUTOMATIC, NULL);
	gtk_box_pack_start (content_area, (GtkWidget*) content_hbox, TRUE, TRUE, (guint) 0);
	_tmp15_ = (GtkImage*) gtk_image_new ();
	g_object_ref_sink (_tmp15_);
	_g_object_unref0 (self->priv->logo_image);
	self->priv->logo_image = _tmp15_;
	_tmp16_ = self->priv->logo_image;
	gtk_box_pack_start (logo_vbox, (GtkWidget*) _tmp16_, FALSE, FALSE, (guint) 12);
	_tmp17_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp17_);
	_tmp18_ = _tmp17_;
	gtk_box_pack_end (logo_vbox, (GtkWidget*) _tmp18_, TRUE, TRUE, (guint) 0);
	_g_object_unref0 (_tmp18_);
	g_object_set ((GtkWidget*) content_hbox, "height-request", 160, NULL);
	g_object_set ((GtkWidget*) content_scrolled_vbox, "width-request", 288, NULL);
	_tmp19_ = self->priv->logo_image;
	gtk_widget_set_size_request ((GtkWidget*) _tmp19_, 128, 128);
	_tmp20_ = (GtkLabel*) gtk_label_new ("");
	g_object_ref_sink (_tmp20_);
	_g_object_unref0 (self->priv->name_label);
	self->priv->name_label = _tmp20_;
	_tmp21_ = self->priv->name_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp21_, GTK_ALIGN_START);
	_tmp22_ = self->priv->name_label;
	gtk_label_set_line_wrap (_tmp22_, TRUE);
	_tmp23_ = self->priv->name_label;
	gtk_label_set_selectable (_tmp23_, TRUE);
	_tmp24_ = self->priv->name_label;
	granite_widgets_utils_apply_text_style_to_label (GRANITE_TEXT_STYLE_H2, _tmp24_);
	_tmp25_ = (GtkLabel*) gtk_label_new ("");
	g_object_ref_sink (_tmp25_);
	_g_object_unref0 (self->priv->copyright_label);
	self->priv->copyright_label = _tmp25_;
	_tmp26_ = self->priv->copyright_label;
	gtk_label_set_selectable (_tmp26_, TRUE);
	_tmp27_ = self->priv->copyright_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp27_, GTK_ALIGN_START);
	_tmp28_ = self->priv->copyright_label;
	gtk_label_set_line_wrap (_tmp28_, TRUE);
	_tmp29_ = (GtkLabel*) gtk_label_new ("");
	g_object_ref_sink (_tmp29_);
	_g_object_unref0 (self->priv->comments_label);
	self->priv->comments_label = _tmp29_;
	_tmp30_ = self->priv->comments_label;
	gtk_label_set_selectable (_tmp30_, TRUE);
	_tmp31_ = self->priv->comments_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp31_, GTK_ALIGN_START);
	_tmp32_ = self->priv->comments_label;
	gtk_label_set_line_wrap (_tmp32_, TRUE);
	_tmp33_ = (GtkLabel*) gtk_label_new ("");
	g_object_ref_sink (_tmp33_);
	_g_object_unref0 (self->priv->authors_label);
	self->priv->authors_label = _tmp33_;
	_tmp34_ = self->priv->authors_label;
	gtk_label_set_selectable (_tmp34_, TRUE);
	_tmp35_ = self->priv->authors_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp35_, GTK_ALIGN_START);
	_tmp36_ = self->priv->authors_label;
	gtk_label_set_line_wrap (_tmp36_, TRUE);
	_tmp37_ = (GtkLabel*) gtk_label_new ("");
	g_object_ref_sink (_tmp37_);
	_g_object_unref0 (self->priv->artists_label);
	self->priv->artists_label = _tmp37_;
	_tmp38_ = self->priv->artists_label;
	gtk_label_set_selectable (_tmp38_, TRUE);
	_tmp39_ = self->priv->artists_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp39_, GTK_ALIGN_START);
	_tmp40_ = self->priv->artists_label;
	gtk_label_set_line_wrap (_tmp40_, TRUE);
	_tmp41_ = (GtkLabel*) gtk_label_new ("");
	g_object_ref_sink (_tmp41_);
	_g_object_unref0 (self->priv->documenters_label);
	self->priv->documenters_label = _tmp41_;
	_tmp42_ = self->priv->documenters_label;
	gtk_label_set_selectable (_tmp42_, TRUE);
	_tmp43_ = self->priv->documenters_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp43_, GTK_ALIGN_START);
	_tmp44_ = self->priv->documenters_label;
	gtk_label_set_line_wrap (_tmp44_, TRUE);
	_tmp45_ = (GtkLabel*) gtk_label_new ("");
	g_object_ref_sink (_tmp45_);
	_g_object_unref0 (self->priv->translators_label);
	self->priv->translators_label = _tmp45_;
	_tmp46_ = self->priv->translators_label;
	gtk_label_set_selectable (_tmp46_, TRUE);
	_tmp47_ = self->priv->translators_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp47_, GTK_ALIGN_START);
	_tmp48_ = self->priv->translators_label;
	gtk_label_set_line_wrap (_tmp48_, TRUE);
	_tmp49_ = granite_widgets_wrap_label_new ("");
	g_object_ref_sink (_tmp49_);
	_g_object_unref0 (self->priv->license_label);
	self->priv->license_label = (GtkLabel*) _tmp49_;
	_tmp50_ = self->priv->license_label;
	gtk_label_set_selectable (_tmp50_, TRUE);
	_tmp51_ = (GtkLabel*) gtk_label_new ("");
	g_object_ref_sink (_tmp51_);
	_g_object_unref0 (self->priv->website_url_label);
	self->priv->website_url_label = _tmp51_;
	_tmp52_ = self->priv->website_url_label;
	gtk_label_set_selectable (_tmp52_, TRUE);
	_tmp53_ = self->priv->website_url_label;
	gtk_widget_set_halign ((GtkWidget*) _tmp53_, GTK_ALIGN_START);
	_tmp54_ = self->priv->website_url_label;
	gtk_label_set_line_wrap (_tmp54_, TRUE);
	_tmp55_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp55_);
	_tmp56_ = _tmp55_;
	gtk_box_pack_start (content_hbox, (GtkWidget*) _tmp56_, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (_tmp56_);
	_tmp57_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp57_);
	_tmp58_ = _tmp57_;
	gtk_box_pack_end (content_hbox, (GtkWidget*) _tmp58_, FALSE, FALSE, (guint) 0);
	_g_object_unref0 (_tmp58_);
	gtk_box_pack_start (content_hbox, (GtkWidget*) logo_vbox, TRUE, TRUE, (guint) 0);
	gtk_box_pack_start (content_hbox, (GtkWidget*) content_right_box, TRUE, TRUE, (guint) 0);
	gtk_scrolled_window_add_with_viewport (content_scrolled, (GtkWidget*) content_scrolled_vbox);
	_tmp59_ = self->priv->name_label;
	gtk_box_pack_start (title_vbox, (GtkWidget*) _tmp59_, FALSE, FALSE, (guint) 12);
	gtk_box_pack_start (content_right_box, (GtkWidget*) title_vbox, FALSE, FALSE, (guint) 0);
	gtk_box_pack_start (content_right_box, (GtkWidget*) content_scrolled, TRUE, TRUE, (guint) 0);
	_tmp60_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	g_object_ref_sink (_tmp60_);
	_tmp61_ = _tmp60_;
	gtk_box_pack_end (content_right_box, (GtkWidget*) _tmp61_, FALSE, FALSE, (guint) 6);
	_g_object_unref0 (_tmp61_);
	_tmp62_ = self->priv->comments_label;
	gtk_box_pack_start (content_scrolled_vbox, (GtkWidget*) _tmp62_, TRUE, TRUE, (guint) 0);
	_tmp63_ = self->priv->website_url_label;
	gtk_box_pack_start (content_scrolled_vbox, (GtkWidget*) _tmp63_, TRUE, TRUE, (guint) 0);
	_tmp64_ = self->priv->copyright_label;
	gtk_box_pack_start (content_scrolled_vbox, (GtkWidget*) _tmp64_, TRUE, TRUE, (guint) 0);
	_tmp65_ = self->priv->license_label;
	gtk_box_pack_start (content_scrolled_vbox, (GtkWidget*) _tmp65_, TRUE, TRUE, (guint) 0);
	_tmp66_ = self->priv->authors_label;
	gtk_box_pack_start (content_scrolled_vbox, (GtkWidget*) _tmp66_, TRUE, TRUE, (guint) 0);
	_tmp67_ = self->priv->artists_label;
	gtk_box_pack_start (content_scrolled_vbox, (GtkWidget*) _tmp67_, TRUE, TRUE, (guint) 0);
	_tmp68_ = self->priv->documenters_label;
	gtk_box_pack_start (content_scrolled_vbox, (GtkWidget*) _tmp68_, TRUE, TRUE, (guint) 0);
	_tmp69_ = self->priv->translators_label;
	gtk_box_pack_start (content_scrolled_vbox, (GtkWidget*) _tmp69_, TRUE, TRUE, (guint) 0);
	_tmp70_ = (GtkButton*) gtk_button_new_with_label (_ ("Close"));
	g_object_ref_sink (_tmp70_);
	_g_object_unref0 (self->priv->close_button);
	self->priv->close_button = _tmp70_;
	_tmp71_ = self->priv->close_button;
	g_signal_connect_object (_tmp71_, "clicked", (GCallback) ___lambda4__gtk_button_clicked, self, 0);
	_tmp72_ = self->priv->close_button;
	gtk_box_pack_end (action_area, (GtkWidget*) _tmp72_, FALSE, FALSE, (guint) 0);
	_tmp73_ = self->priv->close_button;
	gtk_widget_grab_focus ((GtkWidget*) _tmp73_);
	_g_object_unref0 (logo_vbox);
	_g_object_unref0 (title_vbox);
	_g_object_unref0 (content_scrolled_vbox);
	_g_object_unref0 (content_scrolled);
	_g_object_unref0 (content_right_box);
	_g_object_unref0 (content_hbox);
	_g_object_unref0 (action_area);
	_g_object_unref0 (content_area);
	return self;
}


GraniteGtkPatchAboutDialog* granite_gtk_patch_about_dialog_new (void) {
	return granite_gtk_patch_about_dialog_construct (GRANITE_GTK_PATCH_TYPE_ABOUT_DIALOG);
}


static gchar* _vala_g_strjoinv (const gchar* separator, gchar** str_array, int str_array_length1) {
	gchar* result = NULL;
	const gchar* _tmp0_;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	gchar** _tmp3_;
	gint _tmp3__length1;
	_tmp0_ = separator;
	if (_tmp0_ == NULL) {
		separator = "";
	}
	_tmp3_ = str_array;
	_tmp3__length1 = str_array_length1;
	if (_tmp3_ != NULL) {
		_tmp2_ = TRUE;
	} else {
		gchar** _tmp4_;
		gint _tmp4__length1;
		_tmp4_ = str_array;
		_tmp4__length1 = str_array_length1;
		_tmp2_ = _tmp4__length1 > 0;
	}
	if (_tmp2_) {
		_tmp1_ = TRUE;
	} else {
		gboolean _tmp5_ = FALSE;
		gchar** _tmp6_;
		gint _tmp6__length1;
		_tmp6_ = str_array;
		_tmp6__length1 = str_array_length1;
		if (_tmp6__length1 == -1) {
			gchar** _tmp7_;
			gint _tmp7__length1;
			const gchar* _tmp8_;
			_tmp7_ = str_array;
			_tmp7__length1 = str_array_length1;
			_tmp8_ = _tmp7_[0];
			_tmp5_ = _tmp8_ != NULL;
		} else {
			_tmp5_ = FALSE;
		}
		_tmp1_ = _tmp5_;
	}
	if (_tmp1_) {
		gint i = 0;
		gsize len = 0UL;
		gint _tmp31_;
		gint _tmp33_;
		gint _tmp34_;
		gsize _tmp35_;
		const gchar* _tmp36_;
		gint _tmp37_;
		gint _tmp38_;
		gint _tmp39_;
		const gchar* res = NULL;
		gsize _tmp40_;
		void* _tmp41_;
		void* ptr = NULL;
		const gchar* _tmp42_;
		gchar** _tmp43_;
		gint _tmp43__length1;
		const gchar* _tmp44_;
		void* _tmp45_;
		const gchar* _tmp62_;
		len = (gsize) 1;
		{
			gboolean _tmp9_ = FALSE;
			i = 0;
			_tmp9_ = TRUE;
			while (TRUE) {
				gboolean _tmp11_ = FALSE;
				gboolean _tmp12_ = FALSE;
				gchar** _tmp13_;
				gint _tmp13__length1;
				gint _tmp21_ = 0;
				gchar** _tmp22_;
				gint _tmp22__length1;
				gint _tmp23_;
				const gchar* _tmp24_;
				gsize _tmp30_;
				if (!_tmp9_) {
					gint _tmp10_;
					_tmp10_ = i;
					i = _tmp10_ + 1;
				}
				_tmp9_ = FALSE;
				_tmp13_ = str_array;
				_tmp13__length1 = str_array_length1;
				if (_tmp13__length1 != -1) {
					gint _tmp14_;
					gchar** _tmp15_;
					gint _tmp15__length1;
					_tmp14_ = i;
					_tmp15_ = str_array;
					_tmp15__length1 = str_array_length1;
					_tmp12_ = _tmp14_ < _tmp15__length1;
				} else {
					_tmp12_ = FALSE;
				}
				if (_tmp12_) {
					_tmp11_ = TRUE;
				} else {
					gboolean _tmp16_ = FALSE;
					gchar** _tmp17_;
					gint _tmp17__length1;
					_tmp17_ = str_array;
					_tmp17__length1 = str_array_length1;
					if (_tmp17__length1 == -1) {
						gchar** _tmp18_;
						gint _tmp18__length1;
						gint _tmp19_;
						const gchar* _tmp20_;
						_tmp18_ = str_array;
						_tmp18__length1 = str_array_length1;
						_tmp19_ = i;
						_tmp20_ = _tmp18_[_tmp19_];
						_tmp16_ = _tmp20_ != NULL;
					} else {
						_tmp16_ = FALSE;
					}
					_tmp11_ = _tmp16_;
				}
				if (!_tmp11_) {
					break;
				}
				_tmp22_ = str_array;
				_tmp22__length1 = str_array_length1;
				_tmp23_ = i;
				_tmp24_ = _tmp22_[_tmp23_];
				if (_tmp24_ != NULL) {
					gchar** _tmp25_;
					gint _tmp25__length1;
					gint _tmp26_;
					const gchar* _tmp27_;
					gint _tmp28_;
					gint _tmp29_;
					_tmp25_ = str_array;
					_tmp25__length1 = str_array_length1;
					_tmp26_ = i;
					_tmp27_ = _tmp25_[_tmp26_];
					_tmp28_ = strlen ((const gchar*) _tmp27_);
					_tmp29_ = _tmp28_;
					_tmp21_ = _tmp29_;
				} else {
					_tmp21_ = 0;
				}
				_tmp30_ = len;
				len = _tmp30_ + _tmp21_;
			}
		}
		_tmp31_ = i;
		if (_tmp31_ == 0) {
			gchar* _tmp32_;
			_tmp32_ = g_strdup ("");
			result = _tmp32_;
			return result;
		}
		_tmp33_ = i;
		str_array_length1 = _tmp33_;
		_tmp34_ = str_array_length1;
		_tmp35_ = len;
		_tmp36_ = separator;
		_tmp37_ = strlen ((const gchar*) _tmp36_);
		_tmp38_ = _tmp37_;
		_tmp39_ = i;
		len = _tmp35_ + (_tmp38_ * (_tmp39_ - 1));
		_tmp40_ = len;
		_tmp41_ = g_malloc (_tmp40_);
		res = _tmp41_;
		_tmp42_ = res;
		_tmp43_ = str_array;
		_tmp43__length1 = str_array_length1;
		_tmp44_ = _tmp43_[0];
		_tmp45_ = g_stpcpy ((void*) _tmp42_, (const gchar*) _tmp44_);
		ptr = _tmp45_;
		{
			gboolean _tmp46_ = FALSE;
			i = 1;
			_tmp46_ = TRUE;
			while (TRUE) {
				gint _tmp48_;
				gchar** _tmp49_;
				gint _tmp49__length1;
				void* _tmp50_;
				const gchar* _tmp51_;
				void* _tmp52_;
				const gchar* _tmp53_ = NULL;
				gchar** _tmp54_;
				gint _tmp54__length1;
				gint _tmp55_;
				const gchar* _tmp56_;
				void* _tmp60_;
				void* _tmp61_;
				if (!_tmp46_) {
					gint _tmp47_;
					_tmp47_ = i;
					i = _tmp47_ + 1;
				}
				_tmp46_ = FALSE;
				_tmp48_ = i;
				_tmp49_ = str_array;
				_tmp49__length1 = str_array_length1;
				if (!(_tmp48_ < _tmp49__length1)) {
					break;
				}
				_tmp50_ = ptr;
				_tmp51_ = separator;
				_tmp52_ = g_stpcpy (_tmp50_, (const gchar*) _tmp51_);
				ptr = _tmp52_;
				_tmp54_ = str_array;
				_tmp54__length1 = str_array_length1;
				_tmp55_ = i;
				_tmp56_ = _tmp54_[_tmp55_];
				if (_tmp56_ != NULL) {
					gchar** _tmp57_;
					gint _tmp57__length1;
					gint _tmp58_;
					const gchar* _tmp59_;
					_tmp57_ = str_array;
					_tmp57__length1 = str_array_length1;
					_tmp58_ = i;
					_tmp59_ = _tmp57_[_tmp58_];
					_tmp53_ = (const gchar*) _tmp59_;
				} else {
					_tmp53_ = "";
				}
				_tmp60_ = ptr;
				_tmp61_ = g_stpcpy (_tmp60_, _tmp53_);
				ptr = _tmp61_;
			}
		}
		_tmp62_ = res;
		res = NULL;
		result = (gchar*) _tmp62_;
		return result;
	} else {
		gchar* _tmp63_;
		_tmp63_ = g_strdup ("");
		result = _tmp63_;
		return result;
	}
}


static gchar string_get (const gchar* self, glong index) {
	gchar result = '\0';
	glong _tmp0_;
	gchar _tmp1_;
	g_return_val_if_fail (self != NULL, '\0');
	_tmp0_ = index;
	_tmp1_ = ((gchar*) self)[_tmp0_];
	result = _tmp1_;
	return result;
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	const gchar* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	g_strstrip (_tmp1_);
	result = _result_;
	return result;
}


static gchar* granite_gtk_patch_about_dialog_set_string_from_string_array (GraniteGtkPatchAboutDialog* self, const gchar* title, gchar** peoples, int peoples_length1, gboolean tooltip) {
	gchar* result = NULL;
	gboolean _tmp0_;
	gchar* text = NULL;
	gchar* _tmp3_;
	gchar* name = NULL;
	gchar* _tmp4_;
	gchar* email = NULL;
	gchar* _tmp5_;
	gchar* _person_data = NULL;
	gboolean email_started = FALSE;
	const gchar* _tmp6_;
	const gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	const gchar* _tmp72_;
	gchar* _tmp73_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (title != NULL, NULL);
	_tmp0_ = tooltip;
	if (_tmp0_) {
		gchar** _tmp1_;
		gint _tmp1__length1;
		gchar* _tmp2_;
		_tmp1_ = peoples;
		_tmp1__length1 = peoples_length1;
		_tmp2_ = _vala_g_strjoinv ("\n", _tmp1_, _tmp1__length1);
		result = _tmp2_;
		return result;
	}
	_tmp3_ = g_strdup ("");
	text = _tmp3_;
	_tmp4_ = g_strdup ("");
	name = _tmp4_;
	_tmp5_ = g_strdup ("");
	email = _tmp5_;
	email_started = FALSE;
	_tmp6_ = text;
	_tmp7_ = title;
	_tmp8_ = g_strconcat (_tmp7_, "<span size=\"small\">", NULL);
	_tmp9_ = _tmp8_;
	_tmp10_ = g_strconcat (_tmp6_, _tmp9_, NULL);
	_g_free0 (text);
	text = _tmp10_;
	_g_free0 (_tmp9_);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp11_ = FALSE;
			_tmp11_ = TRUE;
			while (TRUE) {
				gint _tmp13_;
				gchar** _tmp14_;
				gint _tmp14__length1;
				gchar** _tmp15_;
				gint _tmp15__length1;
				gint _tmp16_;
				const gchar* _tmp17_;
				gchar** _tmp18_;
				gint _tmp18__length1;
				gint _tmp19_;
				const gchar* _tmp20_;
				gchar* _tmp21_;
				const gchar* _tmp53_;
				gchar* _tmp70_;
				gchar* _tmp71_;
				if (!_tmp11_) {
					gint _tmp12_;
					_tmp12_ = i;
					i = _tmp12_ + 1;
				}
				_tmp11_ = FALSE;
				_tmp13_ = i;
				_tmp14_ = peoples;
				_tmp14__length1 = peoples_length1;
				if (!(_tmp13_ < _tmp14__length1)) {
					break;
				}
				_tmp15_ = peoples;
				_tmp15__length1 = peoples_length1;
				_tmp16_ = i;
				_tmp17_ = _tmp15_[_tmp16_];
				if (_tmp17_ == NULL) {
					break;
				}
				_tmp18_ = peoples;
				_tmp18__length1 = peoples_length1;
				_tmp19_ = i;
				_tmp20_ = _tmp18_[_tmp19_];
				_tmp21_ = g_strdup (_tmp20_);
				_g_free0 (_person_data);
				_person_data = _tmp21_;
				{
					gint j = 0;
					j = 0;
					{
						gboolean _tmp22_ = FALSE;
						_tmp22_ = TRUE;
						while (TRUE) {
							gint _tmp24_;
							const gchar* _tmp25_;
							gint _tmp26_;
							gint _tmp27_;
							const gchar* _tmp28_;
							gint _tmp29_;
							gchar _tmp30_;
							gboolean _tmp31_;
							if (!_tmp22_) {
								gint _tmp23_;
								_tmp23_ = j;
								j = _tmp23_ + 1;
							}
							_tmp22_ = FALSE;
							_tmp24_ = j;
							_tmp25_ = _person_data;
							_tmp26_ = strlen (_tmp25_);
							_tmp27_ = _tmp26_;
							if (!(_tmp24_ < _tmp27_)) {
								break;
							}
							_tmp28_ = _person_data;
							_tmp29_ = j;
							_tmp30_ = string_get (_tmp28_, (glong) _tmp29_);
							if (_tmp30_ == '<') {
								email_started = TRUE;
							}
							_tmp31_ = email_started;
							if (!_tmp31_) {
								const gchar* _tmp32_;
								const gchar* _tmp33_;
								gint _tmp34_;
								gchar _tmp35_;
								gchar* _tmp36_;
								gchar* _tmp37_;
								gchar* _tmp38_;
								_tmp32_ = name;
								_tmp33_ = _person_data;
								_tmp34_ = j;
								_tmp35_ = string_get (_tmp33_, (glong) _tmp34_);
								_tmp36_ = g_strdup_printf ("%c", _tmp35_);
								_tmp37_ = _tmp36_;
								_tmp38_ = g_strconcat (_tmp32_, _tmp37_, NULL);
								_g_free0 (name);
								name = _tmp38_;
								_g_free0 (_tmp37_);
							} else {
								gboolean _tmp39_ = FALSE;
								const gchar* _tmp40_;
								gint _tmp41_;
								gchar _tmp42_;
								_tmp40_ = _person_data;
								_tmp41_ = j;
								_tmp42_ = string_get (_tmp40_, (glong) _tmp41_);
								if (_tmp42_ != '>') {
									const gchar* _tmp43_;
									gint _tmp44_;
									gchar _tmp45_;
									_tmp43_ = _person_data;
									_tmp44_ = j;
									_tmp45_ = string_get (_tmp43_, (glong) _tmp44_);
									_tmp39_ = _tmp45_ != '<';
								} else {
									_tmp39_ = FALSE;
								}
								if (_tmp39_) {
									const gchar* _tmp46_;
									const gchar* _tmp47_;
									gint _tmp48_;
									gchar _tmp49_;
									gchar* _tmp50_;
									gchar* _tmp51_;
									gchar* _tmp52_;
									_tmp46_ = email;
									_tmp47_ = _person_data;
									_tmp48_ = j;
									_tmp49_ = string_get (_tmp47_, (glong) _tmp48_);
									_tmp50_ = g_strdup_printf ("%c", _tmp49_);
									_tmp51_ = _tmp50_;
									_tmp52_ = g_strconcat (_tmp46_, _tmp51_, NULL);
									_g_free0 (email);
									email = _tmp52_;
									_g_free0 (_tmp51_);
								}
							}
						}
					}
				}
				_tmp53_ = email;
				if (g_strcmp0 (_tmp53_, "") == 0) {
					const gchar* _tmp54_;
					const gchar* _tmp55_;
					gchar* _tmp56_;
					gchar* _tmp57_;
					gchar* _tmp58_;
					gchar* _tmp59_;
					gchar* _tmp60_;
					_tmp54_ = text;
					_tmp55_ = name;
					_tmp56_ = string_strip (_tmp55_);
					_tmp57_ = _tmp56_;
					_tmp58_ = g_strdup_printf ("<u>%s</u>\n", _tmp57_);
					_tmp59_ = _tmp58_;
					_tmp60_ = g_strconcat (_tmp54_, _tmp59_, NULL);
					_g_free0 (text);
					text = _tmp60_;
					_g_free0 (_tmp59_);
					_g_free0 (_tmp57_);
				} else {
					const gchar* _tmp61_;
					const gchar* _tmp62_;
					const gchar* _tmp63_;
					const gchar* _tmp64_;
					gchar* _tmp65_;
					gchar* _tmp66_;
					gchar* _tmp67_;
					gchar* _tmp68_;
					gchar* _tmp69_;
					_tmp61_ = text;
					_tmp62_ = email;
					_tmp63_ = email;
					_tmp64_ = name;
					_tmp65_ = string_strip (_tmp64_);
					_tmp66_ = _tmp65_;
					_tmp67_ = g_strdup_printf ("<a href=\"mailto:%s\" title=\"%s\">%s</a>\n", _tmp62_, _tmp63_, _tmp66_);
					_tmp68_ = _tmp67_;
					_tmp69_ = g_strconcat (_tmp61_, _tmp68_, NULL);
					_g_free0 (text);
					text = _tmp69_;
					_g_free0 (_tmp68_);
					_g_free0 (_tmp66_);
				}
				_tmp70_ = g_strdup ("");
				_g_free0 (email);
				email = _tmp70_;
				_tmp71_ = g_strdup ("");
				_g_free0 (name);
				name = _tmp71_;
				email_started = FALSE;
			}
		}
	}
	_tmp72_ = text;
	_tmp73_ = g_strconcat (_tmp72_, "</span>", NULL);
	_g_free0 (text);
	text = _tmp73_;
	result = text;
	_g_free0 (_person_data);
	_g_free0 (email);
	_g_free0 (name);
	return result;
}


static void granite_gtk_patch_about_dialog_update_logo_image (GraniteGtkPatchAboutDialog* self) {
	gboolean _tmp7_ = FALSE;
	const gchar* _tmp8_;
	const gchar* _tmp9_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	{
		GdkPixbuf* _tmp0_ = NULL;
		GtkIconTheme* _tmp1_;
		GdkPixbuf* _tmp2_;
		GtkImage* _tmp3_;
		_tmp1_ = gtk_icon_theme_get_default ();
		_tmp2_ = gtk_icon_theme_load_icon (_tmp1_, "application-default-icon", 128, 0, &_inner_error_);
		_tmp0_ = _tmp2_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch4_g_error;
		}
		_tmp3_ = self->priv->logo_image;
		gtk_image_set_from_pixbuf (_tmp3_, _tmp0_);
		_g_object_unref0 (_tmp0_);
	}
	goto __finally4;
	__catch4_g_error:
	{
		GError* err = NULL;
		FILE* _tmp4_;
		GError* _tmp5_;
		const gchar* _tmp6_;
		err = _inner_error_;
		_inner_error_ = NULL;
		_tmp4_ = stderr;
		_tmp5_ = err;
		_tmp6_ = _tmp5_->message;
		fprintf (_tmp4_, "Unable to load terminal icon: %s", _tmp6_);
		_g_error_free0 (err);
	}
	__finally4:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp8_ = granite_gtk_patch_about_dialog_get_logo_icon_name (self);
	_tmp9_ = _tmp8_;
	if (_tmp9_ != NULL) {
		const gchar* _tmp10_;
		const gchar* _tmp11_;
		_tmp10_ = granite_gtk_patch_about_dialog_get_logo_icon_name (self);
		_tmp11_ = _tmp10_;
		_tmp7_ = g_strcmp0 (_tmp11_, "") != 0;
	} else {
		_tmp7_ = FALSE;
	}
	if (_tmp7_) {
		{
			GdkPixbuf* _tmp12_ = NULL;
			GtkIconTheme* _tmp13_;
			const gchar* _tmp14_;
			const gchar* _tmp15_;
			GdkPixbuf* _tmp16_;
			GtkImage* _tmp17_;
			_tmp13_ = gtk_icon_theme_get_default ();
			_tmp14_ = granite_gtk_patch_about_dialog_get_logo_icon_name (self);
			_tmp15_ = _tmp14_;
			_tmp16_ = gtk_icon_theme_load_icon (_tmp13_, _tmp15_, 128, 0, &_inner_error_);
			_tmp12_ = _tmp16_;
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch5_g_error;
			}
			_tmp17_ = self->priv->logo_image;
			gtk_image_set_from_pixbuf (_tmp17_, _tmp12_);
			_g_object_unref0 (_tmp12_);
		}
		goto __finally5;
		__catch5_g_error:
		{
			GError* err = NULL;
			FILE* _tmp18_;
			GError* _tmp19_;
			const gchar* _tmp20_;
			err = _inner_error_;
			_inner_error_ = NULL;
			_tmp18_ = stderr;
			_tmp19_ = err;
			_tmp20_ = _tmp19_->message;
			fprintf (_tmp18_, "Unable to load terminal icon: %s", _tmp20_);
			_g_error_free0 (err);
		}
		__finally5:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	} else {
		GdkPixbuf* _tmp21_;
		GdkPixbuf* _tmp22_;
		_tmp21_ = granite_gtk_patch_about_dialog_get_logo (self);
		_tmp22_ = _tmp21_;
		if (_tmp22_ != NULL) {
			GtkImage* _tmp23_;
			GdkPixbuf* _tmp24_;
			GdkPixbuf* _tmp25_;
			_tmp23_ = self->priv->logo_image;
			_tmp24_ = granite_gtk_patch_about_dialog_get_logo (self);
			_tmp25_ = _tmp24_;
			gtk_image_set_from_pixbuf (_tmp23_, _tmp25_);
		}
	}
}


static void granite_gtk_patch_about_dialog_update_license (GraniteGtkPatchAboutDialog* self) {
	GtkLicense _tmp0_;
	GtkLicense _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = granite_gtk_patch_about_dialog_get_license_type (self);
	_tmp1_ = _tmp0_;
	switch (_tmp1_) {
		case GTK_LICENSE_GPL_2_0:
		{
			granite_gtk_patch_about_dialog_set_generic_license (self, "http://www.gnu.org/licenses/old-licenses/gpl-2.0.html", "gpl-2.0");
			break;
		}
		case GTK_LICENSE_GPL_3_0:
		{
			granite_gtk_patch_about_dialog_set_generic_license (self, "http://www.gnu.org/licenses/gpl.html", "gpl");
			break;
		}
		case GTK_LICENSE_LGPL_2_1:
		{
			granite_gtk_patch_about_dialog_set_generic_license (self, "http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html", "lgpl-2.1");
			break;
		}
		case GTK_LICENSE_LGPL_3_0:
		{
			granite_gtk_patch_about_dialog_set_generic_license (self, "http://www.gnu.org/licenses/lgpl.html", "lgpl");
			break;
		}
		case GTK_LICENSE_BSD:
		{
			granite_gtk_patch_about_dialog_set_generic_license (self, "http://opensource.org/licenses/bsd-license.php", "bsd");
			break;
		}
		case GTK_LICENSE_MIT_X11:
		{
			granite_gtk_patch_about_dialog_set_generic_license (self, "http://opensource.org/licenses/mit-license.php", "mit");
			break;
		}
		case GTK_LICENSE_ARTISTIC:
		{
			granite_gtk_patch_about_dialog_set_generic_license (self, "http://opensource.org/licenses/artistic-license-2.0.php", "artistic");
			break;
		}
		default:
		{
			gboolean _tmp2_ = FALSE;
			const gchar* _tmp3_;
			const gchar* _tmp4_;
			_tmp3_ = granite_gtk_patch_about_dialog_get_license (self);
			_tmp4_ = _tmp3_;
			if (_tmp4_ != NULL) {
				const gchar* _tmp5_;
				const gchar* _tmp6_;
				_tmp5_ = granite_gtk_patch_about_dialog_get_license (self);
				_tmp6_ = _tmp5_;
				_tmp2_ = g_strcmp0 (_tmp6_, "") != 0;
			} else {
				_tmp2_ = FALSE;
			}
			if (_tmp2_) {
				GtkLabel* _tmp7_;
				const gchar* _tmp8_;
				const gchar* _tmp9_;
				gchar* _tmp10_;
				gchar* _tmp11_;
				GtkLabel* _tmp12_;
				_tmp7_ = self->priv->license_label;
				_tmp8_ = granite_gtk_patch_about_dialog_get_license (self);
				_tmp9_ = _tmp8_;
				_tmp10_ = g_strconcat (_tmp9_, "\n", NULL);
				_tmp11_ = _tmp10_;
				gtk_label_set_markup (_tmp7_, _tmp11_);
				_g_free0 (_tmp11_);
				_tmp12_ = self->priv->license_label;
				gtk_widget_show ((GtkWidget*) _tmp12_);
			} else {
				GtkLabel* _tmp13_;
				_tmp13_ = self->priv->license_label;
				gtk_widget_hide ((GtkWidget*) _tmp13_);
			}
			break;
		}
	}
}


static void granite_gtk_patch_about_dialog_set_generic_license (GraniteGtkPatchAboutDialog* self, const gchar* url, const gchar* license_type) {
	GtkLabel* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	const gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	const gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
	GtkLabel* _tmp20_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (url != NULL);
	g_return_if_fail (license_type != NULL);
	_tmp0_ = self->priv->license_label;
	_tmp1_ = g_strconcat ("<span size=\"small\">", _ ("This program is published under the terms of the "), NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = license_type;
	_tmp4_ = g_strconcat (_tmp2_, _tmp3_, NULL);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_strconcat (_tmp5_, _ (" license, it comes with ABSOLUTELY NO WARRANTY; for details, visit "), NULL);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_strconcat (_tmp7_, "<a href=\"", NULL);
	_tmp9_ = _tmp8_;
	_tmp10_ = url;
	_tmp11_ = g_strconcat (_tmp9_, _tmp10_, NULL);
	_tmp12_ = _tmp11_;
	_tmp13_ = g_strconcat (_tmp12_, "\">", NULL);
	_tmp14_ = _tmp13_;
	_tmp15_ = url;
	_tmp16_ = g_strconcat (_tmp14_, _tmp15_, NULL);
	_tmp17_ = _tmp16_;
	_tmp18_ = g_strconcat (_tmp17_, "</a></span>\n", NULL);
	_tmp19_ = _tmp18_;
	gtk_label_set_markup (_tmp0_, _tmp19_);
	_g_free0 (_tmp19_);
	_g_free0 (_tmp17_);
	_g_free0 (_tmp14_);
	_g_free0 (_tmp12_);
	_g_free0 (_tmp9_);
	_g_free0 (_tmp7_);
	_g_free0 (_tmp5_);
	_g_free0 (_tmp2_);
	_tmp20_ = self->priv->license_label;
	gtk_widget_show ((GtkWidget*) _tmp20_);
}


static void granite_gtk_patch_about_dialog_set_name_and_version (GraniteGtkPatchAboutDialog* self) {
	gboolean _tmp0_ = FALSE;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	g_return_if_fail (self != NULL);
	_tmp1_ = granite_gtk_patch_about_dialog_get_program_name (self);
	_tmp2_ = _tmp1_;
	if (_tmp2_ != NULL) {
		const gchar* _tmp3_;
		const gchar* _tmp4_;
		_tmp3_ = granite_gtk_patch_about_dialog_get_program_name (self);
		_tmp4_ = _tmp3_;
		_tmp0_ = g_strcmp0 (_tmp4_, "") != 0;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		GtkLabel* _tmp5_;
		const gchar* _tmp6_;
		const gchar* _tmp7_;
		gboolean _tmp8_ = FALSE;
		const gchar* _tmp9_;
		const gchar* _tmp10_;
		GtkLabel* _tmp22_;
		_tmp5_ = self->priv->name_label;
		_tmp6_ = granite_gtk_patch_about_dialog_get_program_name (self);
		_tmp7_ = _tmp6_;
		gtk_label_set_text (_tmp5_, _tmp7_);
		_tmp9_ = granite_gtk_patch_about_dialog_get_version (self);
		_tmp10_ = _tmp9_;
		if (_tmp10_ != NULL) {
			const gchar* _tmp11_;
			const gchar* _tmp12_;
			_tmp11_ = granite_gtk_patch_about_dialog_get_version (self);
			_tmp12_ = _tmp11_;
			_tmp8_ = g_strcmp0 (_tmp12_, "") != 0;
		} else {
			_tmp8_ = FALSE;
		}
		if (_tmp8_) {
			GtkLabel* _tmp13_;
			GtkLabel* _tmp14_;
			const gchar* _tmp15_;
			gchar* _tmp16_;
			gchar* _tmp17_;
			const gchar* _tmp18_;
			const gchar* _tmp19_;
			gchar* _tmp20_;
			gchar* _tmp21_;
			_tmp13_ = self->priv->name_label;
			_tmp14_ = self->priv->name_label;
			_tmp15_ = gtk_label_get_text (_tmp14_);
			_tmp16_ = g_strconcat (_tmp15_, " ", NULL);
			_tmp17_ = _tmp16_;
			_tmp18_ = granite_gtk_patch_about_dialog_get_version (self);
			_tmp19_ = _tmp18_;
			_tmp20_ = g_strconcat (_tmp17_, _tmp19_, NULL);
			_tmp21_ = _tmp20_;
			gtk_label_set_text (_tmp13_, _tmp21_);
			_g_free0 (_tmp21_);
			_g_free0 (_tmp17_);
		}
		_tmp22_ = self->priv->name_label;
		gtk_widget_show ((GtkWidget*) _tmp22_);
	} else {
		GtkLabel* _tmp23_;
		_tmp23_ = self->priv->name_label;
		gtk_widget_hide ((GtkWidget*) _tmp23_);
	}
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	if ((*((gchar*) self)) == '\0') {
		_tmp1_ = TRUE;
	} else {
		const gchar* _tmp2_;
		_tmp2_ = old;
		_tmp1_ = (*((gchar*) _tmp2_)) == '\0';
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		const gchar* _tmp3_;
		const gchar* _tmp4_;
		_tmp3_ = old;
		_tmp4_ = replacement;
		_tmp0_ = g_strcmp0 (_tmp3_, _tmp4_) == 0;
	}
	if (_tmp0_) {
		gchar* _tmp5_;
		_tmp5_ = g_strdup (self);
		result = _tmp5_;
		return result;
	}
	{
		GRegex* regex = NULL;
		const gchar* _tmp6_;
		gchar* _tmp7_;
		gchar* _tmp8_;
		GRegex* _tmp9_;
		GRegex* _tmp10_;
		gchar* _tmp11_ = NULL;
		GRegex* _tmp12_;
		const gchar* _tmp13_;
		gchar* _tmp14_;
		gchar* _tmp15_;
		_tmp6_ = old;
		_tmp7_ = g_regex_escape_string (_tmp6_, -1);
		_tmp8_ = _tmp7_;
		_tmp9_ = g_regex_new (_tmp8_, 0, 0, &_inner_error_);
		_tmp10_ = _tmp9_;
		_g_free0 (_tmp8_);
		regex = _tmp10_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch6_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp12_ = regex;
		_tmp13_ = replacement;
		_tmp14_ = g_regex_replace_literal (_tmp12_, self, (gssize) -1, 0, _tmp13_, 0, &_inner_error_);
		_tmp11_ = _tmp14_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch6_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp15_ = _tmp11_;
		_tmp11_ = NULL;
		result = _tmp15_;
		_g_free0 (_tmp11_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally6;
	__catch6_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally6:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


static void granite_gtk_patch_about_dialog_update_website (GraniteGtkPatchAboutDialog* self) {
	gboolean _tmp0_ = FALSE;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	g_return_if_fail (self != NULL);
	_tmp1_ = granite_gtk_patch_about_dialog_get_website (self);
	_tmp2_ = _tmp1_;
	if (_tmp2_ != NULL) {
		const gchar* _tmp3_;
		const gchar* _tmp4_;
		_tmp3_ = granite_gtk_patch_about_dialog_get_website (self);
		_tmp4_ = _tmp3_;
		_tmp0_ = g_strcmp0 (_tmp4_, "") != 0;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		gboolean _tmp5_ = FALSE;
		const gchar* _tmp6_;
		const gchar* _tmp7_;
		GtkLabel* _tmp30_;
		_tmp6_ = granite_gtk_patch_about_dialog_get_website_label (self);
		_tmp7_ = _tmp6_;
		if (_tmp7_ != NULL) {
			const gchar* _tmp8_;
			const gchar* _tmp9_;
			_tmp8_ = granite_gtk_patch_about_dialog_get_website_label (self);
			_tmp9_ = _tmp8_;
			_tmp5_ = g_strcmp0 (_tmp9_, "") != 0;
		} else {
			_tmp5_ = FALSE;
		}
		if (_tmp5_) {
			GtkLabel* _tmp10_;
			const gchar* _tmp11_;
			const gchar* _tmp12_;
			const gchar* _tmp13_;
			const gchar* _tmp14_;
			const gchar* _tmp15_;
			const gchar* _tmp16_;
			gchar* _tmp17_;
			gchar* _tmp18_;
			gchar* _tmp19_;
			gchar* _tmp20_;
			_tmp10_ = self->priv->website_url_label;
			_tmp11_ = granite_gtk_patch_about_dialog_get_website (self);
			_tmp12_ = _tmp11_;
			_tmp13_ = granite_gtk_patch_about_dialog_get_website (self);
			_tmp14_ = _tmp13_;
			_tmp15_ = granite_gtk_patch_about_dialog_get_website_label (self);
			_tmp16_ = _tmp15_;
			_tmp17_ = string_replace (_tmp16_, "&", "&amp;");
			_tmp18_ = _tmp17_;
			_tmp19_ = g_strdup_printf ("<a href=\"%s\" title=\"%s\">%s</a>\n", _tmp12_, _tmp14_, _tmp18_);
			_tmp20_ = _tmp19_;
			gtk_label_set_markup (_tmp10_, _tmp20_);
			_g_free0 (_tmp20_);
			_g_free0 (_tmp18_);
		} else {
			GtkLabel* _tmp21_;
			const gchar* _tmp22_;
			const gchar* _tmp23_;
			const gchar* _tmp24_;
			const gchar* _tmp25_;
			const gchar* _tmp26_;
			const gchar* _tmp27_;
			gchar* _tmp28_;
			gchar* _tmp29_;
			_tmp21_ = self->priv->website_url_label;
			_tmp22_ = granite_gtk_patch_about_dialog_get_website (self);
			_tmp23_ = _tmp22_;
			_tmp24_ = granite_gtk_patch_about_dialog_get_website (self);
			_tmp25_ = _tmp24_;
			_tmp26_ = granite_gtk_patch_about_dialog_get_website (self);
			_tmp27_ = _tmp26_;
			_tmp28_ = g_strdup_printf ("<a href=\"%s\" title=\"%s\">%s</a>\n", _tmp23_, _tmp25_, _tmp27_);
			_tmp29_ = _tmp28_;
			gtk_label_set_markup (_tmp21_, _tmp29_);
			_g_free0 (_tmp29_);
		}
		_tmp30_ = self->priv->website_url_label;
		gtk_widget_show ((GtkWidget*) _tmp30_);
	} else {
		GtkLabel* _tmp31_;
		_tmp31_ = self->priv->website_url_label;
		gtk_widget_hide ((GtkWidget*) _tmp31_);
	}
}


gchar** granite_gtk_patch_about_dialog_get_artists (GraniteGtkPatchAboutDialog* self, int* result_length1) {
	gchar** result;
	gchar** _tmp0_;
	gint _tmp0__length1;
	gchar** _tmp1_;
	gint _tmp1__length1;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_artists;
	_tmp0__length1 = self->priv->_artists_length1;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = _tmp0__length1;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}


static gchar** _vala_array_dup1 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


void granite_gtk_patch_about_dialog_set_artists (GraniteGtkPatchAboutDialog* self, gchar** value, int value_length1) {
	gchar** _tmp0_;
	gint _tmp0__length1;
	gchar** _tmp1_;
	gint _tmp1__length1;
	gboolean _tmp2_ = FALSE;
	gchar** _tmp3_;
	gint _tmp3__length1;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp0__length1 = value_length1;
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup1 (_tmp0_, _tmp0__length1) : ((gpointer) _tmp0_);
	_tmp1__length1 = _tmp0__length1;
	self->priv->_artists = (_vala_array_free (self->priv->_artists, self->priv->_artists_length1, (GDestroyNotify) g_free), NULL);
	self->priv->_artists = _tmp1_;
	self->priv->_artists_length1 = _tmp1__length1;
	self->priv->__artists_size_ = self->priv->_artists_length1;
	_tmp3_ = self->priv->_artists;
	_tmp3__length1 = self->priv->_artists_length1;
	if (_tmp3_ == NULL) {
		_tmp2_ = TRUE;
	} else {
		gchar** _tmp4_;
		gint _tmp4__length1;
		_tmp4_ = self->priv->_artists;
		_tmp4__length1 = self->priv->_artists_length1;
		_tmp2_ = _tmp4__length1 == 0;
	}
	if (_tmp2_) {
		GtkLabel* _tmp5_;
		GtkLabel* _tmp6_;
		_tmp5_ = self->priv->artists_label;
		gtk_widget_hide ((GtkWidget*) _tmp5_);
		_tmp6_ = self->priv->artists_label;
		gtk_label_set_text (_tmp6_, "");
	} else {
		GtkLabel* _tmp7_;
		gchar* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		gchar* _tmp11_;
		gchar** _tmp12_;
		gint _tmp12__length1;
		gchar* _tmp13_;
		gchar* _tmp14_;
		GtkLabel* _tmp15_;
		_tmp7_ = self->priv->artists_label;
		_tmp8_ = g_strconcat ("<span size=\"small\">", _ ("Designed by:"), NULL);
		_tmp9_ = _tmp8_;
		_tmp10_ = g_strconcat (_tmp9_, "</span>\n", NULL);
		_tmp11_ = _tmp10_;
		_tmp12_ = self->priv->_artists;
		_tmp12__length1 = self->priv->_artists_length1;
		_tmp13_ = granite_gtk_patch_about_dialog_set_string_from_string_array (self, _tmp11_, _tmp12_, _tmp12__length1, FALSE);
		_tmp14_ = _tmp13_;
		gtk_label_set_markup (_tmp7_, _tmp14_);
		_g_free0 (_tmp14_);
		_g_free0 (_tmp11_);
		_g_free0 (_tmp9_);
		_tmp15_ = self->priv->artists_label;
		gtk_widget_show ((GtkWidget*) _tmp15_);
	}
	g_object_notify ((GObject *) self, "artists");
}


gchar** granite_gtk_patch_about_dialog_get_authors (GraniteGtkPatchAboutDialog* self, int* result_length1) {
	gchar** result;
	gchar** _tmp0_;
	gint _tmp0__length1;
	gchar** _tmp1_;
	gint _tmp1__length1;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_authors;
	_tmp0__length1 = self->priv->_authors_length1;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = _tmp0__length1;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}


static gchar** _vala_array_dup2 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


void granite_gtk_patch_about_dialog_set_authors (GraniteGtkPatchAboutDialog* self, gchar** value, int value_length1) {
	gchar** _tmp0_;
	gint _tmp0__length1;
	gchar** _tmp1_;
	gint _tmp1__length1;
	gboolean _tmp2_ = FALSE;
	gchar** _tmp3_;
	gint _tmp3__length1;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp0__length1 = value_length1;
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup2 (_tmp0_, _tmp0__length1) : ((gpointer) _tmp0_);
	_tmp1__length1 = _tmp0__length1;
	self->priv->_authors = (_vala_array_free (self->priv->_authors, self->priv->_authors_length1, (GDestroyNotify) g_free), NULL);
	self->priv->_authors = _tmp1_;
	self->priv->_authors_length1 = _tmp1__length1;
	self->priv->__authors_size_ = self->priv->_authors_length1;
	_tmp3_ = self->priv->_authors;
	_tmp3__length1 = self->priv->_authors_length1;
	if (_tmp3_ == NULL) {
		_tmp2_ = TRUE;
	} else {
		gchar** _tmp4_;
		gint _tmp4__length1;
		_tmp4_ = self->priv->_authors;
		_tmp4__length1 = self->priv->_authors_length1;
		_tmp2_ = _tmp4__length1 == 0;
	}
	if (_tmp2_) {
		GtkLabel* _tmp5_;
		GtkLabel* _tmp6_;
		_tmp5_ = self->priv->authors_label;
		gtk_widget_hide ((GtkWidget*) _tmp5_);
		_tmp6_ = self->priv->authors_label;
		gtk_label_set_text (_tmp6_, "");
	} else {
		GtkLabel* _tmp7_;
		gchar* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		gchar* _tmp11_;
		gchar** _tmp12_;
		gint _tmp12__length1;
		gchar* _tmp13_;
		gchar* _tmp14_;
		GtkLabel* _tmp15_;
		_tmp7_ = self->priv->authors_label;
		_tmp8_ = g_strconcat ("<span size=\"small\">", _ ("Written by:"), NULL);
		_tmp9_ = _tmp8_;
		_tmp10_ = g_strconcat (_tmp9_, "</span>\n", NULL);
		_tmp11_ = _tmp10_;
		_tmp12_ = self->priv->_authors;
		_tmp12__length1 = self->priv->_authors_length1;
		_tmp13_ = granite_gtk_patch_about_dialog_set_string_from_string_array (self, _tmp11_, _tmp12_, _tmp12__length1, FALSE);
		_tmp14_ = _tmp13_;
		gtk_label_set_markup (_tmp7_, _tmp14_);
		_g_free0 (_tmp14_);
		_g_free0 (_tmp11_);
		_g_free0 (_tmp9_);
		_tmp15_ = self->priv->authors_label;
		gtk_widget_show ((GtkWidget*) _tmp15_);
	}
	g_object_notify ((GObject *) self, "authors");
}


const gchar* granite_gtk_patch_about_dialog_get_comments (GraniteGtkPatchAboutDialog* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_comments;
	result = _tmp0_;
	return result;
}


void granite_gtk_patch_about_dialog_set_comments (GraniteGtkPatchAboutDialog* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gboolean _tmp2_ = FALSE;
	const gchar* _tmp3_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_comments);
	self->priv->_comments = _tmp1_;
	_tmp3_ = self->priv->_comments;
	if (_tmp3_ == NULL) {
		_tmp2_ = TRUE;
	} else {
		const gchar* _tmp4_;
		_tmp4_ = self->priv->_comments;
		_tmp2_ = g_strcmp0 (_tmp4_, "") == 0;
	}
	if (_tmp2_) {
		GtkLabel* _tmp5_;
		GtkLabel* _tmp6_;
		_tmp5_ = self->priv->comments_label;
		gtk_widget_hide ((GtkWidget*) _tmp5_);
		_tmp6_ = self->priv->comments_label;
		gtk_label_set_text (_tmp6_, "");
	} else {
		GtkLabel* _tmp7_;
		const gchar* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		GtkLabel* _tmp11_;
		_tmp7_ = self->priv->comments_label;
		_tmp8_ = self->priv->_comments;
		_tmp9_ = g_strconcat (_tmp8_, "\n", NULL);
		_tmp10_ = _tmp9_;
		gtk_label_set_text (_tmp7_, _tmp10_);
		_g_free0 (_tmp10_);
		_tmp11_ = self->priv->comments_label;
		gtk_widget_show ((GtkWidget*) _tmp11_);
	}
	g_object_notify ((GObject *) self, "comments");
}


const gchar* granite_gtk_patch_about_dialog_get_copyright (GraniteGtkPatchAboutDialog* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_copyright;
	result = _tmp0_;
	return result;
}


void granite_gtk_patch_about_dialog_set_copyright (GraniteGtkPatchAboutDialog* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gboolean _tmp2_ = FALSE;
	const gchar* _tmp3_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_copyright);
	self->priv->_copyright = _tmp1_;
	_tmp3_ = self->priv->_copyright;
	if (_tmp3_ == NULL) {
		_tmp2_ = TRUE;
	} else {
		const gchar* _tmp4_;
		_tmp4_ = self->priv->_copyright;
		_tmp2_ = g_strcmp0 (_tmp4_, "") == 0;
	}
	if (_tmp2_) {
		GtkLabel* _tmp5_;
		GtkLabel* _tmp6_;
		_tmp5_ = self->priv->copyright_label;
		gtk_widget_hide ((GtkWidget*) _tmp5_);
		_tmp6_ = self->priv->copyright_label;
		gtk_label_set_text (_tmp6_, "");
	} else {
		GtkLabel* _tmp7_;
		const gchar* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
		gchar* _tmp13_;
		gchar* _tmp14_;
		gchar* _tmp15_;
		gchar* _tmp16_;
		GtkLabel* _tmp17_;
		_tmp7_ = self->priv->copyright_label;
		_tmp8_ = self->priv->_copyright;
		_tmp9_ = string_replace (_tmp8_, "&", "&amp;");
		_tmp10_ = _tmp9_;
		_tmp11_ = g_strdup_printf (_ ("Copyright © %s"), _tmp10_);
		_tmp12_ = _tmp11_;
		_tmp13_ = g_strconcat ("<span size=\"small\">", _tmp12_, NULL);
		_tmp14_ = _tmp13_;
		_tmp15_ = g_strconcat (_tmp14_, "</span>\n", NULL);
		_tmp16_ = _tmp15_;
		gtk_label_set_markup (_tmp7_, _tmp16_);
		_g_free0 (_tmp16_);
		_g_free0 (_tmp14_);
		_g_free0 (_tmp12_);
		_g_free0 (_tmp10_);
		_tmp17_ = self->priv->copyright_label;
		gtk_widget_show ((GtkWidget*) _tmp17_);
	}
	g_object_notify ((GObject *) self, "copyright");
}


gchar** granite_gtk_patch_about_dialog_get_documenters (GraniteGtkPatchAboutDialog* self, int* result_length1) {
	gchar** result;
	gchar** _tmp0_;
	gint _tmp0__length1;
	gchar** _tmp1_;
	gint _tmp1__length1;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_documenters;
	_tmp0__length1 = self->priv->_documenters_length1;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = _tmp0__length1;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}


static gchar** _vala_array_dup3 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


void granite_gtk_patch_about_dialog_set_documenters (GraniteGtkPatchAboutDialog* self, gchar** value, int value_length1) {
	gchar** _tmp0_;
	gint _tmp0__length1;
	gchar** _tmp1_;
	gint _tmp1__length1;
	gboolean _tmp2_ = FALSE;
	gchar** _tmp3_;
	gint _tmp3__length1;
	gchar** _tmp4_;
	gint _tmp4__length1;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp0__length1 = value_length1;
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup3 (_tmp0_, _tmp0__length1) : ((gpointer) _tmp0_);
	_tmp1__length1 = _tmp0__length1;
	self->priv->_documenters = (_vala_array_free (self->priv->_documenters, self->priv->_documenters_length1, (GDestroyNotify) g_free), NULL);
	self->priv->_documenters = _tmp1_;
	self->priv->_documenters_length1 = _tmp1__length1;
	self->priv->__documenters_size_ = self->priv->_documenters_length1;
	_tmp3_ = granite_gtk_patch_about_dialog_get_documenters (self, &_tmp3__length1);
	_tmp4_ = _tmp3_;
	_tmp4__length1 = _tmp3__length1;
	if (_tmp4__length1 == 0) {
		_tmp2_ = TRUE;
	} else {
		gchar** _tmp5_;
		gint _tmp5__length1;
		gchar** _tmp6_;
		gint _tmp6__length1;
		_tmp5_ = granite_gtk_patch_about_dialog_get_documenters (self, &_tmp5__length1);
		_tmp6_ = _tmp5_;
		_tmp6__length1 = _tmp5__length1;
		_tmp2_ = _tmp6_ == NULL;
	}
	if (_tmp2_) {
		GtkLabel* _tmp7_;
		_tmp7_ = self->priv->documenters_label;
		gtk_widget_hide ((GtkWidget*) _tmp7_);
	} else {
		GtkLabel* _tmp8_;
		GtkLabel* _tmp9_;
		gchar* _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
		gchar* _tmp13_;
		gchar** _tmp14_;
		gint _tmp14__length1;
		gchar** _tmp15_;
		gint _tmp15__length1;
		gchar* _tmp16_;
		gchar* _tmp17_;
		_tmp8_ = self->priv->documenters_label;
		gtk_widget_show ((GtkWidget*) _tmp8_);
		_tmp9_ = self->priv->documenters_label;
		_tmp10_ = g_strconcat ("<span size=\"small\">", _ ("Documented by:"), NULL);
		_tmp11_ = _tmp10_;
		_tmp12_ = g_strconcat (_tmp11_, "</span>\n", NULL);
		_tmp13_ = _tmp12_;
		_tmp14_ = granite_gtk_patch_about_dialog_get_documenters (self, &_tmp14__length1);
		_tmp15_ = _tmp14_;
		_tmp15__length1 = _tmp14__length1;
		_tmp16_ = granite_gtk_patch_about_dialog_set_string_from_string_array (self, _tmp13_, _tmp15_, _tmp15__length1, FALSE);
		_tmp17_ = _tmp16_;
		gtk_label_set_markup (_tmp9_, _tmp17_);
		_g_free0 (_tmp17_);
		_g_free0 (_tmp13_);
		_g_free0 (_tmp11_);
	}
	g_object_notify ((GObject *) self, "documenters");
}


const gchar* granite_gtk_patch_about_dialog_get_license (GraniteGtkPatchAboutDialog* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_license;
	result = _tmp0_;
	return result;
}


void granite_gtk_patch_about_dialog_set_license (GraniteGtkPatchAboutDialog* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_license);
	self->priv->_license = _tmp1_;
	granite_gtk_patch_about_dialog_update_license (self);
	g_object_notify ((GObject *) self, "license");
}


GtkLicense granite_gtk_patch_about_dialog_get_license_type (GraniteGtkPatchAboutDialog* self) {
	GtkLicense result;
	GtkLicense _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_license_type;
	result = _tmp0_;
	return result;
}


void granite_gtk_patch_about_dialog_set_license_type (GraniteGtkPatchAboutDialog* self, GtkLicense value) {
	GtkLicense _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_license_type = _tmp0_;
	granite_gtk_patch_about_dialog_update_license (self);
	g_object_notify ((GObject *) self, "license-type");
}


GdkPixbuf* granite_gtk_patch_about_dialog_get_logo (GraniteGtkPatchAboutDialog* self) {
	GdkPixbuf* result;
	GdkPixbuf* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_logo;
	result = _tmp0_;
	return result;
}


void granite_gtk_patch_about_dialog_set_logo (GraniteGtkPatchAboutDialog* self, GdkPixbuf* value) {
	GdkPixbuf* _tmp0_;
	GdkPixbuf* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_logo);
	self->priv->_logo = _tmp1_;
	granite_gtk_patch_about_dialog_update_logo_image (self);
	g_object_notify ((GObject *) self, "logo");
}


const gchar* granite_gtk_patch_about_dialog_get_logo_icon_name (GraniteGtkPatchAboutDialog* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_logo_icon_name;
	result = _tmp0_;
	return result;
}


void granite_gtk_patch_about_dialog_set_logo_icon_name (GraniteGtkPatchAboutDialog* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_logo_icon_name);
	self->priv->_logo_icon_name = _tmp1_;
	granite_gtk_patch_about_dialog_update_logo_image (self);
	g_object_notify ((GObject *) self, "logo-icon-name");
}


const gchar* granite_gtk_patch_about_dialog_get_program_name (GraniteGtkPatchAboutDialog* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_program_name;
	result = _tmp0_;
	return result;
}


void granite_gtk_patch_about_dialog_set_program_name (GraniteGtkPatchAboutDialog* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_program_name);
	self->priv->_program_name = _tmp1_;
	granite_gtk_patch_about_dialog_set_name_and_version (self);
	g_object_notify ((GObject *) self, "program-name");
}


const gchar* granite_gtk_patch_about_dialog_get_translator_credits (GraniteGtkPatchAboutDialog* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_translator_credits;
	result = _tmp0_;
	return result;
}


void granite_gtk_patch_about_dialog_set_translator_credits (GraniteGtkPatchAboutDialog* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gboolean _tmp2_ = FALSE;
	const gchar* _tmp3_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_translator_credits);
	self->priv->_translator_credits = _tmp1_;
	_tmp3_ = self->priv->_translator_credits;
	if (_tmp3_ == NULL) {
		_tmp2_ = TRUE;
	} else {
		const gchar* _tmp4_;
		_tmp4_ = self->priv->_translator_credits;
		_tmp2_ = g_strcmp0 (_tmp4_, "") == 0;
	}
	if (_tmp2_) {
		GtkLabel* _tmp5_;
		GtkLabel* _tmp6_;
		_tmp5_ = self->priv->translators_label;
		gtk_widget_hide ((GtkWidget*) _tmp5_);
		_tmp6_ = self->priv->translators_label;
		gtk_label_set_text (_tmp6_, "");
	} else {
		GtkLabel* _tmp7_;
		const gchar* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
		gchar* _tmp13_;
		gchar* _tmp14_;
		gchar* _tmp15_;
		gchar* _tmp16_;
		GtkLabel* _tmp17_;
		_tmp7_ = self->priv->translators_label;
		_tmp8_ = self->priv->_translator_credits;
		_tmp9_ = string_replace (_tmp8_, "&", "&amp;");
		_tmp10_ = _tmp9_;
		_tmp11_ = g_strdup_printf (_ ("Translated by %s"), _tmp10_);
		_tmp12_ = _tmp11_;
		_tmp13_ = g_strconcat ("<span size=\"small\">", _tmp12_, NULL);
		_tmp14_ = _tmp13_;
		_tmp15_ = g_strconcat (_tmp14_, "</span>", NULL);
		_tmp16_ = _tmp15_;
		gtk_label_set_markup (_tmp7_, _tmp16_);
		_g_free0 (_tmp16_);
		_g_free0 (_tmp14_);
		_g_free0 (_tmp12_);
		_g_free0 (_tmp10_);
		_tmp17_ = self->priv->translators_label;
		gtk_widget_show ((GtkWidget*) _tmp17_);
	}
	g_object_notify ((GObject *) self, "translator-credits");
}


const gchar* granite_gtk_patch_about_dialog_get_version (GraniteGtkPatchAboutDialog* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_version;
	result = _tmp0_;
	return result;
}


void granite_gtk_patch_about_dialog_set_version (GraniteGtkPatchAboutDialog* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_version);
	self->priv->_version = _tmp1_;
	granite_gtk_patch_about_dialog_set_name_and_version (self);
	g_object_notify ((GObject *) self, "version");
}


const gchar* granite_gtk_patch_about_dialog_get_website (GraniteGtkPatchAboutDialog* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_website;
	result = _tmp0_;
	return result;
}


void granite_gtk_patch_about_dialog_set_website (GraniteGtkPatchAboutDialog* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_website);
	self->priv->_website = _tmp1_;
	granite_gtk_patch_about_dialog_update_website (self);
	g_object_notify ((GObject *) self, "website");
}


const gchar* granite_gtk_patch_about_dialog_get_website_label (GraniteGtkPatchAboutDialog* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_website_label;
	result = _tmp0_;
	return result;
}


void granite_gtk_patch_about_dialog_set_website_label (GraniteGtkPatchAboutDialog* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_website_label);
	self->priv->_website_label = _tmp1_;
	granite_gtk_patch_about_dialog_update_website (self);
	g_object_notify ((GObject *) self, "website-label");
}


static gboolean granite_gtk_patch_about_dialog_real_activate_link (GraniteGtkPatchAboutDialog* self, const gchar* uri) {
	gboolean result = FALSE;
	gboolean _result_ = FALSE;
	const gchar* _tmp0_;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (uri != NULL, FALSE);
	_result_ = FALSE;
	_tmp0_ = uri;
	if (_tmp0_ != NULL) {
		{
			gboolean _tmp1_ = FALSE;
			GdkScreen* _tmp2_;
			const gchar* _tmp3_;
			guint32 _tmp4_;
			gboolean _tmp5_;
			_tmp2_ = gtk_window_get_screen ((GtkWindow*) self);
			_tmp3_ = uri;
			_tmp4_ = gtk_get_current_event_time ();
			_tmp5_ = gtk_show_uri (_tmp2_, _tmp3_, _tmp4_, &_inner_error_);
			_tmp1_ = _tmp5_;
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch7_g_error;
			}
			_result_ = _tmp1_;
		}
		goto __finally7;
		__catch7_g_error:
		{
			GError* err = NULL;
			FILE* _tmp6_;
			GError* _tmp7_;
			const gchar* _tmp8_;
			err = _inner_error_;
			_inner_error_ = NULL;
			_tmp6_ = stderr;
			_tmp7_ = err;
			_tmp8_ = _tmp7_->message;
			fprintf (_tmp6_, "Unable to open the URI: %s", _tmp8_);
			_g_error_free0 (err);
		}
		__finally7:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			gboolean _tmp9_ = FALSE;
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return _tmp9_;
		}
	}
	result = _result_;
	return result;
}


static void g_cclosure_user_marshal_BOOLEAN__STRING (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef gboolean (*GMarshalFunc_BOOLEAN__STRING) (gpointer data1, const char* arg_1, gpointer data2);
	register GMarshalFunc_BOOLEAN__STRING callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	gboolean v_return;
	cc = (GCClosure *) closure;
	g_return_if_fail (return_value != NULL);
	g_return_if_fail (n_param_values == 2);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_BOOLEAN__STRING) (marshal_data ? marshal_data : cc->callback);
	v_return = callback (data1, g_value_get_string (param_values + 1), data2);
	g_value_set_boolean (return_value, v_return);
}


static void granite_gtk_patch_about_dialog_class_init (GraniteGtkPatchAboutDialogClass * klass) {
	granite_gtk_patch_about_dialog_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GraniteGtkPatchAboutDialogPrivate));
	((GraniteGtkPatchAboutDialogClass *) klass)->activate_link = granite_gtk_patch_about_dialog_real_activate_link;
	G_OBJECT_CLASS (klass)->get_property = _vala_granite_gtk_patch_about_dialog_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_granite_gtk_patch_about_dialog_set_property;
	G_OBJECT_CLASS (klass)->finalize = granite_gtk_patch_about_dialog_finalize;
	/**
	     * The people who contributed artwork to the program, as a null-terminated array of strings.
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_GTK_PATCH_ABOUT_DIALOG_ARTISTS_PROPERTY, g_param_spec_boxed ("artists", "artists", "artists", G_TYPE_STRV, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * The authors of the program, as a null-terminated array of strings.
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_GTK_PATCH_ABOUT_DIALOG_AUTHORS_PROPERTY, g_param_spec_boxed ("authors", "authors", "authors", G_TYPE_STRV, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * Comments about the program.
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_GTK_PATCH_ABOUT_DIALOG_COMMENTS_PROPERTY, g_param_spec_string ("comments", "comments", "comments", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * Copyright information for the program.
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_GTK_PATCH_ABOUT_DIALOG_COPYRIGHT_PROPERTY, g_param_spec_string ("copyright", "copyright", "copyright", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * The people documenting the program, as a null-terminated array of strings.
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_GTK_PATCH_ABOUT_DIALOG_DOCUMENTERS_PROPERTY, g_param_spec_boxed ("documenters", "documenters", "documenters", G_TYPE_STRV, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * The license of the program.
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_GTK_PATCH_ABOUT_DIALOG_LICENSE_PROPERTY, g_param_spec_string ("license", "license", "license", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_GTK_PATCH_ABOUT_DIALOG_LICENSE_TYPE_PROPERTY, g_param_spec_enum ("license-type", "license-type", "license-type", GTK_TYPE_LICENSE, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * A logo for the about box.
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_GTK_PATCH_ABOUT_DIALOG_LOGO_PROPERTY, g_param_spec_object ("logo", "logo", "logo", gdk_pixbuf_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * A named icon to use as the logo for the about box.
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_GTK_PATCH_ABOUT_DIALOG_LOGO_ICON_NAME_PROPERTY, g_param_spec_string ("logo-icon-name", "logo-icon-name", "logo-icon-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * The name of the program.
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_GTK_PATCH_ABOUT_DIALOG_PROGRAM_NAME_PROPERTY, g_param_spec_string ("program-name", "program-name", "program-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * Credits to the translators.
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_GTK_PATCH_ABOUT_DIALOG_TRANSLATOR_CREDITS_PROPERTY, g_param_spec_string ("translator-credits", "translator-credits", "translator-credits", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * The version of the program.
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_GTK_PATCH_ABOUT_DIALOG_VERSION_PROPERTY, g_param_spec_string ("version", "version", "version", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * The URL for the link to the website of the program.
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_GTK_PATCH_ABOUT_DIALOG_WEBSITE_PROPERTY, g_param_spec_string ("website", "website", "website", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	     * The label for the link to the website of the program.
	     */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_GTK_PATCH_ABOUT_DIALOG_WEBSITE_LABEL_PROPERTY, g_param_spec_string ("website-label", "website-label", "website-label", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	granite_gtk_patch_about_dialog_signals[GRANITE_GTK_PATCH_ABOUT_DIALOG_ACTIVATE_LINK_SIGNAL] = g_signal_new ("activate-link", GRANITE_GTK_PATCH_TYPE_ABOUT_DIALOG, G_SIGNAL_RUN_LAST, G_STRUCT_OFFSET (GraniteGtkPatchAboutDialogClass, activate_link), NULL, NULL, g_cclosure_user_marshal_BOOLEAN__STRING, G_TYPE_BOOLEAN, 1, G_TYPE_STRING);
}


static void granite_gtk_patch_about_dialog_instance_init (GraniteGtkPatchAboutDialog * self) {
	gchar** _tmp0_;
	gchar** _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar** _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	self->priv = GRANITE_GTK_PATCH_ABOUT_DIALOG_GET_PRIVATE (self);
	_tmp0_ = g_new0 (gchar*, 0 + 1);
	self->priv->_artists = _tmp0_;
	self->priv->_artists_length1 = 0;
	self->priv->__artists_size_ = self->priv->_artists_length1;
	_tmp1_ = g_new0 (gchar*, 0 + 1);
	self->priv->_authors = _tmp1_;
	self->priv->_authors_length1 = 0;
	self->priv->__authors_size_ = self->priv->_authors_length1;
	_tmp2_ = g_strdup ("");
	self->priv->_comments = _tmp2_;
	_tmp3_ = g_strdup ("");
	self->priv->_copyright = _tmp3_;
	_tmp4_ = g_new0 (gchar*, 0 + 1);
	self->priv->_documenters = _tmp4_;
	self->priv->_documenters_length1 = 0;
	self->priv->__documenters_size_ = self->priv->_documenters_length1;
	_tmp5_ = g_strdup ("");
	self->priv->_license = _tmp5_;
	self->priv->_license_type = GTK_LICENSE_UNKNOWN;
	self->priv->_logo = NULL;
	_tmp6_ = g_strdup ("");
	self->priv->_logo_icon_name = _tmp6_;
	_tmp7_ = g_strdup ("");
	self->priv->_program_name = _tmp7_;
	_tmp8_ = g_strdup ("");
	self->priv->_translator_credits = _tmp8_;
	_tmp9_ = g_strdup ("");
	self->priv->_version = _tmp9_;
	_tmp10_ = g_strdup ("");
	self->priv->_website = _tmp10_;
	_tmp11_ = g_strdup ("");
	self->priv->_website_label = _tmp11_;
}


static void granite_gtk_patch_about_dialog_finalize (GObject * obj) {
	GraniteGtkPatchAboutDialog * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRANITE_GTK_PATCH_TYPE_ABOUT_DIALOG, GraniteGtkPatchAboutDialog);
	self->priv->_artists = (_vala_array_free (self->priv->_artists, self->priv->_artists_length1, (GDestroyNotify) g_free), NULL);
	self->priv->_authors = (_vala_array_free (self->priv->_authors, self->priv->_authors_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (self->priv->_comments);
	_g_free0 (self->priv->_copyright);
	self->priv->_documenters = (_vala_array_free (self->priv->_documenters, self->priv->_documenters_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (self->priv->_license);
	_g_object_unref0 (self->priv->_logo);
	_g_free0 (self->priv->_logo_icon_name);
	_g_free0 (self->priv->_program_name);
	_g_free0 (self->priv->_translator_credits);
	_g_free0 (self->priv->_version);
	_g_free0 (self->priv->_website);
	_g_free0 (self->priv->_website_label);
	_g_object_unref0 (self->priv->logo_image);
	_g_object_unref0 (self->priv->name_label);
	_g_object_unref0 (self->priv->copyright_label);
	_g_object_unref0 (self->priv->comments_label);
	_g_object_unref0 (self->priv->authors_label);
	_g_object_unref0 (self->priv->artists_label);
	_g_object_unref0 (self->priv->documenters_label);
	_g_object_unref0 (self->priv->translators_label);
	_g_object_unref0 (self->priv->license_label);
	_g_object_unref0 (self->priv->website_url_label);
	_g_object_unref0 (self->priv->close_button);
	G_OBJECT_CLASS (granite_gtk_patch_about_dialog_parent_class)->finalize (obj);
}


/***
    Copyright (C) 2011-2013 Adrien Plazas <kekun.plazas@laposte.net>

    This program or library is free software; you can redistribute it
    and/or modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 3 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
    Lesser General Public License for more details.
 
    You should have received a copy of the GNU Lesser General
    Public License along with this library; if not, write to the
    Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301 USA.
***/
GType granite_gtk_patch_about_dialog_get_type (void) {
	static volatile gsize granite_gtk_patch_about_dialog_type_id__volatile = 0;
	if (g_once_init_enter (&granite_gtk_patch_about_dialog_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraniteGtkPatchAboutDialogClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) granite_gtk_patch_about_dialog_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraniteGtkPatchAboutDialog), 0, (GInstanceInitFunc) granite_gtk_patch_about_dialog_instance_init, NULL };
		GType granite_gtk_patch_about_dialog_type_id;
		granite_gtk_patch_about_dialog_type_id = g_type_register_static (gtk_dialog_get_type (), "GraniteGtkPatchAboutDialog", &g_define_type_info, 0);
		g_once_init_leave (&granite_gtk_patch_about_dialog_type_id__volatile, granite_gtk_patch_about_dialog_type_id);
	}
	return granite_gtk_patch_about_dialog_type_id__volatile;
}


static void _vala_granite_gtk_patch_about_dialog_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GraniteGtkPatchAboutDialog * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GRANITE_GTK_PATCH_TYPE_ABOUT_DIALOG, GraniteGtkPatchAboutDialog);
	switch (property_id) {
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_ARTISTS_PROPERTY:
		{
			int length;
			g_value_set_boxed (value, granite_gtk_patch_about_dialog_get_artists (self, &length));
		}
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_AUTHORS_PROPERTY:
		{
			int length;
			g_value_set_boxed (value, granite_gtk_patch_about_dialog_get_authors (self, &length));
		}
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_COMMENTS_PROPERTY:
		g_value_set_string (value, granite_gtk_patch_about_dialog_get_comments (self));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_COPYRIGHT_PROPERTY:
		g_value_set_string (value, granite_gtk_patch_about_dialog_get_copyright (self));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_DOCUMENTERS_PROPERTY:
		{
			int length;
			g_value_set_boxed (value, granite_gtk_patch_about_dialog_get_documenters (self, &length));
		}
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_LICENSE_PROPERTY:
		g_value_set_string (value, granite_gtk_patch_about_dialog_get_license (self));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_LICENSE_TYPE_PROPERTY:
		g_value_set_enum (value, granite_gtk_patch_about_dialog_get_license_type (self));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_LOGO_PROPERTY:
		g_value_set_object (value, granite_gtk_patch_about_dialog_get_logo (self));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_LOGO_ICON_NAME_PROPERTY:
		g_value_set_string (value, granite_gtk_patch_about_dialog_get_logo_icon_name (self));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_PROGRAM_NAME_PROPERTY:
		g_value_set_string (value, granite_gtk_patch_about_dialog_get_program_name (self));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_TRANSLATOR_CREDITS_PROPERTY:
		g_value_set_string (value, granite_gtk_patch_about_dialog_get_translator_credits (self));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_VERSION_PROPERTY:
		g_value_set_string (value, granite_gtk_patch_about_dialog_get_version (self));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_WEBSITE_PROPERTY:
		g_value_set_string (value, granite_gtk_patch_about_dialog_get_website (self));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_WEBSITE_LABEL_PROPERTY:
		g_value_set_string (value, granite_gtk_patch_about_dialog_get_website_label (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_granite_gtk_patch_about_dialog_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GraniteGtkPatchAboutDialog * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GRANITE_GTK_PATCH_TYPE_ABOUT_DIALOG, GraniteGtkPatchAboutDialog);
	switch (property_id) {
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_ARTISTS_PROPERTY:
		{
			gpointer boxed;
			boxed = g_value_get_boxed (value);
			granite_gtk_patch_about_dialog_set_artists (self, boxed, (boxed == NULL) ? 0 : g_strv_length (boxed));
		}
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_AUTHORS_PROPERTY:
		{
			gpointer boxed;
			boxed = g_value_get_boxed (value);
			granite_gtk_patch_about_dialog_set_authors (self, boxed, (boxed == NULL) ? 0 : g_strv_length (boxed));
		}
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_COMMENTS_PROPERTY:
		granite_gtk_patch_about_dialog_set_comments (self, g_value_get_string (value));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_COPYRIGHT_PROPERTY:
		granite_gtk_patch_about_dialog_set_copyright (self, g_value_get_string (value));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_DOCUMENTERS_PROPERTY:
		{
			gpointer boxed;
			boxed = g_value_get_boxed (value);
			granite_gtk_patch_about_dialog_set_documenters (self, boxed, (boxed == NULL) ? 0 : g_strv_length (boxed));
		}
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_LICENSE_PROPERTY:
		granite_gtk_patch_about_dialog_set_license (self, g_value_get_string (value));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_LICENSE_TYPE_PROPERTY:
		granite_gtk_patch_about_dialog_set_license_type (self, g_value_get_enum (value));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_LOGO_PROPERTY:
		granite_gtk_patch_about_dialog_set_logo (self, g_value_get_object (value));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_LOGO_ICON_NAME_PROPERTY:
		granite_gtk_patch_about_dialog_set_logo_icon_name (self, g_value_get_string (value));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_PROGRAM_NAME_PROPERTY:
		granite_gtk_patch_about_dialog_set_program_name (self, g_value_get_string (value));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_TRANSLATOR_CREDITS_PROPERTY:
		granite_gtk_patch_about_dialog_set_translator_credits (self, g_value_get_string (value));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_VERSION_PROPERTY:
		granite_gtk_patch_about_dialog_set_version (self, g_value_get_string (value));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_WEBSITE_PROPERTY:
		granite_gtk_patch_about_dialog_set_website (self, g_value_get_string (value));
		break;
		case GRANITE_GTK_PATCH_ABOUT_DIALOG_WEBSITE_LABEL_PROPERTY:
		granite_gtk_patch_about_dialog_set_website_label (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



