/* Logger.c generated by valac 0.36.7, the Vala compiler
 * generated from Logger.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#define GRANITE_SERVICES_TYPE_LOG_LEVEL (granite_services_log_level_get_type ())

#define GRANITE_SERVICES_TYPE_CONSOLE_COLOR (granite_services_console_color_get_type ())

#define GRANITE_SERVICES_TYPE_LOGGER (granite_services_logger_get_type ())
#define GRANITE_SERVICES_LOGGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_SERVICES_TYPE_LOGGER, GraniteServicesLogger))
#define GRANITE_SERVICES_LOGGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_SERVICES_TYPE_LOGGER, GraniteServicesLoggerClass))
#define GRANITE_SERVICES_IS_LOGGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_SERVICES_TYPE_LOGGER))
#define GRANITE_SERVICES_IS_LOGGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_SERVICES_TYPE_LOGGER))
#define GRANITE_SERVICES_LOGGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_SERVICES_TYPE_LOGGER, GraniteServicesLoggerClass))

typedef struct _GraniteServicesLogger GraniteServicesLogger;
typedef struct _GraniteServicesLoggerClass GraniteServicesLoggerClass;
typedef struct _GraniteServicesLoggerPrivate GraniteServicesLoggerPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

typedef enum  {
	GRANITE_SERVICES_LOG_LEVEL_DEBUG,
	GRANITE_SERVICES_LOG_LEVEL_INFO,
	GRANITE_SERVICES_LOG_LEVEL_NOTIFY,
	GRANITE_SERVICES_LOG_LEVEL_WARN,
	GRANITE_SERVICES_LOG_LEVEL_ERROR,
	GRANITE_SERVICES_LOG_LEVEL_FATAL
} GraniteServicesLogLevel;

typedef enum  {
	GRANITE_SERVICES_CONSOLE_COLOR_BLACK,
	GRANITE_SERVICES_CONSOLE_COLOR_RED,
	GRANITE_SERVICES_CONSOLE_COLOR_GREEN,
	GRANITE_SERVICES_CONSOLE_COLOR_YELLOW,
	GRANITE_SERVICES_CONSOLE_COLOR_BLUE,
	GRANITE_SERVICES_CONSOLE_COLOR_MAGENTA,
	GRANITE_SERVICES_CONSOLE_COLOR_CYAN,
	GRANITE_SERVICES_CONSOLE_COLOR_WHITE
} GraniteServicesConsoleColor;

struct _GraniteServicesLogger {
	GObject parent_instance;
	GraniteServicesLoggerPrivate * priv;
};

struct _GraniteServicesLoggerClass {
	GObjectClass parent_class;
};


static gpointer granite_services_logger_parent_class = NULL;
static GraniteServicesLogLevel granite_services_logger__DisplayLevel;
static GraniteServicesLogLevel granite_services_logger__DisplayLevel = GRANITE_SERVICES_LOG_LEVEL_WARN;
static gchar* granite_services_logger__AppName;
static gchar* granite_services_logger__AppName = NULL;
static GRegex* granite_services_logger_re;
static GRegex* granite_services_logger_re = NULL;

GType granite_services_log_level_get_type (void) G_GNUC_CONST;
GType granite_services_console_color_get_type (void) G_GNUC_CONST;
GType granite_services_logger_get_type (void) G_GNUC_CONST;
enum  {
	GRANITE_SERVICES_LOGGER_0_PROPERTY
};
void granite_services_logger_initialize (const gchar* app_name);
static const gchar* granite_services_logger_get_AppName (void);
static void granite_services_logger_set_AppName (const gchar* value);
static void granite_services_logger_glib_log_func (const gchar* d, GLogLevelFlags flags, const gchar* msg);
static void _granite_services_logger_glib_log_func_glog_func (const gchar* log_domain, GLogLevelFlags log_levels, const gchar* message, gpointer self);
static gchar* granite_services_logger_format_message (const gchar* msg);
void granite_services_logger_notification (const gchar* msg);
static void granite_services_logger_write (GraniteServicesLogLevel level, const gchar* msg);
static gchar* granite_services_logger_get_time (void);
GraniteServicesLogLevel granite_services_logger_get_DisplayLevel (void);
static void granite_services_logger_set_color_for_level (GraniteServicesLogLevel level);
const gchar* granite_services_log_level_to_string (GraniteServicesLogLevel self);
static void granite_services_logger_reset_color (void);
static void granite_services_logger_set_foreground (GraniteServicesConsoleColor color);
static void granite_services_logger_set_background (GraniteServicesConsoleColor color);
static void granite_services_logger_set_color (GraniteServicesConsoleColor color, gboolean isForeground);
GraniteServicesLogger* granite_services_logger_new (void);
GraniteServicesLogger* granite_services_logger_construct (GType object_type);
void granite_services_logger_set_DisplayLevel (GraniteServicesLogLevel value);
static void granite_services_logger_finalize (GObject * obj);
static void _vala_granite_services_logger_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_granite_services_logger_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


/**
     * LogLevel:
     */
GType granite_services_log_level_get_type (void) {
	static volatile gsize granite_services_log_level_type_id__volatile = 0;
	if (g_once_init_enter (&granite_services_log_level_type_id__volatile)) {
		static const GEnumValue values[] = {{GRANITE_SERVICES_LOG_LEVEL_DEBUG, "GRANITE_SERVICES_LOG_LEVEL_DEBUG", "debug"}, {GRANITE_SERVICES_LOG_LEVEL_INFO, "GRANITE_SERVICES_LOG_LEVEL_INFO", "info"}, {GRANITE_SERVICES_LOG_LEVEL_NOTIFY, "GRANITE_SERVICES_LOG_LEVEL_NOTIFY", "notify"}, {GRANITE_SERVICES_LOG_LEVEL_WARN, "GRANITE_SERVICES_LOG_LEVEL_WARN", "warn"}, {GRANITE_SERVICES_LOG_LEVEL_ERROR, "GRANITE_SERVICES_LOG_LEVEL_ERROR", "error"}, {GRANITE_SERVICES_LOG_LEVEL_FATAL, "GRANITE_SERVICES_LOG_LEVEL_FATAL", "fatal"}, {0, NULL, NULL}};
		GType granite_services_log_level_type_id;
		granite_services_log_level_type_id = g_enum_register_static ("GraniteServicesLogLevel", values);
		g_once_init_leave (&granite_services_log_level_type_id__volatile, granite_services_log_level_type_id);
	}
	return granite_services_log_level_type_id__volatile;
}


GType granite_services_console_color_get_type (void) {
	static volatile gsize granite_services_console_color_type_id__volatile = 0;
	if (g_once_init_enter (&granite_services_console_color_type_id__volatile)) {
		static const GEnumValue values[] = {{GRANITE_SERVICES_CONSOLE_COLOR_BLACK, "GRANITE_SERVICES_CONSOLE_COLOR_BLACK", "black"}, {GRANITE_SERVICES_CONSOLE_COLOR_RED, "GRANITE_SERVICES_CONSOLE_COLOR_RED", "red"}, {GRANITE_SERVICES_CONSOLE_COLOR_GREEN, "GRANITE_SERVICES_CONSOLE_COLOR_GREEN", "green"}, {GRANITE_SERVICES_CONSOLE_COLOR_YELLOW, "GRANITE_SERVICES_CONSOLE_COLOR_YELLOW", "yellow"}, {GRANITE_SERVICES_CONSOLE_COLOR_BLUE, "GRANITE_SERVICES_CONSOLE_COLOR_BLUE", "blue"}, {GRANITE_SERVICES_CONSOLE_COLOR_MAGENTA, "GRANITE_SERVICES_CONSOLE_COLOR_MAGENTA", "magenta"}, {GRANITE_SERVICES_CONSOLE_COLOR_CYAN, "GRANITE_SERVICES_CONSOLE_COLOR_CYAN", "cyan"}, {GRANITE_SERVICES_CONSOLE_COLOR_WHITE, "GRANITE_SERVICES_CONSOLE_COLOR_WHITE", "white"}, {0, NULL, NULL}};
		GType granite_services_console_color_type_id;
		granite_services_console_color_type_id = g_enum_register_static ("GraniteServicesConsoleColor", values);
		g_once_init_leave (&granite_services_console_color_type_id__volatile, granite_services_console_color_type_id);
	}
	return granite_services_console_color_type_id__volatile;
}


/**
         * This method initializes the Logger
         * 
         * @param app_name name of app that is logging
         */
static void _granite_services_logger_glib_log_func_glog_func (const gchar* log_domain, GLogLevelFlags log_levels, const gchar* message, gpointer self) {
	granite_services_logger_glib_log_func (log_domain, log_levels, message);
}


void granite_services_logger_initialize (const gchar* app_name) {
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	g_return_if_fail (app_name != NULL);
	_tmp0_ = granite_services_logger_get_AppName ();
	_tmp1_ = _tmp0_;
	_tmp2_ = app_name;
	granite_services_logger_set_AppName (_tmp2_);
	g_log_set_default_handler (_granite_services_logger_glib_log_func_glog_func, NULL);
}


/**
         * Formats a message to be logged
         * 
         * @param msg message to be formatted
         */
static gchar* granite_services_logger_format_message (const gchar* msg) {
	gchar* result = NULL;
	gboolean _tmp0_ = FALSE;
	GRegex* _tmp1_;
	const gchar* _tmp16_;
	gchar* _tmp17_;
	g_return_val_if_fail (msg != NULL, NULL);
	_tmp1_ = granite_services_logger_re;
	if (_tmp1_ != NULL) {
		GRegex* _tmp2_;
		const gchar* _tmp3_;
		gboolean _tmp4_;
		_tmp2_ = granite_services_logger_re;
		_tmp3_ = msg;
		_tmp4_ = g_regex_match (_tmp2_, _tmp3_, 0, NULL);
		_tmp0_ = _tmp4_;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		gchar** parts = NULL;
		GRegex* _tmp5_;
		const gchar* _tmp6_;
		gchar** _tmp7_;
		gchar** _tmp8_;
		gint parts_length1;
		gint _parts_size_;
		gchar** _tmp9_;
		gint _tmp9__length1;
		const gchar* _tmp10_;
		gchar** _tmp11_;
		gint _tmp11__length1;
		const gchar* _tmp12_;
		gchar** _tmp13_;
		gint _tmp13__length1;
		const gchar* _tmp14_;
		gchar* _tmp15_;
		_tmp5_ = granite_services_logger_re;
		_tmp6_ = msg;
		_tmp8_ = _tmp7_ = g_regex_split (_tmp5_, _tmp6_, 0);
		parts = _tmp8_;
		parts_length1 = _vala_array_length (_tmp7_);
		_parts_size_ = parts_length1;
		_tmp9_ = parts;
		_tmp9__length1 = parts_length1;
		_tmp10_ = _tmp9_[1];
		_tmp11_ = parts;
		_tmp11__length1 = parts_length1;
		_tmp12_ = _tmp11_[2];
		_tmp13_ = parts;
		_tmp13__length1 = parts_length1;
		_tmp14_ = _tmp13_[3];
		_tmp15_ = g_strdup_printf ("[%s%s] %s", _tmp10_, _tmp12_, _tmp14_);
		result = _tmp15_;
		parts = (_vala_array_free (parts, parts_length1, (GDestroyNotify) g_free), NULL);
		return result;
	}
	_tmp16_ = msg;
	_tmp17_ = g_strdup (_tmp16_);
	result = _tmp17_;
	return result;
}


/**
         * Logs message using Notify level formatting
         * 
         * @param msg message to be logged
         */
void granite_services_logger_notification (const gchar* msg) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	g_return_if_fail (msg != NULL);
	_tmp0_ = msg;
	_tmp1_ = granite_services_logger_format_message (_tmp0_);
	_tmp2_ = _tmp1_;
	granite_services_logger_write (GRANITE_SERVICES_LOG_LEVEL_NOTIFY, _tmp2_);
	_g_free0 (_tmp2_);
}


static gchar* granite_services_logger_get_time (void) {
	gchar* result = NULL;
	GDateTime* now = NULL;
	GDateTime* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	gint _tmp4_;
	gchar* _tmp5_;
	_tmp0_ = g_date_time_new_now_local ();
	now = _tmp0_;
	_tmp1_ = g_date_time_get_hour (now);
	_tmp2_ = g_date_time_get_minute (now);
	_tmp3_ = g_date_time_get_second (now);
	_tmp4_ = g_date_time_get_microsecond (now);
	_tmp5_ = g_strdup_printf ("%.2d:%.2d:%.2d.%.6d", _tmp1_, _tmp2_, _tmp3_, _tmp4_);
	result = _tmp5_;
	_g_date_time_unref0 (now);
	return result;
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_;
	glong _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_;
		gchar* _tmp6_;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_;
	glong _tmp8_;
	glong _tmp14_;
	glong _tmp17_;
	glong _tmp18_;
	glong _tmp19_;
	glong _tmp20_;
	glong _tmp21_;
	gchar* _tmp22_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		glong _tmp3_;
		glong _tmp4_;
		glong _tmp5_;
		_tmp3_ = offset;
		_tmp4_ = len;
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
		string_length = _tmp5_;
	} else {
		gint _tmp6_;
		gint _tmp7_;
		_tmp6_ = strlen (self);
		_tmp7_ = _tmp6_;
		string_length = (glong) _tmp7_;
	}
	_tmp8_ = offset;
	if (_tmp8_ < ((glong) 0)) {
		glong _tmp9_;
		glong _tmp10_;
		glong _tmp11_;
		_tmp9_ = string_length;
		_tmp10_ = offset;
		offset = _tmp9_ + _tmp10_;
		_tmp11_ = offset;
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
	} else {
		glong _tmp12_;
		glong _tmp13_;
		_tmp12_ = offset;
		_tmp13_ = string_length;
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
	}
	_tmp14_ = len;
	if (_tmp14_ < ((glong) 0)) {
		glong _tmp15_;
		glong _tmp16_;
		_tmp15_ = string_length;
		_tmp16_ = offset;
		len = _tmp15_ - _tmp16_;
	}
	_tmp17_ = offset;
	_tmp18_ = len;
	_tmp19_ = string_length;
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
	_tmp20_ = offset;
	_tmp21_ = len;
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
	result = _tmp22_;
	return result;
}


static void granite_services_logger_write (GraniteServicesLogLevel level, const gchar* msg) {
	GraniteServicesLogLevel _tmp0_;
	GraniteServicesLogLevel _tmp1_;
	GraniteServicesLogLevel _tmp2_;
	GraniteServicesLogLevel _tmp3_;
	FILE* _tmp4_;
	GraniteServicesLogLevel _tmp5_;
	GEnumValue* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	FILE* _tmp11_;
	const gchar* _tmp12_;
	g_return_if_fail (msg != NULL);
	_tmp0_ = level;
	_tmp1_ = granite_services_logger_get_DisplayLevel ();
	_tmp2_ = _tmp1_;
	if (_tmp0_ < _tmp2_) {
		return;
	}
	_tmp3_ = level;
	granite_services_logger_set_color_for_level (_tmp3_);
	_tmp4_ = stdout;
	_tmp5_ = level;
	_tmp6_ = g_enum_get_value (g_type_class_ref (GRANITE_SERVICES_TYPE_LOG_LEVEL), _tmp5_);
	_tmp7_ = string_substring ((_tmp6_ != NULL) ? _tmp6_->value_name : NULL, (glong) 16, (glong) -1);
	_tmp8_ = _tmp7_;
	_tmp9_ = granite_services_logger_get_time ();
	_tmp10_ = _tmp9_;
	fprintf (_tmp4_, "[%s %s]", _tmp8_, _tmp10_);
	_g_free0 (_tmp10_);
	_g_free0 (_tmp8_);
	granite_services_logger_reset_color ();
	_tmp11_ = stdout;
	_tmp12_ = msg;
	fprintf (_tmp11_, " %s\n", _tmp12_);
}


static void granite_services_logger_set_color_for_level (GraniteServicesLogLevel level) {
	GraniteServicesLogLevel _tmp0_;
	_tmp0_ = level;
	switch (_tmp0_) {
		case GRANITE_SERVICES_LOG_LEVEL_DEBUG:
		{
			granite_services_logger_set_foreground (GRANITE_SERVICES_CONSOLE_COLOR_GREEN);
			break;
		}
		case GRANITE_SERVICES_LOG_LEVEL_INFO:
		{
			granite_services_logger_set_foreground (GRANITE_SERVICES_CONSOLE_COLOR_BLUE);
			break;
		}
		case GRANITE_SERVICES_LOG_LEVEL_NOTIFY:
		{
			granite_services_logger_set_foreground (GRANITE_SERVICES_CONSOLE_COLOR_MAGENTA);
			break;
		}
		case GRANITE_SERVICES_LOG_LEVEL_WARN:
		{
			granite_services_logger_set_foreground (GRANITE_SERVICES_CONSOLE_COLOR_YELLOW);
			break;
		}
		case GRANITE_SERVICES_LOG_LEVEL_ERROR:
		{
			granite_services_logger_set_foreground (GRANITE_SERVICES_CONSOLE_COLOR_RED);
			break;
		}
		case GRANITE_SERVICES_LOG_LEVEL_FATAL:
		{
			granite_services_logger_set_background (GRANITE_SERVICES_CONSOLE_COLOR_RED);
			granite_services_logger_set_foreground (GRANITE_SERVICES_CONSOLE_COLOR_WHITE);
			break;
		}
		default:
		break;
	}
}


static void granite_services_logger_reset_color (void) {
	FILE* _tmp0_;
	_tmp0_ = stdout;
	fprintf (_tmp0_, "\x001b[0m");
}


static void granite_services_logger_set_foreground (GraniteServicesConsoleColor color) {
	GraniteServicesConsoleColor _tmp0_;
	_tmp0_ = color;
	granite_services_logger_set_color (_tmp0_, TRUE);
}


static void granite_services_logger_set_background (GraniteServicesConsoleColor color) {
	GraniteServicesConsoleColor _tmp0_;
	_tmp0_ = color;
	granite_services_logger_set_color (_tmp0_, FALSE);
}


static void granite_services_logger_set_color (GraniteServicesConsoleColor color, gboolean isForeground) {
	GraniteServicesConsoleColor color_code = 0;
	GraniteServicesConsoleColor _tmp0_;
	gboolean _tmp1_;
	FILE* _tmp3_;
	GraniteServicesConsoleColor _tmp4_;
	_tmp0_ = color;
	color_code = (_tmp0_ + 30) + 60;
	_tmp1_ = isForeground;
	if (!_tmp1_) {
		GraniteServicesConsoleColor _tmp2_;
		_tmp2_ = color_code;
		color_code = _tmp2_ + 10;
	}
	_tmp3_ = stdout;
	_tmp4_ = color_code;
	fprintf (_tmp3_, "\x001b[%dm", (gint) _tmp4_);
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	if ((*((gchar*) self)) == '\0') {
		_tmp1_ = TRUE;
	} else {
		const gchar* _tmp2_;
		_tmp2_ = old;
		_tmp1_ = (*((gchar*) _tmp2_)) == '\0';
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		const gchar* _tmp3_;
		const gchar* _tmp4_;
		_tmp3_ = old;
		_tmp4_ = replacement;
		_tmp0_ = g_strcmp0 (_tmp3_, _tmp4_) == 0;
	}
	if (_tmp0_) {
		gchar* _tmp5_;
		_tmp5_ = g_strdup (self);
		result = _tmp5_;
		return result;
	}
	{
		GRegex* regex = NULL;
		const gchar* _tmp6_;
		gchar* _tmp7_;
		gchar* _tmp8_;
		GRegex* _tmp9_;
		GRegex* _tmp10_;
		gchar* _tmp11_ = NULL;
		GRegex* _tmp12_;
		const gchar* _tmp13_;
		gchar* _tmp14_;
		gchar* _tmp15_;
		_tmp6_ = old;
		_tmp7_ = g_regex_escape_string (_tmp6_, -1);
		_tmp8_ = _tmp7_;
		_tmp9_ = g_regex_new (_tmp8_, 0, 0, &_inner_error_);
		_tmp10_ = _tmp9_;
		_g_free0 (_tmp8_);
		regex = _tmp10_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch8_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp12_ = regex;
		_tmp13_ = replacement;
		_tmp14_ = g_regex_replace_literal (_tmp12_, self, (gssize) -1, 0, _tmp13_, 0, &_inner_error_);
		_tmp11_ = _tmp14_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch8_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp15_ = _tmp11_;
		_tmp11_ = NULL;
		result = _tmp15_;
		_g_free0 (_tmp11_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally8;
	__catch8_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally8:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


static void granite_services_logger_glib_log_func (const gchar* d, GLogLevelFlags flags, const gchar* msg) {
	gchar* domain = NULL;
	gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* message = NULL;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	const gchar* _tmp9_;
	const gchar* _tmp10_;
	gchar* _tmp11_;
	GLogLevelFlags _tmp12_;
	g_return_if_fail (msg != NULL);
	_tmp0_ = g_strdup ("");
	domain = _tmp0_;
	_tmp1_ = d;
	if (_tmp1_ != NULL) {
		const gchar* _tmp2_;
		gchar* _tmp3_;
		_tmp2_ = d;
		_tmp3_ = g_strdup_printf ("[%s] ", _tmp2_);
		_g_free0 (domain);
		domain = _tmp3_;
	}
	_tmp4_ = msg;
	_tmp5_ = string_replace (_tmp4_, "\n", "");
	_tmp6_ = _tmp5_;
	_tmp7_ = string_replace (_tmp6_, "\r", "");
	_tmp8_ = _tmp7_;
	_g_free0 (_tmp6_);
	message = _tmp8_;
	_tmp9_ = domain;
	_tmp10_ = message;
	_tmp11_ = g_strdup_printf ("%s%s", _tmp9_, _tmp10_);
	_g_free0 (message);
	message = _tmp11_;
	_tmp12_ = flags;
	switch (_tmp12_) {
		case G_LOG_LEVEL_CRITICAL:
		{
			const gchar* _tmp13_;
			gchar* _tmp14_;
			gchar* _tmp15_;
			const gchar* _tmp16_;
			const gchar* _tmp17_;
			gchar* _tmp18_;
			gchar* _tmp19_;
			gchar* _tmp20_;
			gchar* _tmp21_;
			_tmp13_ = message;
			_tmp14_ = granite_services_logger_format_message (_tmp13_);
			_tmp15_ = _tmp14_;
			granite_services_logger_write (GRANITE_SERVICES_LOG_LEVEL_FATAL, _tmp15_);
			_g_free0 (_tmp15_);
			_tmp16_ = granite_services_logger_get_AppName ();
			_tmp17_ = _tmp16_;
			_tmp18_ = g_strconcat (_tmp17_, " will not function properly.", NULL);
			_tmp19_ = _tmp18_;
			_tmp20_ = granite_services_logger_format_message (_tmp19_);
			_tmp21_ = _tmp20_;
			granite_services_logger_write (GRANITE_SERVICES_LOG_LEVEL_FATAL, _tmp21_);
			_g_free0 (_tmp21_);
			_g_free0 (_tmp19_);
			break;
		}
		case G_LOG_LEVEL_ERROR:
		{
			const gchar* _tmp22_;
			gchar* _tmp23_;
			gchar* _tmp24_;
			_tmp22_ = message;
			_tmp23_ = granite_services_logger_format_message (_tmp22_);
			_tmp24_ = _tmp23_;
			granite_services_logger_write (GRANITE_SERVICES_LOG_LEVEL_ERROR, _tmp24_);
			_g_free0 (_tmp24_);
			break;
		}
		case G_LOG_LEVEL_INFO:
		case G_LOG_LEVEL_MESSAGE:
		{
			const gchar* _tmp25_;
			gchar* _tmp26_;
			gchar* _tmp27_;
			_tmp25_ = message;
			_tmp26_ = granite_services_logger_format_message (_tmp25_);
			_tmp27_ = _tmp26_;
			granite_services_logger_write (GRANITE_SERVICES_LOG_LEVEL_INFO, _tmp27_);
			_g_free0 (_tmp27_);
			break;
		}
		case G_LOG_LEVEL_DEBUG:
		{
			const gchar* _tmp28_;
			gchar* _tmp29_;
			gchar* _tmp30_;
			_tmp28_ = message;
			_tmp29_ = granite_services_logger_format_message (_tmp28_);
			_tmp30_ = _tmp29_;
			granite_services_logger_write (GRANITE_SERVICES_LOG_LEVEL_DEBUG, _tmp30_);
			_g_free0 (_tmp30_);
			break;
		}
		default:
		case G_LOG_LEVEL_WARNING:
		{
			const gchar* _tmp31_;
			gchar* _tmp32_;
			gchar* _tmp33_;
			_tmp31_ = message;
			_tmp32_ = granite_services_logger_format_message (_tmp31_);
			_tmp33_ = _tmp32_;
			granite_services_logger_write (GRANITE_SERVICES_LOG_LEVEL_WARN, _tmp33_);
			_g_free0 (_tmp33_);
			break;
		}
	}
	_g_free0 (message);
	_g_free0 (domain);
}


GraniteServicesLogger* granite_services_logger_construct (GType object_type) {
	GraniteServicesLogger * self = NULL;
	self = (GraniteServicesLogger*) g_object_new (object_type, NULL);
	return self;
}


GraniteServicesLogger* granite_services_logger_new (void) {
	return granite_services_logger_construct (GRANITE_SERVICES_TYPE_LOGGER);
}


GraniteServicesLogLevel granite_services_logger_get_DisplayLevel (void) {
	GraniteServicesLogLevel result;
	GraniteServicesLogLevel _tmp0_;
	_tmp0_ = granite_services_logger__DisplayLevel;
	result = _tmp0_;
	return result;
}


void granite_services_logger_set_DisplayLevel (GraniteServicesLogLevel value) {
	GraniteServicesLogLevel _tmp0_;
	_tmp0_ = value;
	granite_services_logger__DisplayLevel = _tmp0_;
}


static const gchar* granite_services_logger_get_AppName (void) {
	const gchar* result;
	const gchar* _tmp0_;
	_tmp0_ = granite_services_logger__AppName;
	result = _tmp0_;
	return result;
}


static void granite_services_logger_set_AppName (const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (granite_services_logger__AppName);
	granite_services_logger__AppName = _tmp1_;
}


static void granite_services_logger_class_init (GraniteServicesLoggerClass * klass) {
	granite_services_logger_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->get_property = _vala_granite_services_logger_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_granite_services_logger_set_property;
	G_OBJECT_CLASS (klass)->finalize = granite_services_logger_finalize;
}


static void granite_services_logger_instance_init (GraniteServicesLogger * self) {
}


static void granite_services_logger_finalize (GObject * obj) {
	GraniteServicesLogger * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRANITE_SERVICES_TYPE_LOGGER, GraniteServicesLogger);
	G_OBJECT_CLASS (granite_services_logger_parent_class)->finalize (obj);
}


/**
     * This class helps in the use of logs in a Granite application.
     * 
     */
GType granite_services_logger_get_type (void) {
	static volatile gsize granite_services_logger_type_id__volatile = 0;
	if (g_once_init_enter (&granite_services_logger_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraniteServicesLoggerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) granite_services_logger_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraniteServicesLogger), 0, (GInstanceInitFunc) granite_services_logger_instance_init, NULL };
		GType granite_services_logger_type_id;
		granite_services_logger_type_id = g_type_register_static (G_TYPE_OBJECT, "GraniteServicesLogger", &g_define_type_info, 0);
		g_once_init_leave (&granite_services_logger_type_id__volatile, granite_services_logger_type_id);
	}
	return granite_services_logger_type_id__volatile;
}


static void _vala_granite_services_logger_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GraniteServicesLogger * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GRANITE_SERVICES_TYPE_LOGGER, GraniteServicesLogger);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_granite_services_logger_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GraniteServicesLogger * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GRANITE_SERVICES_TYPE_LOGGER, GraniteServicesLogger);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



