/* SimpleCommand.c generated by valac 0.36.7, the Vala compiler
 * generated from SimpleCommand.vala, do not modify */

/***
    Copyright (C) 2011-2013 Lucas Baudin <xapantu@gmail.com>

    This program or library is free software; you can redistribute it
    and/or modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 3 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
    Lesser General Public License for more details.
 
    You should have received a copy of the GNU Lesser General
    Public License along with this library; if not, write to the
    Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301 USA.
***/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define GRANITE_SERVICES_TYPE_SIMPLE_COMMAND (granite_services_simple_command_get_type ())
#define GRANITE_SERVICES_SIMPLE_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_SERVICES_TYPE_SIMPLE_COMMAND, GraniteServicesSimpleCommand))
#define GRANITE_SERVICES_SIMPLE_COMMAND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_SERVICES_TYPE_SIMPLE_COMMAND, GraniteServicesSimpleCommandClass))
#define GRANITE_SERVICES_IS_SIMPLE_COMMAND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_SERVICES_TYPE_SIMPLE_COMMAND))
#define GRANITE_SERVICES_IS_SIMPLE_COMMAND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_SERVICES_TYPE_SIMPLE_COMMAND))
#define GRANITE_SERVICES_SIMPLE_COMMAND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_SERVICES_TYPE_SIMPLE_COMMAND, GraniteServicesSimpleCommandClass))

typedef struct _GraniteServicesSimpleCommand GraniteServicesSimpleCommand;
typedef struct _GraniteServicesSimpleCommandClass GraniteServicesSimpleCommandClass;
typedef struct _GraniteServicesSimpleCommandPrivate GraniteServicesSimpleCommandPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_io_channel_unref0(var) ((var == NULL) ? NULL : (var = (g_io_channel_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
enum  {
	GRANITE_SERVICES_SIMPLE_COMMAND_DONE_SIGNAL,
	GRANITE_SERVICES_SIMPLE_COMMAND_OUTPUT_CHANGED_SIGNAL,
	GRANITE_SERVICES_SIMPLE_COMMAND_STANDARD_CHANGED_SIGNAL,
	GRANITE_SERVICES_SIMPLE_COMMAND_ERROR_CHANGED_SIGNAL,
	GRANITE_SERVICES_SIMPLE_COMMAND_NUM_SIGNALS
};
static guint granite_services_simple_command_signals[GRANITE_SERVICES_SIMPLE_COMMAND_NUM_SIGNALS] = {0};

struct _GraniteServicesSimpleCommand {
	GObject parent_instance;
	GraniteServicesSimpleCommandPrivate * priv;
	gchar* standard_output_str;
	gchar* error_output_str;
	gchar* output_str;
};

struct _GraniteServicesSimpleCommandClass {
	GObjectClass parent_class;
};

struct _GraniteServicesSimpleCommandPrivate {
	GIOChannel* out_make;
	GIOChannel* error_out;
	gchar* dir;
	gchar* command;
	GPid pid;
};


static gpointer granite_services_simple_command_parent_class = NULL;

GType granite_services_simple_command_get_type (void) G_GNUC_CONST;
#define GRANITE_SERVICES_SIMPLE_COMMAND_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GRANITE_SERVICES_TYPE_SIMPLE_COMMAND, GraniteServicesSimpleCommandPrivate))
enum  {
	GRANITE_SERVICES_SIMPLE_COMMAND_0_PROPERTY
};
GraniteServicesSimpleCommand* granite_services_simple_command_new (const gchar* dir, const gchar* command);
GraniteServicesSimpleCommand* granite_services_simple_command_construct (GType object_type, const gchar* dir, const gchar* command);
void granite_services_simple_command_run (GraniteServicesSimpleCommand* self);
static void __lambda23_ (GraniteServicesSimpleCommand* self, GPid pid, gint exit);
static void ___lambda23__gchild_watch_func (GPid pid, gint status, gpointer self);
static gboolean __lambda24_ (GraniteServicesSimpleCommand* self, GIOChannel* source, GIOCondition condition);
static gboolean ___lambda24__gio_func (GIOChannel* source, GIOCondition condition, gpointer self);
static gboolean __lambda25_ (GraniteServicesSimpleCommand* self, GIOChannel* source, GIOCondition condition);
static gboolean ___lambda25__gio_func (GIOChannel* source, GIOCondition condition, gpointer self);
static void granite_services_simple_command_finalize (GObject * obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


/**
     * Create a new object. You will have to call run() when you want to run the command.
     *
     * @param dir The working dir
     * @param command The command to execute (using absolute paths like /usr/bin/make causes less
     * strange bugs).
     *
     */
GraniteServicesSimpleCommand* granite_services_simple_command_construct (GType object_type, const gchar* dir, const gchar* command) {
	GraniteServicesSimpleCommand * self = NULL;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	g_return_val_if_fail (dir != NULL, NULL);
	g_return_val_if_fail (command != NULL, NULL);
	self = (GraniteServicesSimpleCommand*) g_object_new (object_type, NULL);
	_tmp0_ = dir;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->dir);
	self->priv->dir = _tmp1_;
	_tmp2_ = command;
	_tmp3_ = g_strdup (_tmp2_);
	_g_free0 (self->priv->command);
	self->priv->command = _tmp3_;
	return self;
}


GraniteServicesSimpleCommand* granite_services_simple_command_new (const gchar* dir, const gchar* command) {
	return granite_services_simple_command_construct (GRANITE_SERVICES_TYPE_SIMPLE_COMMAND, dir, command);
}


/**
     * Launch the command. It is async.
     */
static void __lambda23_ (GraniteServicesSimpleCommand* self, GPid pid, gint exit) {
	gint _tmp0_;
	_tmp0_ = exit;
	g_signal_emit (self, granite_services_simple_command_signals[GRANITE_SERVICES_SIMPLE_COMMAND_DONE_SIGNAL], 0, _tmp0_);
}


static void ___lambda23__gchild_watch_func (GPid pid, gint status, gpointer self) {
	__lambda23_ ((GraniteServicesSimpleCommand*) self, pid, status);
}


static gboolean __lambda24_ (GraniteServicesSimpleCommand* self, GIOChannel* source, GIOCondition condition) {
	gboolean result = FALSE;
	GIOCondition _tmp0_;
	gchar* output = NULL;
	const gchar* _tmp7_;
	const gchar* _tmp8_;
	gchar* _tmp9_;
	const gchar* _tmp10_;
	const gchar* _tmp11_;
	gchar* _tmp12_;
	const gchar* _tmp13_;
	const gchar* _tmp14_;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (source != NULL, FALSE);
	_tmp0_ = condition;
	if (_tmp0_ == G_IO_HUP) {
		result = FALSE;
		return result;
	}
	output = NULL;
	{
		GIOChannel* _tmp1_;
		gchar* _tmp2_ = NULL;
		_tmp1_ = self->priv->out_make;
		g_io_channel_read_line (_tmp1_, &_tmp2_, NULL, NULL, &_inner_error_);
		_g_free0 (output);
		output = _tmp2_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch18_g_error;
		}
	}
	goto __finally18;
	__catch18_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp3_;
		GError* _tmp4_;
		const gchar* _tmp5_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp3_ = self->priv->command;
		_tmp4_ = e;
		_tmp5_ = _tmp4_->message;
		g_critical ("SimpleCommand.vala:124: Error in the output retrieving of %s: %s", _tmp3_, _tmp5_);
		_g_error_free0 (e);
	}
	__finally18:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		gboolean _tmp6_ = FALSE;
		_g_free0 (output);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return _tmp6_;
	}
	_tmp7_ = self->standard_output_str;
	_tmp8_ = output;
	_tmp9_ = g_strconcat (_tmp7_, _tmp8_, NULL);
	_g_free0 (self->standard_output_str);
	self->standard_output_str = _tmp9_;
	_tmp10_ = self->output_str;
	_tmp11_ = output;
	_tmp12_ = g_strconcat (_tmp10_, _tmp11_, NULL);
	_g_free0 (self->output_str);
	self->output_str = _tmp12_;
	_tmp13_ = output;
	g_signal_emit (self, granite_services_simple_command_signals[GRANITE_SERVICES_SIMPLE_COMMAND_STANDARD_CHANGED_SIGNAL], 0, _tmp13_);
	_tmp14_ = output;
	g_signal_emit (self, granite_services_simple_command_signals[GRANITE_SERVICES_SIMPLE_COMMAND_OUTPUT_CHANGED_SIGNAL], 0, _tmp14_);
	result = TRUE;
	_g_free0 (output);
	return result;
}


static gboolean ___lambda24__gio_func (GIOChannel* source, GIOCondition condition, gpointer self) {
	gboolean result;
	result = __lambda24_ ((GraniteServicesSimpleCommand*) self, source, condition);
	return result;
}


static gboolean __lambda25_ (GraniteServicesSimpleCommand* self, GIOChannel* source, GIOCondition condition) {
	gboolean result = FALSE;
	GIOCondition _tmp0_;
	gchar* output = NULL;
	const gchar* _tmp7_;
	const gchar* _tmp8_;
	gchar* _tmp9_;
	const gchar* _tmp10_;
	const gchar* _tmp11_;
	gchar* _tmp12_;
	const gchar* _tmp13_;
	const gchar* _tmp14_;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (source != NULL, FALSE);
	_tmp0_ = condition;
	if (_tmp0_ == G_IO_HUP) {
		result = FALSE;
		return result;
	}
	output = NULL;
	{
		GIOChannel* _tmp1_;
		gchar* _tmp2_ = NULL;
		_tmp1_ = self->priv->error_out;
		g_io_channel_read_line (_tmp1_, &_tmp2_, NULL, NULL, &_inner_error_);
		_g_free0 (output);
		output = _tmp2_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch19_g_error;
		}
	}
	goto __finally19;
	__catch19_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp3_;
		GError* _tmp4_;
		const gchar* _tmp5_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp3_ = self->priv->command;
		_tmp4_ = e;
		_tmp5_ = _tmp4_->message;
		g_critical ("SimpleCommand.vala:149: Error in the output retrieving of %s: %s", _tmp3_, _tmp5_);
		_g_error_free0 (e);
	}
	__finally19:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		gboolean _tmp6_ = FALSE;
		_g_free0 (output);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return _tmp6_;
	}
	_tmp7_ = self->error_output_str;
	_tmp8_ = output;
	_tmp9_ = g_strconcat (_tmp7_, _tmp8_, NULL);
	_g_free0 (self->error_output_str);
	self->error_output_str = _tmp9_;
	_tmp10_ = self->output_str;
	_tmp11_ = output;
	_tmp12_ = g_strconcat (_tmp10_, _tmp11_, NULL);
	_g_free0 (self->output_str);
	self->output_str = _tmp12_;
	_tmp13_ = output;
	g_signal_emit (self, granite_services_simple_command_signals[GRANITE_SERVICES_SIMPLE_COMMAND_ERROR_CHANGED_SIGNAL], 0, _tmp13_);
	_tmp14_ = output;
	g_signal_emit (self, granite_services_simple_command_signals[GRANITE_SERVICES_SIMPLE_COMMAND_OUTPUT_CHANGED_SIGNAL], 0, _tmp14_);
	result = TRUE;
	_g_free0 (output);
	return result;
}


static gboolean ___lambda25__gio_func (GIOChannel* source, GIOCondition condition, gpointer self) {
	gboolean result;
	result = __lambda25_ ((GraniteServicesSimpleCommand*) self, source, condition);
	return result;
}


void granite_services_simple_command_run (GraniteServicesSimpleCommand* self) {
	gint standard_output = 0;
	gint standard_error = 0;
	GPid _tmp12_;
	gint _tmp13_;
	GIOChannel* _tmp14_;
	GIOChannel* _tmp15_;
	gint _tmp16_;
	GIOChannel* _tmp17_;
	GIOChannel* _tmp18_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	standard_output = 0;
	standard_error = 0;
	{
		const gchar* _tmp0_;
		const gchar* _tmp1_;
		gchar** _tmp2_;
		gchar** _tmp3_;
		gchar** _tmp4_;
		gint _tmp4__length1;
		GPid _tmp5_ = 0;
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		_tmp0_ = self->priv->dir;
		_tmp1_ = self->priv->command;
		_tmp3_ = _tmp2_ = g_strsplit (_tmp1_, " ", 0);
		_tmp4_ = _tmp3_;
		_tmp4__length1 = _vala_array_length (_tmp2_);
		g_spawn_async_with_pipes (_tmp0_, _tmp4_, NULL, G_SPAWN_DO_NOT_REAP_CHILD, NULL, NULL, &_tmp5_, NULL, &_tmp6_, &_tmp7_, &_inner_error_);
		self->priv->pid = _tmp5_;
		standard_output = _tmp6_;
		standard_error = _tmp7_;
		_tmp4_ = (_vala_array_free (_tmp4_, _tmp4__length1, (GDestroyNotify) g_free), NULL);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch17_g_error;
		}
	}
	goto __finally17;
	__catch17_g_error:
	{
		GError* e = NULL;
		const gchar* _tmp8_;
		const gchar* _tmp9_;
		GError* _tmp10_;
		const gchar* _tmp11_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp8_ = self->priv->command;
		_tmp9_ = self->priv->dir;
		_tmp10_ = e;
		_tmp11_ = _tmp10_->message;
		g_critical ("SimpleCommand.vala:105: Couldn't launch command %s in the directory %s" \
": %s", _tmp8_, _tmp9_, _tmp11_);
		_g_error_free0 (e);
	}
	__finally17:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp12_ = self->priv->pid;
	g_child_watch_add_full (G_PRIORITY_DEFAULT_IDLE, _tmp12_, ___lambda23__gchild_watch_func, g_object_ref (self), g_object_unref);
	_tmp13_ = standard_output;
	_tmp14_ = g_io_channel_unix_new (_tmp13_);
	_g_io_channel_unref0 (self->priv->out_make);
	self->priv->out_make = _tmp14_;
	_tmp15_ = self->priv->out_make;
	g_io_add_watch (_tmp15_, G_IO_IN | G_IO_HUP, ___lambda24__gio_func, self);
	_tmp16_ = standard_error;
	_tmp17_ = g_io_channel_unix_new (_tmp16_);
	_g_io_channel_unref0 (self->priv->error_out);
	self->priv->error_out = _tmp17_;
	_tmp18_ = self->priv->error_out;
	g_io_add_watch (_tmp18_, G_IO_IN | G_IO_HUP, ___lambda25__gio_func, self);
}


static void granite_services_simple_command_class_init (GraniteServicesSimpleCommandClass * klass) {
	granite_services_simple_command_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GraniteServicesSimpleCommandPrivate));
	G_OBJECT_CLASS (klass)->finalize = granite_services_simple_command_finalize;
	/**
	     * Emitted when the command is finished.
	     */
	granite_services_simple_command_signals[GRANITE_SERVICES_SIMPLE_COMMAND_DONE_SIGNAL] = g_signal_new ("done", GRANITE_SERVICES_TYPE_SIMPLE_COMMAND, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__INT, G_TYPE_NONE, 1, G_TYPE_INT);
	/**
	     * When the output changed (std.out and std.err).
	     *
	     * @param text the new text
	     */
	granite_services_simple_command_signals[GRANITE_SERVICES_SIMPLE_COMMAND_OUTPUT_CHANGED_SIGNAL] = g_signal_new ("output-changed", GRANITE_SERVICES_TYPE_SIMPLE_COMMAND, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
	/**
	     * When the standard output is changed.
	     *
	     * @param text the new text from std.out
	     */
	granite_services_simple_command_signals[GRANITE_SERVICES_SIMPLE_COMMAND_STANDARD_CHANGED_SIGNAL] = g_signal_new ("standard-changed", GRANITE_SERVICES_TYPE_SIMPLE_COMMAND, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
	/**
	     * When the error output is changed.
	     *
	     * @param text the new text from std.err
	     */
	granite_services_simple_command_signals[GRANITE_SERVICES_SIMPLE_COMMAND_ERROR_CHANGED_SIGNAL] = g_signal_new ("error-changed", GRANITE_SERVICES_TYPE_SIMPLE_COMMAND, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__STRING, G_TYPE_NONE, 1, G_TYPE_STRING);
}


static void granite_services_simple_command_instance_init (GraniteServicesSimpleCommand * self) {
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	self->priv = GRANITE_SERVICES_SIMPLE_COMMAND_GET_PRIVATE (self);
	_tmp0_ = g_strdup ("");
	self->standard_output_str = _tmp0_;
	_tmp1_ = g_strdup ("");
	self->error_output_str = _tmp1_;
	_tmp2_ = g_strdup ("");
	self->output_str = _tmp2_;
}


static void granite_services_simple_command_finalize (GObject * obj) {
	GraniteServicesSimpleCommand * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRANITE_SERVICES_TYPE_SIMPLE_COMMAND, GraniteServicesSimpleCommand);
	_g_free0 (self->standard_output_str);
	_g_free0 (self->error_output_str);
	_g_free0 (self->output_str);
	_g_io_channel_unref0 (self->priv->out_make);
	_g_io_channel_unref0 (self->priv->error_out);
	_g_free0 (self->priv->dir);
	_g_free0 (self->priv->command);
	G_OBJECT_CLASS (granite_services_simple_command_parent_class)->finalize (obj);
}


/**
 * This class is a wrapper to run an async command. It provides useful signals.
 */
GType granite_services_simple_command_get_type (void) {
	static volatile gsize granite_services_simple_command_type_id__volatile = 0;
	if (g_once_init_enter (&granite_services_simple_command_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraniteServicesSimpleCommandClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) granite_services_simple_command_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraniteServicesSimpleCommand), 0, (GInstanceInitFunc) granite_services_simple_command_instance_init, NULL };
		GType granite_services_simple_command_type_id;
		granite_services_simple_command_type_id = g_type_register_static (G_TYPE_OBJECT, "GraniteServicesSimpleCommand", &g_define_type_info, 0);
		g_once_init_leave (&granite_services_simple_command_type_id__volatile, granite_services_simple_command_type_id);
	}
	return granite_services_simple_command_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



