/* style-classes.c generated by valac 0.36.7, the Vala compiler
 * generated from style-classes.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




#define GRANITE_STYLE_CLASS_CATEGORY_EXPANDER "category-expander"
#define GRANITE_STYLE_CLASS_COMPOSITED "composited"
#define GRANITE_STYLE_CLASS_BADGE "badge"
#define GRANITE_STYLE_CLASS_CONTENT_VIEW "content-view"
#define GRANITE_STYLE_CLASS_CONTENT_VIEW_WINDOW "content-view-window"
#define GRANITE_STYLE_CLASS_DECORATED_WINDOW "decorated-window"
#define GRANITE_STYLE_CLASS_SOURCE_LIST "source-list"
#define GRANITE_STYLE_CLASS_POPOVER "popover"
#define GRANITE_STYLE_CLASS_POPOVER_BG "popover_bg"
#define GRANITE_STYLE_CLASS_HELP_BUTTON "help_button"
#define GRANITE_STYLE_CLASS_THIN_PANE_SEPARATOR "sidebar-pane-separator"
#define GRANITE_STYLE_CLASS_OVERLAY_BAR "overlay-bar"
#define GRANITE_STYLE_CLASS_TITLE_TEXT "title"
#define GRANITE_STYLE_CLASS_H1_TEXT "h1"
#define GRANITE_STYLE_CLASS_H2_TEXT "h2"
#define GRANITE_STYLE_CLASS_H3_TEXT "h3"



