/* AppMenu.c generated by valac 0.36.7, the Vala compiler
 * generated from AppMenu.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>


#define GRANITE_WIDGETS_TYPE_TOOL_BUTTON_WITH_MENU (granite_widgets_tool_button_with_menu_get_type ())
#define GRANITE_WIDGETS_TOOL_BUTTON_WITH_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_WIDGETS_TYPE_TOOL_BUTTON_WITH_MENU, GraniteWidgetsToolButtonWithMenu))
#define GRANITE_WIDGETS_TOOL_BUTTON_WITH_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_WIDGETS_TYPE_TOOL_BUTTON_WITH_MENU, GraniteWidgetsToolButtonWithMenuClass))
#define GRANITE_WIDGETS_IS_TOOL_BUTTON_WITH_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_WIDGETS_TYPE_TOOL_BUTTON_WITH_MENU))
#define GRANITE_WIDGETS_IS_TOOL_BUTTON_WITH_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_WIDGETS_TYPE_TOOL_BUTTON_WITH_MENU))
#define GRANITE_WIDGETS_TOOL_BUTTON_WITH_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_WIDGETS_TYPE_TOOL_BUTTON_WITH_MENU, GraniteWidgetsToolButtonWithMenuClass))

typedef struct _GraniteWidgetsToolButtonWithMenu GraniteWidgetsToolButtonWithMenu;
typedef struct _GraniteWidgetsToolButtonWithMenuClass GraniteWidgetsToolButtonWithMenuClass;
typedef struct _GraniteWidgetsToolButtonWithMenuPrivate GraniteWidgetsToolButtonWithMenuPrivate;

#define GRANITE_WIDGETS_TYPE_APP_MENU (granite_widgets_app_menu_get_type ())
#define GRANITE_WIDGETS_APP_MENU(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_WIDGETS_TYPE_APP_MENU, GraniteWidgetsAppMenu))
#define GRANITE_WIDGETS_APP_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_WIDGETS_TYPE_APP_MENU, GraniteWidgetsAppMenuClass))
#define GRANITE_WIDGETS_IS_APP_MENU(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_WIDGETS_TYPE_APP_MENU))
#define GRANITE_WIDGETS_IS_APP_MENU_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_WIDGETS_TYPE_APP_MENU))
#define GRANITE_WIDGETS_APP_MENU_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_WIDGETS_TYPE_APP_MENU, GraniteWidgetsAppMenuClass))

typedef struct _GraniteWidgetsAppMenu GraniteWidgetsAppMenu;
typedef struct _GraniteWidgetsAppMenuClass GraniteWidgetsAppMenuClass;
typedef struct _GraniteWidgetsAppMenuPrivate GraniteWidgetsAppMenuPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define GRANITE_TYPE_APPLICATION (granite_application_get_type ())
#define GRANITE_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_TYPE_APPLICATION, GraniteApplication))
#define GRANITE_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_TYPE_APPLICATION, GraniteApplicationClass))
#define GRANITE_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_TYPE_APPLICATION))
#define GRANITE_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_TYPE_APPLICATION))
#define GRANITE_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_TYPE_APPLICATION, GraniteApplicationClass))

typedef struct _GraniteApplication GraniteApplication;
typedef struct _GraniteApplicationClass GraniteApplicationClass;
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))
enum  {
	GRANITE_WIDGETS_APP_MENU_SHOW_ABOUT_SIGNAL,
	GRANITE_WIDGETS_APP_MENU_NUM_SIGNALS
};
static guint granite_widgets_app_menu_signals[GRANITE_WIDGETS_APP_MENU_NUM_SIGNALS] = {0};

struct _GraniteWidgetsToolButtonWithMenu {
	GtkToggleToolButton parent_instance;
	GraniteWidgetsToolButtonWithMenuPrivate * priv;
	GtkAction* myaction;
	gulong toggled_sig_id;
};

struct _GraniteWidgetsToolButtonWithMenuClass {
	GtkToggleToolButtonClass parent_class;
};

struct _GraniteWidgetsAppMenu {
	GraniteWidgetsToolButtonWithMenu parent_instance;
	GraniteWidgetsAppMenuPrivate * priv;
	GtkMenuItem* about_item;
};

struct _GraniteWidgetsAppMenuClass {
	GraniteWidgetsToolButtonWithMenuClass parent_class;
};


static gpointer granite_widgets_app_menu_parent_class = NULL;

GType granite_widgets_tool_button_with_menu_get_type (void) G_GNUC_CONST;
GType granite_widgets_app_menu_get_type (void) G_GNUC_CONST;
enum  {
	GRANITE_WIDGETS_APP_MENU_0_PROPERTY
};
GraniteWidgetsAppMenu* granite_widgets_app_menu_new (GtkMenu* menu);
GraniteWidgetsAppMenu* granite_widgets_app_menu_construct (GType object_type, GtkMenu* menu);
GraniteWidgetsToolButtonWithMenu* granite_widgets_tool_button_with_menu_new (GtkImage* image, const gchar* label, GtkMenu* menu);
GraniteWidgetsToolButtonWithMenu* granite_widgets_tool_button_with_menu_construct (GType object_type, GtkImage* image, const gchar* label, GtkMenu* menu);
GType granite_application_get_type (void) G_GNUC_CONST;
GraniteWidgetsAppMenu* granite_widgets_app_menu_new_with_app (GraniteApplication* application, GtkMenu* menu);
GraniteWidgetsAppMenu* granite_widgets_app_menu_construct_with_app (GType object_type, GraniteApplication* application, GtkMenu* menu);
void granite_widgets_app_menu_add_items (GraniteWidgetsAppMenu* self, GtkMenu* menu);
static void __lambda22_ (GraniteWidgetsAppMenu* self);
static void ___lambda22__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
GraniteWidgetsAppMenu* granite_widgets_app_menu_new_with_urls (GtkMenu* menu, const gchar* help_url, const gchar* translate_url, const gchar* bug_url) G_GNUC_DEPRECATED;
GraniteWidgetsAppMenu* granite_widgets_app_menu_construct_with_urls (GType object_type, GtkMenu* menu, const gchar* help_url, const gchar* translate_url, const gchar* bug_url) G_GNUC_DEPRECATED;
static void granite_widgets_app_menu_finalize (GObject * obj);


/**
         * Makes new AppMenu.
         *
         * @param menu menu to be turned into an AppMenu.
         */
GraniteWidgetsAppMenu* granite_widgets_app_menu_construct (GType object_type, GtkMenu* menu) {
	GraniteWidgetsAppMenu * self = NULL;
	GtkImage* _tmp0_;
	GtkImage* _tmp1_;
	GtkMenu* _tmp2_;
	g_return_val_if_fail (menu != NULL, NULL);
	_tmp0_ = (GtkImage*) gtk_image_new_from_icon_name ("application-menu", GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp0_);
	_tmp1_ = _tmp0_;
	_tmp2_ = menu;
	self = (GraniteWidgetsAppMenu*) granite_widgets_tool_button_with_menu_construct (object_type, _tmp1_, _ ("Menu"), _tmp2_);
	_g_object_unref0 (_tmp1_);
	return self;
}


GraniteWidgetsAppMenu* granite_widgets_app_menu_new (GtkMenu* menu) {
	return granite_widgets_app_menu_construct (GRANITE_WIDGETS_TYPE_APP_MENU, menu);
}


/**
         * Makes new AppMenu with built-in about page.
         *
         * @param application application of AppMenu.
         * @param menu menu to be created.
         */
static void __lambda22_ (GraniteWidgetsAppMenu* self) {
	GtkWidget* _tmp0_;
	_tmp0_ = gtk_widget_get_toplevel ((GtkWidget*) self);
	g_signal_emit (self, granite_widgets_app_menu_signals[GRANITE_WIDGETS_APP_MENU_SHOW_ABOUT_SIGNAL], 0, _tmp0_);
}


static void ___lambda22__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda22_ ((GraniteWidgetsAppMenu*) self);
}


GraniteWidgetsAppMenu* granite_widgets_app_menu_construct_with_app (GType object_type, GraniteApplication* application, GtkMenu* menu) {
	GraniteWidgetsAppMenu * self = NULL;
	GtkImage* _tmp0_;
	GtkImage* _tmp1_;
	GtkMenu* _tmp2_;
	GtkMenu* _tmp3_;
	GtkMenuItem* _tmp4_;
	g_return_val_if_fail (menu != NULL, NULL);
	_tmp0_ = (GtkImage*) gtk_image_new_from_icon_name ("application-menu", GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp0_);
	_tmp1_ = _tmp0_;
	_tmp2_ = menu;
	self = (GraniteWidgetsAppMenu*) granite_widgets_tool_button_with_menu_construct (object_type, _tmp1_, _ ("Menu"), _tmp2_);
	_g_object_unref0 (_tmp1_);
	_tmp3_ = menu;
	granite_widgets_app_menu_add_items (self, _tmp3_);
	_tmp4_ = self->about_item;
	g_signal_connect_object (_tmp4_, "activate", (GCallback) ___lambda22__gtk_menu_item_activate, self, 0);
	return self;
}


GraniteWidgetsAppMenu* granite_widgets_app_menu_new_with_app (GraniteApplication* application, GtkMenu* menu) {
	return granite_widgets_app_menu_construct_with_app (GRANITE_WIDGETS_TYPE_APP_MENU, application, menu);
}


/**
         * Create a new AppMenu, parameters are unused now.
         */
GraniteWidgetsAppMenu* granite_widgets_app_menu_construct_with_urls (GType object_type, GtkMenu* menu, const gchar* help_url, const gchar* translate_url, const gchar* bug_url) {
	GraniteWidgetsAppMenu * self = NULL;
	GtkImage* _tmp0_;
	GtkImage* _tmp1_;
	GtkMenu* _tmp2_;
	g_return_val_if_fail (menu != NULL, NULL);
	g_return_val_if_fail (help_url != NULL, NULL);
	g_return_val_if_fail (translate_url != NULL, NULL);
	g_return_val_if_fail (bug_url != NULL, NULL);
	g_critical ("AppMenu.vala:71: This is a deprecated creation method: AppMenu.with_ur" \
"ls");
	_tmp0_ = (GtkImage*) gtk_image_new_from_icon_name ("application-menu", GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp0_);
	_tmp1_ = _tmp0_;
	_tmp2_ = menu;
	self = (GraniteWidgetsAppMenu*) granite_widgets_tool_button_with_menu_construct (object_type, _tmp1_, _ ("Menu"), _tmp2_);
	_g_object_unref0 (_tmp1_);
	return self;
}


GraniteWidgetsAppMenu* granite_widgets_app_menu_new_with_urls (GtkMenu* menu, const gchar* help_url, const gchar* translate_url, const gchar* bug_url) {
	return granite_widgets_app_menu_construct_with_urls (GRANITE_WIDGETS_TYPE_APP_MENU, menu, help_url, translate_url, bug_url);
}


/**
         * This method adds makes a properly formatted App Menu menu from given menu
         * 
         * @param menu menu to format
         */
void granite_widgets_app_menu_add_items (GraniteWidgetsAppMenu* self, GtkMenu* menu) {
	GtkMenuItem* _tmp0_;
	GtkMenu* _tmp1_;
	GList* _tmp2_;
	GList* _tmp3_;
	guint _tmp4_;
	gboolean _tmp5_;
	GtkMenu* _tmp9_;
	GtkMenuItem* _tmp10_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (menu != NULL);
	_tmp0_ = (GtkMenuItem*) gtk_menu_item_new_with_label (_ ("About"));
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->about_item);
	self->about_item = _tmp0_;
	_tmp1_ = menu;
	_tmp2_ = gtk_container_get_children ((GtkContainer*) _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_list_length (_tmp3_);
	_tmp5_ = _tmp4_ > ((guint) 0);
	_g_list_free0 (_tmp3_);
	if (_tmp5_) {
		GtkMenu* _tmp6_;
		GtkSeparatorMenuItem* _tmp7_;
		GtkSeparatorMenuItem* _tmp8_;
		_tmp6_ = menu;
		_tmp7_ = (GtkSeparatorMenuItem*) gtk_separator_menu_item_new ();
		g_object_ref_sink (_tmp7_);
		_tmp8_ = _tmp7_;
		gtk_menu_shell_append ((GtkMenuShell*) _tmp6_, (GtkWidget*) ((GtkMenuItem*) _tmp8_));
		_g_object_unref0 (_tmp8_);
	}
	_tmp9_ = menu;
	_tmp10_ = self->about_item;
	gtk_menu_shell_append ((GtkMenuShell*) _tmp9_, (GtkWidget*) _tmp10_);
}


static void granite_widgets_app_menu_class_init (GraniteWidgetsAppMenuClass * klass) {
	granite_widgets_app_menu_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = granite_widgets_app_menu_finalize;
	/**
	         * Called when showing about.
	         */
	granite_widgets_app_menu_signals[GRANITE_WIDGETS_APP_MENU_SHOW_ABOUT_SIGNAL] = g_signal_new ("show-about", GRANITE_WIDGETS_TYPE_APP_MENU, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, gtk_widget_get_type ());
}


static void granite_widgets_app_menu_instance_init (GraniteWidgetsAppMenu * self) {
}


static void granite_widgets_app_menu_finalize (GObject * obj) {
	GraniteWidgetsAppMenu * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRANITE_WIDGETS_TYPE_APP_MENU, GraniteWidgetsAppMenu);
	_g_object_unref0 (self->about_item);
	G_OBJECT_CLASS (granite_widgets_app_menu_parent_class)->finalize (obj);
}


/**
 * An App Menu is the gear menu that goes on the right of the toolbar.
 */
GType granite_widgets_app_menu_get_type (void) {
	static volatile gsize granite_widgets_app_menu_type_id__volatile = 0;
	if (g_once_init_enter (&granite_widgets_app_menu_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraniteWidgetsAppMenuClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) granite_widgets_app_menu_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraniteWidgetsAppMenu), 0, (GInstanceInitFunc) granite_widgets_app_menu_instance_init, NULL };
		GType granite_widgets_app_menu_type_id;
		granite_widgets_app_menu_type_id = g_type_register_static (GRANITE_WIDGETS_TYPE_TOOL_BUTTON_WITH_MENU, "GraniteWidgetsAppMenu", &g_define_type_info, 0);
		g_once_init_leave (&granite_widgets_app_menu_type_id__volatile, granite_widgets_app_menu_type_id);
	}
	return granite_widgets_app_menu_type_id__volatile;
}



