/* CellRendererBadge.c generated by valac 0.36.7, the Vala compiler
 * generated from CellRendererBadge.vala, do not modify */

/***
    Copyright (C) 2012-2013 Victor Eduardo <victoreduardm@gmal.com>

    This program or library is free software; you can redistribute it
    and/or modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 3 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
    Lesser General Public License for more details.
 
    You should have received a copy of the GNU Lesser General
    Public License along with this library; if not, write to the
    Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301 USA.
***/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <pango/pango.h>
#include <cairo.h>
#include <gdk/gdk.h>
#include <float.h>
#include <math.h>


#define GRANITE_WIDGETS_TYPE_CELL_RENDERER_BADGE (granite_widgets_cell_renderer_badge_get_type ())
#define GRANITE_WIDGETS_CELL_RENDERER_BADGE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_WIDGETS_TYPE_CELL_RENDERER_BADGE, GraniteWidgetsCellRendererBadge))
#define GRANITE_WIDGETS_CELL_RENDERER_BADGE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_WIDGETS_TYPE_CELL_RENDERER_BADGE, GraniteWidgetsCellRendererBadgeClass))
#define GRANITE_WIDGETS_IS_CELL_RENDERER_BADGE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_WIDGETS_TYPE_CELL_RENDERER_BADGE))
#define GRANITE_WIDGETS_IS_CELL_RENDERER_BADGE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_WIDGETS_TYPE_CELL_RENDERER_BADGE))
#define GRANITE_WIDGETS_CELL_RENDERER_BADGE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_WIDGETS_TYPE_CELL_RENDERER_BADGE, GraniteWidgetsCellRendererBadgeClass))

typedef struct _GraniteWidgetsCellRendererBadge GraniteWidgetsCellRendererBadge;
typedef struct _GraniteWidgetsCellRendererBadgeClass GraniteWidgetsCellRendererBadgeClass;
typedef struct _GraniteWidgetsCellRendererBadgePrivate GraniteWidgetsCellRendererBadgePrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _GraniteWidgetsCellRendererBadge {
	GtkCellRenderer parent_instance;
	GraniteWidgetsCellRendererBadgePrivate * priv;
};

struct _GraniteWidgetsCellRendererBadgeClass {
	GtkCellRendererClass parent_class;
};

struct _GraniteWidgetsCellRendererBadgePrivate {
	gchar* _text;
	PangoRectangle text_logical_rect;
	PangoLayout* text_layout;
	GtkBorder margin;
	GtkBorder padding;
	GtkBorder border;
};


static gpointer granite_widgets_cell_renderer_badge_parent_class = NULL;

GType granite_widgets_cell_renderer_badge_get_type (void) G_GNUC_CONST;
#define GRANITE_WIDGETS_CELL_RENDERER_BADGE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GRANITE_WIDGETS_TYPE_CELL_RENDERER_BADGE, GraniteWidgetsCellRendererBadgePrivate))
enum  {
	GRANITE_WIDGETS_CELL_RENDERER_BADGE_0_PROPERTY,
	GRANITE_WIDGETS_CELL_RENDERER_BADGE_TEXT_PROPERTY
};
GraniteWidgetsCellRendererBadge* granite_widgets_cell_renderer_badge_new (void);
GraniteWidgetsCellRendererBadge* granite_widgets_cell_renderer_badge_construct (GType object_type);
static GtkSizeRequestMode granite_widgets_cell_renderer_badge_real_get_request_mode (GtkCellRenderer* base);
static void granite_widgets_cell_renderer_badge_real_get_preferred_width (GtkCellRenderer* base, GtkWidget* widget, gint* minimum_size, gint* natural_size);
static void granite_widgets_cell_renderer_badge_update_layout_properties (GraniteWidgetsCellRendererBadge* self, GtkWidget* widget);
static void granite_widgets_cell_renderer_badge_real_get_preferred_height_for_width (GtkCellRenderer* base, GtkWidget* widget, gint width, gint* minimum_height, gint* natural_height);
#define GRANITE_STYLE_CLASS_BADGE "badge"
const gchar* granite_widgets_cell_renderer_badge_get_text (GraniteWidgetsCellRendererBadge* self);
static void granite_widgets_cell_renderer_badge_real_render (GtkCellRenderer* base, cairo_t* context, GtkWidget* widget, GdkRectangle* bg_area, GdkRectangle* cell_area, GtkCellRendererState flags);
static void granite_widgets_cell_renderer_badge_real_get_size (GtkCellRenderer* base, GtkWidget* widget, GdkRectangle* cell_area, gint* x_offset, gint* y_offset, gint* width, gint* height) G_GNUC_DEPRECATED;
void granite_widgets_cell_renderer_badge_set_text (GraniteWidgetsCellRendererBadge* self, const gchar* value);
static void granite_widgets_cell_renderer_badge_finalize (GObject * obj);
static void _vala_granite_widgets_cell_renderer_badge_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_granite_widgets_cell_renderer_badge_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


GraniteWidgetsCellRendererBadge* granite_widgets_cell_renderer_badge_construct (GType object_type) {
	GraniteWidgetsCellRendererBadge * self = NULL;
	self = (GraniteWidgetsCellRendererBadge*) g_object_new (object_type, NULL);
	return self;
}


GraniteWidgetsCellRendererBadge* granite_widgets_cell_renderer_badge_new (void) {
	return granite_widgets_cell_renderer_badge_construct (GRANITE_WIDGETS_TYPE_CELL_RENDERER_BADGE);
}


static GtkSizeRequestMode granite_widgets_cell_renderer_badge_real_get_request_mode (GtkCellRenderer* base) {
	GraniteWidgetsCellRendererBadge * self;
	GtkSizeRequestMode result = 0;
	self = (GraniteWidgetsCellRendererBadge*) base;
	result = GTK_SIZE_REQUEST_HEIGHT_FOR_WIDTH;
	return result;
}


static void granite_widgets_cell_renderer_badge_real_get_preferred_width (GtkCellRenderer* base, GtkWidget* widget, gint* minimum_size, gint* natural_size) {
	GraniteWidgetsCellRendererBadge * self;
	gint _vala_minimum_size = 0;
	gint _vala_natural_size = 0;
	GtkWidget* _tmp0_;
	gint width = 0;
	PangoRectangle _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	GtkBorder _tmp4_;
	gint16 _tmp5_;
	GtkBorder _tmp6_;
	gint16 _tmp7_;
	gint _tmp8_;
	GtkBorder _tmp9_;
	gint16 _tmp10_;
	GtkBorder _tmp11_;
	gint16 _tmp12_;
	gint _tmp13_;
	GtkBorder _tmp14_;
	gint16 _tmp15_;
	GtkBorder _tmp16_;
	gint16 _tmp17_;
	gint _tmp18_;
	guint _tmp19_;
	guint _tmp20_;
	self = (GraniteWidgetsCellRendererBadge*) base;
	g_return_if_fail (widget != NULL);
	_tmp0_ = widget;
	granite_widgets_cell_renderer_badge_update_layout_properties (self, _tmp0_);
	_tmp1_ = self->priv->text_logical_rect;
	_tmp2_ = _tmp1_.width;
	width = _tmp2_;
	_tmp3_ = width;
	_tmp4_ = self->priv->margin;
	_tmp5_ = _tmp4_.left;
	_tmp6_ = self->priv->margin;
	_tmp7_ = _tmp6_.right;
	width = _tmp3_ + (_tmp5_ + _tmp7_);
	_tmp8_ = width;
	_tmp9_ = self->priv->padding;
	_tmp10_ = _tmp9_.left;
	_tmp11_ = self->priv->padding;
	_tmp12_ = _tmp11_.right;
	width = _tmp8_ + (_tmp10_ + _tmp12_);
	_tmp13_ = width;
	_tmp14_ = self->priv->border;
	_tmp15_ = _tmp14_.left;
	_tmp16_ = self->priv->border;
	_tmp17_ = _tmp16_.right;
	width = _tmp13_ + (_tmp15_ + _tmp17_);
	_tmp18_ = width;
	g_object_get ((GtkCellRenderer*) self, "xpad", &_tmp19_, NULL);
	_tmp20_ = _tmp19_;
	_vala_natural_size = _tmp18_ + (2 * ((gint) _tmp20_));
	_vala_minimum_size = _vala_natural_size;
	if (minimum_size) {
		*minimum_size = _vala_minimum_size;
	}
	if (natural_size) {
		*natural_size = _vala_natural_size;
	}
}


static void granite_widgets_cell_renderer_badge_real_get_preferred_height_for_width (GtkCellRenderer* base, GtkWidget* widget, gint width, gint* minimum_height, gint* natural_height) {
	GraniteWidgetsCellRendererBadge * self;
	gint _vala_minimum_height = 0;
	gint _vala_natural_height = 0;
	GtkWidget* _tmp0_;
	gint height = 0;
	PangoRectangle _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	GtkBorder _tmp4_;
	gint16 _tmp5_;
	GtkBorder _tmp6_;
	gint16 _tmp7_;
	gint _tmp8_;
	GtkBorder _tmp9_;
	gint16 _tmp10_;
	GtkBorder _tmp11_;
	gint16 _tmp12_;
	gint _tmp13_;
	GtkBorder _tmp14_;
	gint16 _tmp15_;
	GtkBorder _tmp16_;
	gint16 _tmp17_;
	gint _tmp18_;
	guint _tmp19_;
	guint _tmp20_;
	self = (GraniteWidgetsCellRendererBadge*) base;
	g_return_if_fail (widget != NULL);
	_tmp0_ = widget;
	granite_widgets_cell_renderer_badge_update_layout_properties (self, _tmp0_);
	_tmp1_ = self->priv->text_logical_rect;
	_tmp2_ = _tmp1_.height;
	height = _tmp2_;
	_tmp3_ = height;
	_tmp4_ = self->priv->margin;
	_tmp5_ = _tmp4_.top;
	_tmp6_ = self->priv->margin;
	_tmp7_ = _tmp6_.bottom;
	height = _tmp3_ + (_tmp5_ + _tmp7_);
	_tmp8_ = height;
	_tmp9_ = self->priv->padding;
	_tmp10_ = _tmp9_.top;
	_tmp11_ = self->priv->padding;
	_tmp12_ = _tmp11_.bottom;
	height = _tmp8_ + (_tmp10_ + _tmp12_);
	_tmp13_ = height;
	_tmp14_ = self->priv->border;
	_tmp15_ = _tmp14_.top;
	_tmp16_ = self->priv->border;
	_tmp17_ = _tmp16_.bottom;
	height = _tmp13_ + (_tmp15_ + _tmp17_);
	_tmp18_ = height;
	g_object_get ((GtkCellRenderer*) self, "ypad", &_tmp19_, NULL);
	_tmp20_ = _tmp19_;
	_vala_natural_height = _tmp18_ + (2 * ((gint) _tmp20_));
	_vala_minimum_height = _vala_natural_height;
	if (minimum_height) {
		*minimum_height = _vala_minimum_height;
	}
	if (natural_height) {
		*natural_height = _vala_natural_height;
	}
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void granite_widgets_cell_renderer_badge_update_layout_properties (GraniteWidgetsCellRendererBadge* self, GtkWidget* widget) {
	GtkStyleContext* ctx = NULL;
	GtkWidget* _tmp0_;
	GtkStyleContext* _tmp1_;
	GtkStyleContext* _tmp2_;
	GtkStateFlags state = 0;
	GtkStateFlags _tmp3_;
	GtkBorder _tmp4_ = {0};
	GtkBorder _tmp5_ = {0};
	GtkBorder _tmp6_ = {0};
	GtkWidget* _tmp7_;
	const gchar* _tmp8_;
	PangoLayout* _tmp9_;
	PangoLayout* _tmp10_;
	PangoFontDescription* _tmp11_;
	PangoRectangle ink_rect = {0};
	PangoLayout* _tmp12_;
	PangoRectangle _tmp13_ = {0};
	PangoRectangle _tmp14_ = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (widget != NULL);
	_tmp0_ = widget;
	_tmp1_ = gtk_widget_get_style_context (_tmp0_);
	_tmp2_ = _g_object_ref0 (_tmp1_);
	ctx = _tmp2_;
	gtk_style_context_save (ctx);
	gtk_style_context_add_class (ctx, GRANITE_STYLE_CLASS_BADGE);
	_tmp3_ = gtk_style_context_get_state (ctx);
	state = _tmp3_;
	gtk_style_context_get_margin (ctx, state, &_tmp4_);
	self->priv->margin = _tmp4_;
	gtk_style_context_get_padding (ctx, state, &_tmp5_);
	self->priv->padding = _tmp5_;
	gtk_style_context_get_border (ctx, state, &_tmp6_);
	self->priv->border = _tmp6_;
	_tmp7_ = widget;
	_tmp8_ = self->priv->_text;
	_tmp9_ = gtk_widget_create_pango_layout (_tmp7_, _tmp8_);
	_g_object_unref0 (self->priv->text_layout);
	self->priv->text_layout = _tmp9_;
	_tmp10_ = self->priv->text_layout;
	_tmp11_ = gtk_style_context_get_font (ctx, state);
	pango_layout_set_font_description (_tmp10_, _tmp11_);
	gtk_style_context_restore (ctx);
	_tmp12_ = self->priv->text_layout;
	pango_layout_get_pixel_extents (_tmp12_, &_tmp13_, &_tmp14_);
	ink_rect = _tmp13_;
	self->priv->text_logical_rect = _tmp14_;
	_g_object_unref0 (ctx);
}


static void granite_widgets_cell_renderer_badge_real_render (GtkCellRenderer* base, cairo_t* context, GtkWidget* widget, GdkRectangle* bg_area, GdkRectangle* cell_area, GtkCellRendererState flags) {
	GraniteWidgetsCellRendererBadge * self;
	GtkWidget* _tmp0_;
	GdkRectangle aligned_area = {0};
	GtkWidget* _tmp1_;
	GtkCellRendererState _tmp2_;
	GdkRectangle _tmp3_;
	GdkRectangle _tmp4_ = {0};
	gint x = 0;
	GdkRectangle _tmp5_;
	gint _tmp6_;
	gint y = 0;
	GdkRectangle _tmp7_;
	gint _tmp8_;
	gint width = 0;
	GdkRectangle _tmp9_;
	gint _tmp10_;
	gint height = 0;
	GdkRectangle _tmp11_;
	gint _tmp12_;
	gint _tmp13_;
	GtkBorder _tmp14_;
	gint16 _tmp15_;
	gint _tmp16_;
	GtkBorder _tmp17_;
	gint16 _tmp18_;
	gint _tmp19_;
	GtkBorder _tmp20_;
	gint16 _tmp21_;
	GtkBorder _tmp22_;
	gint16 _tmp23_;
	gint _tmp24_;
	GtkBorder _tmp25_;
	gint16 _tmp26_;
	GtkBorder _tmp27_;
	gint16 _tmp28_;
	GtkStyleContext* ctx = NULL;
	GtkWidget* _tmp29_;
	GtkStyleContext* _tmp30_;
	GtkStyleContext* _tmp31_;
	cairo_t* _tmp32_;
	gint _tmp33_;
	gint _tmp34_;
	gint _tmp35_;
	gint _tmp36_;
	cairo_t* _tmp37_;
	gint _tmp38_;
	gint _tmp39_;
	gint _tmp40_;
	gint _tmp41_;
	gint _tmp42_;
	GtkBorder _tmp43_;
	gint16 _tmp44_;
	GtkBorder _tmp45_;
	gint16 _tmp46_;
	gint _tmp47_;
	GtkBorder _tmp48_;
	gint16 _tmp49_;
	GtkBorder _tmp50_;
	gint16 _tmp51_;
	gint _tmp52_;
	GtkBorder _tmp53_;
	gint16 _tmp54_;
	GtkBorder _tmp55_;
	gint16 _tmp56_;
	GtkBorder _tmp57_;
	gint16 _tmp58_;
	GtkBorder _tmp59_;
	gint16 _tmp60_;
	gint _tmp61_;
	GtkBorder _tmp62_;
	gint16 _tmp63_;
	GtkBorder _tmp64_;
	gint16 _tmp65_;
	GtkBorder _tmp66_;
	gint16 _tmp67_;
	GtkBorder _tmp68_;
	gint16 _tmp69_;
	gint _tmp70_;
	PangoRectangle _tmp71_;
	gint _tmp72_;
	gint _tmp73_;
	PangoRectangle _tmp74_;
	gint _tmp75_;
	gint _tmp76_;
	PangoRectangle _tmp77_;
	gint _tmp78_;
	gint _tmp79_;
	PangoRectangle _tmp80_;
	gint _tmp81_;
	cairo_t* _tmp82_;
	gint _tmp83_;
	gint _tmp84_;
	PangoLayout* _tmp85_;
	self = (GraniteWidgetsCellRendererBadge*) base;
	g_return_if_fail (context != NULL);
	g_return_if_fail (widget != NULL);
	g_return_if_fail (bg_area != NULL);
	g_return_if_fail (cell_area != NULL);
	_tmp0_ = widget;
	granite_widgets_cell_renderer_badge_update_layout_properties (self, _tmp0_);
	_tmp1_ = widget;
	_tmp2_ = flags;
	_tmp3_ = *cell_area;
	gtk_cell_renderer_get_aligned_area ((GtkCellRenderer*) self, _tmp1_, _tmp2_, &_tmp3_, &_tmp4_);
	aligned_area = _tmp4_;
	_tmp5_ = aligned_area;
	_tmp6_ = _tmp5_.x;
	x = _tmp6_;
	_tmp7_ = aligned_area;
	_tmp8_ = _tmp7_.y;
	y = _tmp8_;
	_tmp9_ = aligned_area;
	_tmp10_ = _tmp9_.width;
	width = _tmp10_;
	_tmp11_ = aligned_area;
	_tmp12_ = _tmp11_.height;
	height = _tmp12_;
	_tmp13_ = x;
	_tmp14_ = self->priv->margin;
	_tmp15_ = _tmp14_.right;
	x = _tmp13_ + _tmp15_;
	_tmp16_ = y;
	_tmp17_ = self->priv->margin;
	_tmp18_ = _tmp17_.top;
	y = _tmp16_ + _tmp18_;
	_tmp19_ = width;
	_tmp20_ = self->priv->margin;
	_tmp21_ = _tmp20_.left;
	_tmp22_ = self->priv->margin;
	_tmp23_ = _tmp22_.right;
	width = _tmp19_ - (_tmp21_ + _tmp23_);
	_tmp24_ = height;
	_tmp25_ = self->priv->margin;
	_tmp26_ = _tmp25_.top;
	_tmp27_ = self->priv->margin;
	_tmp28_ = _tmp27_.bottom;
	height = _tmp24_ - (_tmp26_ + _tmp28_);
	_tmp29_ = widget;
	_tmp30_ = gtk_widget_get_style_context (_tmp29_);
	_tmp31_ = _g_object_ref0 (_tmp30_);
	ctx = _tmp31_;
	gtk_style_context_add_class (ctx, GRANITE_STYLE_CLASS_BADGE);
	_tmp32_ = context;
	_tmp33_ = x;
	_tmp34_ = y;
	_tmp35_ = width;
	_tmp36_ = height;
	gtk_render_background (ctx, _tmp32_, (gdouble) _tmp33_, (gdouble) _tmp34_, (gdouble) _tmp35_, (gdouble) _tmp36_);
	_tmp37_ = context;
	_tmp38_ = x;
	_tmp39_ = y;
	_tmp40_ = width;
	_tmp41_ = height;
	gtk_render_frame (ctx, _tmp37_, (gdouble) _tmp38_, (gdouble) _tmp39_, (gdouble) _tmp40_, (gdouble) _tmp41_);
	_tmp42_ = x;
	_tmp43_ = self->priv->border;
	_tmp44_ = _tmp43_.right;
	_tmp45_ = self->priv->padding;
	_tmp46_ = _tmp45_.right;
	x = _tmp42_ + (_tmp44_ + _tmp46_);
	_tmp47_ = y;
	_tmp48_ = self->priv->border;
	_tmp49_ = _tmp48_.top;
	_tmp50_ = self->priv->padding;
	_tmp51_ = _tmp50_.top;
	y = _tmp47_ + (_tmp49_ + _tmp51_);
	_tmp52_ = width;
	_tmp53_ = self->priv->border;
	_tmp54_ = _tmp53_.left;
	_tmp55_ = self->priv->border;
	_tmp56_ = _tmp55_.right;
	_tmp57_ = self->priv->padding;
	_tmp58_ = _tmp57_.left;
	_tmp59_ = self->priv->padding;
	_tmp60_ = _tmp59_.right;
	width = _tmp52_ - (((_tmp54_ + _tmp56_) + _tmp58_) + _tmp60_);
	_tmp61_ = height;
	_tmp62_ = self->priv->border;
	_tmp63_ = _tmp62_.top;
	_tmp64_ = self->priv->border;
	_tmp65_ = _tmp64_.bottom;
	_tmp66_ = self->priv->padding;
	_tmp67_ = _tmp66_.top;
	_tmp68_ = self->priv->padding;
	_tmp69_ = _tmp68_.bottom;
	height = _tmp61_ - (((_tmp63_ + _tmp65_) + _tmp67_) + _tmp69_);
	_tmp70_ = x;
	_tmp71_ = self->priv->text_logical_rect;
	_tmp72_ = _tmp71_.x;
	_tmp73_ = width;
	_tmp74_ = self->priv->text_logical_rect;
	_tmp75_ = _tmp74_.width;
	x = _tmp70_ + (_tmp72_ + ((_tmp73_ - _tmp75_) / 2));
	_tmp76_ = y;
	_tmp77_ = self->priv->text_logical_rect;
	_tmp78_ = _tmp77_.y;
	_tmp79_ = height;
	_tmp80_ = self->priv->text_logical_rect;
	_tmp81_ = _tmp80_.height;
	y = _tmp76_ + (_tmp78_ + ((_tmp79_ - _tmp81_) / 2));
	_tmp82_ = context;
	_tmp83_ = x;
	_tmp84_ = y;
	_tmp85_ = self->priv->text_layout;
	gtk_render_layout (ctx, _tmp82_, (gdouble) _tmp83_, (gdouble) _tmp84_, _tmp85_);
	_g_object_unref0 (ctx);
}


static void granite_widgets_cell_renderer_badge_real_get_size (GtkCellRenderer* base, GtkWidget* widget, GdkRectangle* cell_area, gint* x_offset, gint* y_offset, gint* width, gint* height) {
	GraniteWidgetsCellRendererBadge * self;
	gint _vala_x_offset = 0;
	gint _vala_y_offset = 0;
	gint _vala_width = 0;
	gint _vala_height = 0;
	self = (GraniteWidgetsCellRendererBadge*) base;
	g_return_if_fail (widget != NULL);
	g_assert_not_reached ();
	if (x_offset) {
		*x_offset = _vala_x_offset;
	}
	if (y_offset) {
		*y_offset = _vala_y_offset;
	}
	if (width) {
		*width = _vala_width;
	}
	if (height) {
		*height = _vala_height;
	}
}


const gchar* granite_widgets_cell_renderer_badge_get_text (GraniteWidgetsCellRendererBadge* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_text;
	result = _tmp0_;
	return result;
}


void granite_widgets_cell_renderer_badge_set_text (GraniteWidgetsCellRendererBadge* self, const gchar* value) {
	g_return_if_fail (self != NULL);
	if (g_strcmp0 (value, granite_widgets_cell_renderer_badge_get_text (self)) != 0) {
		const gchar* _tmp0_;
		gchar* _tmp1_;
		_tmp0_ = value;
		_tmp1_ = g_strdup (_tmp0_);
		_g_free0 (self->priv->_text);
		self->priv->_text = _tmp1_;
		g_object_notify ((GObject *) self, "text");
	}
}


static void granite_widgets_cell_renderer_badge_class_init (GraniteWidgetsCellRendererBadgeClass * klass) {
	granite_widgets_cell_renderer_badge_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GraniteWidgetsCellRendererBadgePrivate));
	((GtkCellRendererClass *) klass)->get_request_mode = (GtkSizeRequestMode (*) (GtkCellRenderer *)) granite_widgets_cell_renderer_badge_real_get_request_mode;
	((GtkCellRendererClass *) klass)->get_preferred_width = (void (*) (GtkCellRenderer *, GtkWidget*, gint*, gint*)) granite_widgets_cell_renderer_badge_real_get_preferred_width;
	((GtkCellRendererClass *) klass)->get_preferred_height_for_width = (void (*) (GtkCellRenderer *, GtkWidget*, gint, gint*, gint*)) granite_widgets_cell_renderer_badge_real_get_preferred_height_for_width;
	((GtkCellRendererClass *) klass)->render = (void (*) (GtkCellRenderer *, cairo_t*, GtkWidget*, GdkRectangle*, GdkRectangle*, GtkCellRendererState)) granite_widgets_cell_renderer_badge_real_render;
	((GtkCellRendererClass *) klass)->get_size = (void (*) (GtkCellRenderer *, GtkWidget*, GdkRectangle*, gint*, gint*, gint*, gint*)) granite_widgets_cell_renderer_badge_real_get_size;
	G_OBJECT_CLASS (klass)->get_property = _vala_granite_widgets_cell_renderer_badge_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_granite_widgets_cell_renderer_badge_set_property;
	G_OBJECT_CLASS (klass)->finalize = granite_widgets_cell_renderer_badge_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_WIDGETS_CELL_RENDERER_BADGE_TEXT_PROPERTY, g_param_spec_string ("text", "text", "text", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void granite_widgets_cell_renderer_badge_instance_init (GraniteWidgetsCellRendererBadge * self) {
	gchar* _tmp0_;
	self->priv = GRANITE_WIDGETS_CELL_RENDERER_BADGE_GET_PRIVATE (self);
	_tmp0_ = g_strdup ("");
	self->priv->_text = _tmp0_;
}


static void granite_widgets_cell_renderer_badge_finalize (GObject * obj) {
	GraniteWidgetsCellRendererBadge * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRANITE_WIDGETS_TYPE_CELL_RENDERER_BADGE, GraniteWidgetsCellRendererBadge);
	_g_free0 (self->priv->_text);
	_g_object_unref0 (self->priv->text_layout);
	G_OBJECT_CLASS (granite_widgets_cell_renderer_badge_parent_class)->finalize (obj);
}


/**
 * A badge renderer.
 *
 * Informs the user quickly on the content of the corresponding view. For example
 * it might be used to show how much songs are in a playlist or how much updates
 * are available.
 *
 * {{../../doc/images/cellrendererbadge.png}}
 *
 * @since 0.2
 */
GType granite_widgets_cell_renderer_badge_get_type (void) {
	static volatile gsize granite_widgets_cell_renderer_badge_type_id__volatile = 0;
	if (g_once_init_enter (&granite_widgets_cell_renderer_badge_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraniteWidgetsCellRendererBadgeClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) granite_widgets_cell_renderer_badge_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraniteWidgetsCellRendererBadge), 0, (GInstanceInitFunc) granite_widgets_cell_renderer_badge_instance_init, NULL };
		GType granite_widgets_cell_renderer_badge_type_id;
		granite_widgets_cell_renderer_badge_type_id = g_type_register_static (gtk_cell_renderer_get_type (), "GraniteWidgetsCellRendererBadge", &g_define_type_info, 0);
		g_once_init_leave (&granite_widgets_cell_renderer_badge_type_id__volatile, granite_widgets_cell_renderer_badge_type_id);
	}
	return granite_widgets_cell_renderer_badge_type_id__volatile;
}


static void _vala_granite_widgets_cell_renderer_badge_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GraniteWidgetsCellRendererBadge * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GRANITE_WIDGETS_TYPE_CELL_RENDERER_BADGE, GraniteWidgetsCellRendererBadge);
	switch (property_id) {
		case GRANITE_WIDGETS_CELL_RENDERER_BADGE_TEXT_PROPERTY:
		g_value_set_string (value, granite_widgets_cell_renderer_badge_get_text (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_granite_widgets_cell_renderer_badge_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GraniteWidgetsCellRendererBadge * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GRANITE_WIDGETS_TYPE_CELL_RENDERER_BADGE, GraniteWidgetsCellRendererBadge);
	switch (property_id) {
		case GRANITE_WIDGETS_CELL_RENDERER_BADGE_TEXT_PROPERTY:
		granite_widgets_cell_renderer_badge_set_text (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



