/* CollapsiblePaned.c generated by valac 0.36.7, the Vala compiler
 * generated from CollapsiblePaned.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>


#define GRANITE_TYPE_COLLAPSE_MODE (granite_collapse_mode_get_type ())

#define GRANITE_WIDGETS_TYPE_COLLAPSIBLE_PANED (granite_widgets_collapsible_paned_get_type ())
#define GRANITE_WIDGETS_COLLAPSIBLE_PANED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_WIDGETS_TYPE_COLLAPSIBLE_PANED, GraniteWidgetsCollapsiblePaned))
#define GRANITE_WIDGETS_COLLAPSIBLE_PANED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_WIDGETS_TYPE_COLLAPSIBLE_PANED, GraniteWidgetsCollapsiblePanedClass))
#define GRANITE_WIDGETS_IS_COLLAPSIBLE_PANED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_WIDGETS_TYPE_COLLAPSIBLE_PANED))
#define GRANITE_WIDGETS_IS_COLLAPSIBLE_PANED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_WIDGETS_TYPE_COLLAPSIBLE_PANED))
#define GRANITE_WIDGETS_COLLAPSIBLE_PANED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_WIDGETS_TYPE_COLLAPSIBLE_PANED, GraniteWidgetsCollapsiblePanedClass))

typedef struct _GraniteWidgetsCollapsiblePaned GraniteWidgetsCollapsiblePaned;
typedef struct _GraniteWidgetsCollapsiblePanedClass GraniteWidgetsCollapsiblePanedClass;
typedef struct _GraniteWidgetsCollapsiblePanedPrivate GraniteWidgetsCollapsiblePanedPrivate;

#define GRANITE_WIDGETS_TYPE_HCOLLAPSABLE_PANED (granite_widgets_hcollapsable_paned_get_type ())
#define GRANITE_WIDGETS_HCOLLAPSABLE_PANED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_WIDGETS_TYPE_HCOLLAPSABLE_PANED, GraniteWidgetsHCollapsablePaned))
#define GRANITE_WIDGETS_HCOLLAPSABLE_PANED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_WIDGETS_TYPE_HCOLLAPSABLE_PANED, GraniteWidgetsHCollapsablePanedClass))
#define GRANITE_WIDGETS_IS_HCOLLAPSABLE_PANED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_WIDGETS_TYPE_HCOLLAPSABLE_PANED))
#define GRANITE_WIDGETS_IS_HCOLLAPSABLE_PANED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_WIDGETS_TYPE_HCOLLAPSABLE_PANED))
#define GRANITE_WIDGETS_HCOLLAPSABLE_PANED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_WIDGETS_TYPE_HCOLLAPSABLE_PANED, GraniteWidgetsHCollapsablePanedClass))

typedef struct _GraniteWidgetsHCollapsablePaned GraniteWidgetsHCollapsablePaned;
typedef struct _GraniteWidgetsHCollapsablePanedClass GraniteWidgetsHCollapsablePanedClass;
typedef struct _GraniteWidgetsHCollapsablePanedPrivate GraniteWidgetsHCollapsablePanedPrivate;

#define GRANITE_WIDGETS_TYPE_VCOLLAPSABLE_PANED (granite_widgets_vcollapsable_paned_get_type ())
#define GRANITE_WIDGETS_VCOLLAPSABLE_PANED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_WIDGETS_TYPE_VCOLLAPSABLE_PANED, GraniteWidgetsVCollapsablePaned))
#define GRANITE_WIDGETS_VCOLLAPSABLE_PANED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_WIDGETS_TYPE_VCOLLAPSABLE_PANED, GraniteWidgetsVCollapsablePanedClass))
#define GRANITE_WIDGETS_IS_VCOLLAPSABLE_PANED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_WIDGETS_TYPE_VCOLLAPSABLE_PANED))
#define GRANITE_WIDGETS_IS_VCOLLAPSABLE_PANED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_WIDGETS_TYPE_VCOLLAPSABLE_PANED))
#define GRANITE_WIDGETS_VCOLLAPSABLE_PANED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_WIDGETS_TYPE_VCOLLAPSABLE_PANED, GraniteWidgetsVCollapsablePanedClass))

typedef struct _GraniteWidgetsVCollapsablePaned GraniteWidgetsVCollapsablePaned;
typedef struct _GraniteWidgetsVCollapsablePanedClass GraniteWidgetsVCollapsablePanedClass;
typedef struct _GraniteWidgetsVCollapsablePanedPrivate GraniteWidgetsVCollapsablePanedPrivate;

typedef enum  {
	GRANITE_COLLAPSE_MODE_NONE = 0,
	GRANITE_COLLAPSE_MODE_LEFT = 1,
	GRANITE_COLLAPSE_MODE_TOP = 1,
	GRANITE_COLLAPSE_MODE_FIRST = 1,
	GRANITE_COLLAPSE_MODE_RIGHT = 2,
	GRANITE_COLLAPSE_MODE_BOTTOM = 2,
	GRANITE_COLLAPSE_MODE_LAST = 2
} GraniteCollapseMode;

struct _GraniteWidgetsCollapsiblePaned {
	GtkPaned parent_instance;
	GraniteWidgetsCollapsiblePanedPrivate * priv;
};

struct _GraniteWidgetsCollapsiblePanedClass {
	GtkPanedClass parent_class;
};

struct _GraniteWidgetsCollapsiblePanedPrivate {
	GraniteCollapseMode _collapse_mode;
	gint saved_state;
	guint last_click_time;
};

struct _GraniteWidgetsHCollapsablePaned {
	GraniteWidgetsCollapsiblePaned parent_instance;
	GraniteWidgetsHCollapsablePanedPrivate * priv;
};

struct _GraniteWidgetsHCollapsablePanedClass {
	GraniteWidgetsCollapsiblePanedClass parent_class;
};

struct _GraniteWidgetsVCollapsablePaned {
	GraniteWidgetsCollapsiblePaned parent_instance;
	GraniteWidgetsVCollapsablePanedPrivate * priv;
};

struct _GraniteWidgetsVCollapsablePanedClass {
	GraniteWidgetsCollapsiblePanedClass parent_class;
};


static gpointer granite_widgets_collapsible_paned_parent_class = NULL;
static gpointer granite_widgets_hcollapsable_paned_parent_class = NULL;
static gpointer granite_widgets_vcollapsable_paned_parent_class = NULL;

GType granite_collapse_mode_get_type (void) G_GNUC_CONST;
GType granite_widgets_collapsible_paned_get_type (void) G_GNUC_CONST;
#define GRANITE_WIDGETS_COLLAPSIBLE_PANED_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GRANITE_WIDGETS_TYPE_COLLAPSIBLE_PANED, GraniteWidgetsCollapsiblePanedPrivate))
enum  {
	GRANITE_WIDGETS_COLLAPSIBLE_PANED_0_PROPERTY,
	GRANITE_WIDGETS_COLLAPSIBLE_PANED_COLLAPSE_MODE_PROPERTY
};
GraniteWidgetsCollapsiblePaned* granite_widgets_collapsible_paned_new (GtkOrientation orientation);
GraniteWidgetsCollapsiblePaned* granite_widgets_collapsible_paned_construct (GType object_type, GtkOrientation orientation);
static gboolean granite_widgets_collapsible_paned_detect_toggle (GraniteWidgetsCollapsiblePaned* self, GdkEventButton* event);
static gboolean _granite_widgets_collapsible_paned_detect_toggle_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
GraniteCollapseMode granite_widgets_collapsible_paned_get_collapse_mode (GraniteWidgetsCollapsiblePaned* self);
void granite_widgets_collapsible_paned_set_collapse_mode (GraniteWidgetsCollapsiblePaned* self, GraniteCollapseMode value);
static void granite_widgets_collapsible_paned_finalize (GObject * obj);
static void _vala_granite_widgets_collapsible_paned_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_granite_widgets_collapsible_paned_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
GType granite_widgets_hcollapsable_paned_get_type (void) G_GNUC_CONST;
enum  {
	GRANITE_WIDGETS_HCOLLAPSABLE_PANED_0_PROPERTY
};
GraniteWidgetsHCollapsablePaned* granite_widgets_hcollapsable_paned_new (void);
GraniteWidgetsHCollapsablePaned* granite_widgets_hcollapsable_paned_construct (GType object_type);
GType granite_widgets_vcollapsable_paned_get_type (void) G_GNUC_CONST;
enum  {
	GRANITE_WIDGETS_VCOLLAPSABLE_PANED_0_PROPERTY
};
GraniteWidgetsVCollapsablePaned* granite_widgets_vcollapsable_paned_new (void);
GraniteWidgetsVCollapsablePaned* granite_widgets_vcollapsable_paned_construct (GType object_type);


/***
    Copyright (C) 2011-2013 Mathijs Henquet

    This program or library is free software; you can redistribute it
    and/or modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 3 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
    Lesser General Public License for more details.
 
    You should have received a copy of the GNU Lesser General
    Public License along with this library; if not, write to the
    Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301 USA.
***/
GType granite_collapse_mode_get_type (void) {
	static volatile gsize granite_collapse_mode_type_id__volatile = 0;
	if (g_once_init_enter (&granite_collapse_mode_type_id__volatile)) {
		static const GEnumValue values[] = {{GRANITE_COLLAPSE_MODE_NONE, "GRANITE_COLLAPSE_MODE_NONE", "none"}, {GRANITE_COLLAPSE_MODE_LEFT, "GRANITE_COLLAPSE_MODE_LEFT", "left"}, {GRANITE_COLLAPSE_MODE_TOP, "GRANITE_COLLAPSE_MODE_TOP", "top"}, {GRANITE_COLLAPSE_MODE_FIRST, "GRANITE_COLLAPSE_MODE_FIRST", "first"}, {GRANITE_COLLAPSE_MODE_RIGHT, "GRANITE_COLLAPSE_MODE_RIGHT", "right"}, {GRANITE_COLLAPSE_MODE_BOTTOM, "GRANITE_COLLAPSE_MODE_BOTTOM", "bottom"}, {GRANITE_COLLAPSE_MODE_LAST, "GRANITE_COLLAPSE_MODE_LAST", "last"}, {0, NULL, NULL}};
		GType granite_collapse_mode_type_id;
		granite_collapse_mode_type_id = g_enum_register_static ("GraniteCollapseMode", values);
		g_once_init_leave (&granite_collapse_mode_type_id__volatile, granite_collapse_mode_type_id);
	}
	return granite_collapse_mode_type_id__volatile;
}


static gboolean _granite_widgets_collapsible_paned_detect_toggle_gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = granite_widgets_collapsible_paned_detect_toggle ((GraniteWidgetsCollapsiblePaned*) self, event);
	return result;
}


GraniteWidgetsCollapsiblePaned* granite_widgets_collapsible_paned_construct (GType object_type, GtkOrientation orientation) {
	GraniteWidgetsCollapsiblePaned * self = NULL;
	GtkOrientation _tmp0_;
	self = (GraniteWidgetsCollapsiblePaned*) g_object_new (object_type, NULL);
	_tmp0_ = orientation;
	gtk_orientable_set_orientation ((GtkOrientable*) self, _tmp0_);
	g_signal_connect_object ((GtkWidget*) self, "button-press-event", (GCallback) _granite_widgets_collapsible_paned_detect_toggle_gtk_widget_button_press_event, self, 0);
	return self;
}


GraniteWidgetsCollapsiblePaned* granite_widgets_collapsible_paned_new (GtkOrientation orientation) {
	return granite_widgets_collapsible_paned_construct (GRANITE_WIDGETS_TYPE_COLLAPSIBLE_PANED, orientation);
}


static gboolean granite_widgets_collapsible_paned_detect_toggle (GraniteWidgetsCollapsiblePaned* self, GdkEventButton* event) {
	gboolean result = FALSE;
	GraniteCollapseMode _tmp0_;
	gboolean _tmp1_ = FALSE;
	GdkEventButton* _tmp2_;
	guint32 _tmp3_;
	guint _tmp4_;
	GtkSettings* _tmp5_;
	gint _tmp6_;
	gint _tmp7_;
	gboolean _tmp10_ = FALSE;
	GdkEventButton* _tmp11_;
	GdkEventType _tmp12_;
	GdkEventButton* _tmp30_;
	guint32 _tmp31_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = self->priv->_collapse_mode;
	if (_tmp0_ == GRANITE_COLLAPSE_MODE_NONE) {
		result = FALSE;
		return result;
	}
	_tmp2_ = event;
	_tmp3_ = _tmp2_->time;
	_tmp4_ = self->priv->last_click_time;
	_tmp5_ = gtk_settings_get_default ();
	g_object_get (_tmp5_, "gtk-double-click-time", &_tmp6_, NULL);
	_tmp7_ = _tmp6_;
	if (_tmp3_ < ((guint32) (_tmp4_ + _tmp7_))) {
		GdkEventButton* _tmp8_;
		GdkEventType _tmp9_;
		_tmp8_ = event;
		_tmp9_ = _tmp8_->type;
		_tmp1_ = _tmp9_ != GDK_2BUTTON_PRESS;
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		result = TRUE;
		return result;
	}
	_tmp11_ = event;
	_tmp12_ = _tmp11_->type;
	if (_tmp12_ == GDK_2BUTTON_PRESS) {
		GdkEventButton* _tmp13_;
		GdkWindow* _tmp14_;
		GdkWindow* _tmp15_;
		_tmp13_ = event;
		_tmp14_ = _tmp13_->window;
		_tmp15_ = gtk_paned_get_handle_window ((GtkPaned*) self);
		_tmp10_ = _tmp14_ == _tmp15_;
	} else {
		_tmp10_ = FALSE;
	}
	if (_tmp10_) {
		gboolean _tmp16_ = FALSE;
		gint current_position = 0;
		gint _tmp17_;
		GraniteCollapseMode _tmp18_;
		gint requested_position = 0;
		gint _tmp22_;
		GraniteCollapseMode _tmp25_;
		gint _tmp29_;
		g_signal_emit_by_name ((GtkPaned*) self, "accept-position", &_tmp16_);
		_tmp17_ = gtk_paned_get_position ((GtkPaned*) self);
		current_position = _tmp17_;
		_tmp18_ = self->priv->_collapse_mode;
		if (_tmp18_ == GRANITE_COLLAPSE_MODE_LAST) {
			gint _tmp19_;
			gint _tmp20_;
			gint _tmp21_;
			g_object_get ((GtkPaned*) self, "max-position", &_tmp19_, NULL);
			_tmp20_ = _tmp19_;
			_tmp21_ = current_position;
			current_position = _tmp20_ - _tmp21_;
		}
		_tmp22_ = current_position;
		if (_tmp22_ == 0) {
			gint _tmp23_;
			g_debug ("CollapsiblePaned.vala:66: [CollapsablePaned] expand");
			_tmp23_ = self->priv->saved_state;
			requested_position = _tmp23_;
		} else {
			gint _tmp24_;
			_tmp24_ = current_position;
			self->priv->saved_state = _tmp24_;
			g_debug ("CollapsiblePaned.vala:71: [CollapsablePaned] shrink");
			requested_position = 0;
		}
		_tmp25_ = self->priv->_collapse_mode;
		if (_tmp25_ == GRANITE_COLLAPSE_MODE_LAST) {
			gint _tmp26_;
			gint _tmp27_;
			gint _tmp28_;
			g_object_get ((GtkPaned*) self, "max-position", &_tmp26_, NULL);
			_tmp27_ = _tmp26_;
			_tmp28_ = requested_position;
			requested_position = _tmp27_ - _tmp28_;
		}
		_tmp29_ = requested_position;
		gtk_paned_set_position ((GtkPaned*) self, _tmp29_);
		result = TRUE;
		return result;
	}
	_tmp30_ = event;
	_tmp31_ = _tmp30_->time;
	self->priv->last_click_time = (guint) _tmp31_;
	result = FALSE;
	return result;
}


GraniteCollapseMode granite_widgets_collapsible_paned_get_collapse_mode (GraniteWidgetsCollapsiblePaned* self) {
	GraniteCollapseMode result;
	GraniteCollapseMode _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_collapse_mode;
	result = _tmp0_;
	return result;
}


void granite_widgets_collapsible_paned_set_collapse_mode (GraniteWidgetsCollapsiblePaned* self, GraniteCollapseMode value) {
	g_return_if_fail (self != NULL);
	if (granite_widgets_collapsible_paned_get_collapse_mode (self) != value) {
		GraniteCollapseMode _tmp0_;
		_tmp0_ = value;
		self->priv->_collapse_mode = _tmp0_;
		g_object_notify ((GObject *) self, "collapse-mode");
	}
}


static void granite_widgets_collapsible_paned_class_init (GraniteWidgetsCollapsiblePanedClass * klass) {
	granite_widgets_collapsible_paned_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GraniteWidgetsCollapsiblePanedPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_granite_widgets_collapsible_paned_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_granite_widgets_collapsible_paned_set_property;
	G_OBJECT_CLASS (klass)->finalize = granite_widgets_collapsible_paned_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_WIDGETS_COLLAPSIBLE_PANED_COLLAPSE_MODE_PROPERTY, g_param_spec_enum ("collapse-mode", "collapse-mode", "collapse-mode", GRANITE_TYPE_COLLAPSE_MODE, GRANITE_COLLAPSE_MODE_NONE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void granite_widgets_collapsible_paned_instance_init (GraniteWidgetsCollapsiblePaned * self) {
	self->priv = GRANITE_WIDGETS_COLLAPSIBLE_PANED_GET_PRIVATE (self);
	self->priv->_collapse_mode = GRANITE_COLLAPSE_MODE_NONE;
	self->priv->saved_state = 10;
	self->priv->last_click_time = (guint) 0;
}


static void granite_widgets_collapsible_paned_finalize (GObject * obj) {
	GraniteWidgetsCollapsiblePaned * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRANITE_WIDGETS_TYPE_COLLAPSIBLE_PANED, GraniteWidgetsCollapsiblePaned);
	G_OBJECT_CLASS (granite_widgets_collapsible_paned_parent_class)->finalize (obj);
}


/**
     * A paned that can be easily collapsed by double-clicking over the pane separator.
     * If it was previously collapsed, it is expanded, and vice-versa.
     */
GType granite_widgets_collapsible_paned_get_type (void) {
	static volatile gsize granite_widgets_collapsible_paned_type_id__volatile = 0;
	if (g_once_init_enter (&granite_widgets_collapsible_paned_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraniteWidgetsCollapsiblePanedClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) granite_widgets_collapsible_paned_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraniteWidgetsCollapsiblePaned), 0, (GInstanceInitFunc) granite_widgets_collapsible_paned_instance_init, NULL };
		GType granite_widgets_collapsible_paned_type_id;
		granite_widgets_collapsible_paned_type_id = g_type_register_static (gtk_paned_get_type (), "GraniteWidgetsCollapsiblePaned", &g_define_type_info, 0);
		g_once_init_leave (&granite_widgets_collapsible_paned_type_id__volatile, granite_widgets_collapsible_paned_type_id);
	}
	return granite_widgets_collapsible_paned_type_id__volatile;
}


static void _vala_granite_widgets_collapsible_paned_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GraniteWidgetsCollapsiblePaned * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GRANITE_WIDGETS_TYPE_COLLAPSIBLE_PANED, GraniteWidgetsCollapsiblePaned);
	switch (property_id) {
		case GRANITE_WIDGETS_COLLAPSIBLE_PANED_COLLAPSE_MODE_PROPERTY:
		g_value_set_enum (value, granite_widgets_collapsible_paned_get_collapse_mode (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_granite_widgets_collapsible_paned_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GraniteWidgetsCollapsiblePaned * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GRANITE_WIDGETS_TYPE_COLLAPSIBLE_PANED, GraniteWidgetsCollapsiblePaned);
	switch (property_id) {
		case GRANITE_WIDGETS_COLLAPSIBLE_PANED_COLLAPSE_MODE_PROPERTY:
		granite_widgets_collapsible_paned_set_collapse_mode (self, g_value_get_enum (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


GraniteWidgetsHCollapsablePaned* granite_widgets_hcollapsable_paned_construct (GType object_type) {
	GraniteWidgetsHCollapsablePaned * self = NULL;
	self = (GraniteWidgetsHCollapsablePaned*) granite_widgets_collapsible_paned_construct (object_type, GTK_ORIENTATION_HORIZONTAL);
	return self;
}


GraniteWidgetsHCollapsablePaned* granite_widgets_hcollapsable_paned_new (void) {
	return granite_widgets_hcollapsable_paned_construct (GRANITE_WIDGETS_TYPE_HCOLLAPSABLE_PANED);
}


static void granite_widgets_hcollapsable_paned_class_init (GraniteWidgetsHCollapsablePanedClass * klass) {
	granite_widgets_hcollapsable_paned_parent_class = g_type_class_peek_parent (klass);
}


static void granite_widgets_hcollapsable_paned_instance_init (GraniteWidgetsHCollapsablePaned * self) {
}


GType granite_widgets_hcollapsable_paned_get_type (void) {
	static volatile gsize granite_widgets_hcollapsable_paned_type_id__volatile = 0;
	if (g_once_init_enter (&granite_widgets_hcollapsable_paned_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraniteWidgetsHCollapsablePanedClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) granite_widgets_hcollapsable_paned_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraniteWidgetsHCollapsablePaned), 0, (GInstanceInitFunc) granite_widgets_hcollapsable_paned_instance_init, NULL };
		GType granite_widgets_hcollapsable_paned_type_id;
		granite_widgets_hcollapsable_paned_type_id = g_type_register_static (GRANITE_WIDGETS_TYPE_COLLAPSIBLE_PANED, "GraniteWidgetsHCollapsablePaned", &g_define_type_info, 0);
		g_once_init_leave (&granite_widgets_hcollapsable_paned_type_id__volatile, granite_widgets_hcollapsable_paned_type_id);
	}
	return granite_widgets_hcollapsable_paned_type_id__volatile;
}


GraniteWidgetsVCollapsablePaned* granite_widgets_vcollapsable_paned_construct (GType object_type) {
	GraniteWidgetsVCollapsablePaned * self = NULL;
	self = (GraniteWidgetsVCollapsablePaned*) granite_widgets_collapsible_paned_construct (object_type, GTK_ORIENTATION_VERTICAL);
	return self;
}


GraniteWidgetsVCollapsablePaned* granite_widgets_vcollapsable_paned_new (void) {
	return granite_widgets_vcollapsable_paned_construct (GRANITE_WIDGETS_TYPE_VCOLLAPSABLE_PANED);
}


static void granite_widgets_vcollapsable_paned_class_init (GraniteWidgetsVCollapsablePanedClass * klass) {
	granite_widgets_vcollapsable_paned_parent_class = g_type_class_peek_parent (klass);
}


static void granite_widgets_vcollapsable_paned_instance_init (GraniteWidgetsVCollapsablePaned * self) {
}


GType granite_widgets_vcollapsable_paned_get_type (void) {
	static volatile gsize granite_widgets_vcollapsable_paned_type_id__volatile = 0;
	if (g_once_init_enter (&granite_widgets_vcollapsable_paned_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraniteWidgetsVCollapsablePanedClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) granite_widgets_vcollapsable_paned_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraniteWidgetsVCollapsablePaned), 0, (GInstanceInitFunc) granite_widgets_vcollapsable_paned_instance_init, NULL };
		GType granite_widgets_vcollapsable_paned_type_id;
		granite_widgets_vcollapsable_paned_type_id = g_type_register_static (GRANITE_WIDGETS_TYPE_COLLAPSIBLE_PANED, "GraniteWidgetsVCollapsablePaned", &g_define_type_info, 0);
		g_once_init_leave (&granite_widgets_vcollapsable_paned_type_id__volatile, granite_widgets_vcollapsable_paned_type_id);
	}
	return granite_widgets_vcollapsable_paned_type_id__volatile;
}



