/* CompositedWindow.c generated by valac 0.36.7, the Vala compiler
 * generated from CompositedWindow.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>


#define GRANITE_WIDGETS_TYPE_COMPOSITED_WINDOW (granite_widgets_composited_window_get_type ())
#define GRANITE_WIDGETS_COMPOSITED_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_WIDGETS_TYPE_COMPOSITED_WINDOW, GraniteWidgetsCompositedWindow))
#define GRANITE_WIDGETS_COMPOSITED_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_WIDGETS_TYPE_COMPOSITED_WINDOW, GraniteWidgetsCompositedWindowClass))
#define GRANITE_WIDGETS_IS_COMPOSITED_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_WIDGETS_TYPE_COMPOSITED_WINDOW))
#define GRANITE_WIDGETS_IS_COMPOSITED_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_WIDGETS_TYPE_COMPOSITED_WINDOW))
#define GRANITE_WIDGETS_COMPOSITED_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_WIDGETS_TYPE_COMPOSITED_WINDOW, GraniteWidgetsCompositedWindowClass))

typedef struct _GraniteWidgetsCompositedWindow GraniteWidgetsCompositedWindow;
typedef struct _GraniteWidgetsCompositedWindowClass GraniteWidgetsCompositedWindowClass;
typedef struct _GraniteWidgetsCompositedWindowPrivate GraniteWidgetsCompositedWindowPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _GraniteWidgetsCompositedWindow {
	GtkWindow parent_instance;
	GraniteWidgetsCompositedWindowPrivate * priv;
};

struct _GraniteWidgetsCompositedWindowClass {
	GtkWindowClass parent_class;
};


static gpointer granite_widgets_composited_window_parent_class = NULL;
static GtkBuildableIface * granite_widgets_composited_window_gtk_buildable_parent_iface = NULL;

GType granite_widgets_composited_window_get_type (void) G_GNUC_CONST;
enum  {
	GRANITE_WIDGETS_COMPOSITED_WINDOW_0_PROPERTY
};
#define GRANITE_WIDGETS_COMPOSITED_WINDOW_STYLESHEET ".composited { background-color: rgba (0,0,0,0); }"
GraniteWidgetsCompositedWindow* granite_widgets_composited_window_new (void);
GraniteWidgetsCompositedWindow* granite_widgets_composited_window_construct (GType object_type);
static GObject * granite_widgets_composited_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
GtkCssProvider* granite_widgets_utils_set_theming (GtkWidget* widget, const gchar* stylesheet, const gchar* class_name, gint priority);
#define GRANITE_STYLE_CLASS_COMPOSITED "composited"


GraniteWidgetsCompositedWindow* granite_widgets_composited_window_construct (GType object_type) {
	GraniteWidgetsCompositedWindow * self = NULL;
	self = (GraniteWidgetsCompositedWindow*) g_object_new (object_type, NULL);
	return self;
}


GraniteWidgetsCompositedWindow* granite_widgets_composited_window_new (void) {
	return granite_widgets_composited_window_construct (GRANITE_WIDGETS_TYPE_COMPOSITED_WINDOW);
}


static GObject * granite_widgets_composited_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	GraniteWidgetsCompositedWindow * self;
	GdkScreen* _tmp0_;
	GdkVisual* _tmp1_;
	GtkCssProvider* _tmp2_;
	GtkCssProvider* _tmp3_;
	parent_class = G_OBJECT_CLASS (granite_widgets_composited_window_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRANITE_WIDGETS_TYPE_COMPOSITED_WINDOW, GraniteWidgetsCompositedWindow);
	gtk_widget_set_app_paintable ((GtkWidget*) self, TRUE);
	gtk_window_set_decorated ((GtkWindow*) self, FALSE);
	gtk_window_set_resizable ((GtkWindow*) self, FALSE);
	_tmp0_ = gtk_window_get_screen ((GtkWindow*) self);
	_tmp1_ = gdk_screen_get_rgba_visual (_tmp0_);
	gtk_widget_set_visual ((GtkWidget*) self, _tmp1_);
	_tmp2_ = granite_widgets_utils_set_theming ((GtkWidget*) self, GRANITE_WIDGETS_COMPOSITED_WINDOW_STYLESHEET, GRANITE_STYLE_CLASS_COMPOSITED, GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
	_tmp3_ = _tmp2_;
	_g_object_unref0 (_tmp3_);
	return obj;
}


static void granite_widgets_composited_window_class_init (GraniteWidgetsCompositedWindowClass * klass) {
	granite_widgets_composited_window_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->constructor = granite_widgets_composited_window_constructor;
}


static void granite_widgets_composited_window_gtk_buildable_interface_init (GtkBuildableIface * iface) {
	granite_widgets_composited_window_gtk_buildable_parent_iface = g_type_interface_peek_parent (iface);
}


static void granite_widgets_composited_window_instance_init (GraniteWidgetsCompositedWindow * self) {
}


/**
     * A transparent window without decorations and so on. Useful for any kinds of overlays and similar things
     */
GType granite_widgets_composited_window_get_type (void) {
	static volatile gsize granite_widgets_composited_window_type_id__volatile = 0;
	if (g_once_init_enter (&granite_widgets_composited_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraniteWidgetsCompositedWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) granite_widgets_composited_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraniteWidgetsCompositedWindow), 0, (GInstanceInitFunc) granite_widgets_composited_window_instance_init, NULL };
		static const GInterfaceInfo gtk_buildable_info = { (GInterfaceInitFunc) granite_widgets_composited_window_gtk_buildable_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType granite_widgets_composited_window_type_id;
		granite_widgets_composited_window_type_id = g_type_register_static (gtk_window_get_type (), "GraniteWidgetsCompositedWindow", &g_define_type_info, 0);
		g_type_add_interface_static (granite_widgets_composited_window_type_id, GTK_TYPE_BUILDABLE, &gtk_buildable_info);
		g_once_init_leave (&granite_widgets_composited_window_type_id__volatile, granite_widgets_composited_window_type_id);
	}
	return granite_widgets_composited_window_type_id__volatile;
}



