/* StaticNotebook.c generated by valac 0.36.7, the Vala compiler
 * generated from StaticNotebook.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define GRANITE_WIDGETS_TYPE_STATIC_NOTEBOOK (granite_widgets_static_notebook_get_type ())
#define GRANITE_WIDGETS_STATIC_NOTEBOOK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_WIDGETS_TYPE_STATIC_NOTEBOOK, GraniteWidgetsStaticNotebook))
#define GRANITE_WIDGETS_STATIC_NOTEBOOK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_WIDGETS_TYPE_STATIC_NOTEBOOK, GraniteWidgetsStaticNotebookClass))
#define GRANITE_WIDGETS_IS_STATIC_NOTEBOOK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_WIDGETS_TYPE_STATIC_NOTEBOOK))
#define GRANITE_WIDGETS_IS_STATIC_NOTEBOOK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_WIDGETS_TYPE_STATIC_NOTEBOOK))
#define GRANITE_WIDGETS_STATIC_NOTEBOOK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_WIDGETS_TYPE_STATIC_NOTEBOOK, GraniteWidgetsStaticNotebookClass))

typedef struct _GraniteWidgetsStaticNotebook GraniteWidgetsStaticNotebook;
typedef struct _GraniteWidgetsStaticNotebookClass GraniteWidgetsStaticNotebookClass;
typedef struct _GraniteWidgetsStaticNotebookPrivate GraniteWidgetsStaticNotebookPrivate;

#define GRANITE_WIDGETS_TYPE_MODE_BUTTON (granite_widgets_mode_button_get_type ())
#define GRANITE_WIDGETS_MODE_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_WIDGETS_TYPE_MODE_BUTTON, GraniteWidgetsModeButton))
#define GRANITE_WIDGETS_MODE_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_WIDGETS_TYPE_MODE_BUTTON, GraniteWidgetsModeButtonClass))
#define GRANITE_WIDGETS_IS_MODE_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_WIDGETS_TYPE_MODE_BUTTON))
#define GRANITE_WIDGETS_IS_MODE_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_WIDGETS_TYPE_MODE_BUTTON))
#define GRANITE_WIDGETS_MODE_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_WIDGETS_TYPE_MODE_BUTTON, GraniteWidgetsModeButtonClass))

typedef struct _GraniteWidgetsModeButton GraniteWidgetsModeButton;
typedef struct _GraniteWidgetsModeButtonClass GraniteWidgetsModeButtonClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
enum  {
	GRANITE_WIDGETS_STATIC_NOTEBOOK_PAGE_CHANGED_SIGNAL,
	GRANITE_WIDGETS_STATIC_NOTEBOOK_NUM_SIGNALS
};
static guint granite_widgets_static_notebook_signals[GRANITE_WIDGETS_STATIC_NOTEBOOK_NUM_SIGNALS] = {0};

struct _GraniteWidgetsStaticNotebook {
	GtkBox parent_instance;
	GraniteWidgetsStaticNotebookPrivate * priv;
};

struct _GraniteWidgetsStaticNotebookClass {
	GtkBoxClass parent_class;
};

struct _GraniteWidgetsStaticNotebookPrivate {
	GtkNotebook* notebook;
	GraniteWidgetsModeButton* switcher;
	GtkBox* switcher_box;
	gboolean switcher_hidden;
};


static gpointer granite_widgets_static_notebook_parent_class = NULL;

GType granite_widgets_static_notebook_get_type (void) G_GNUC_CONST;
GType granite_widgets_mode_button_get_type (void) G_GNUC_CONST;
#define GRANITE_WIDGETS_STATIC_NOTEBOOK_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GRANITE_WIDGETS_TYPE_STATIC_NOTEBOOK, GraniteWidgetsStaticNotebookPrivate))
enum  {
	GRANITE_WIDGETS_STATIC_NOTEBOOK_0_PROPERTY,
	GRANITE_WIDGETS_STATIC_NOTEBOOK_PAGE_PROPERTY
};
GraniteWidgetsStaticNotebook* granite_widgets_static_notebook_new (gboolean show_separator);
GraniteWidgetsStaticNotebook* granite_widgets_static_notebook_construct (GType object_type, gboolean show_separator);
GraniteWidgetsModeButton* granite_widgets_mode_button_new (void);
GraniteWidgetsModeButton* granite_widgets_mode_button_construct (GType object_type);
static void granite_widgets_static_notebook_on_mode_changed (GraniteWidgetsStaticNotebook* self, GtkWidget* widget);
static void _granite_widgets_static_notebook_on_mode_changed_granite_widgets_mode_button_mode_changed (GraniteWidgetsModeButton* _sender, GtkWidget* widget, gpointer self);
void granite_widgets_static_notebook_set_switcher_visible (GraniteWidgetsStaticNotebook* self, gboolean val);
static void granite_widgets_static_notebook_update_switcher_visibility (GraniteWidgetsStaticNotebook* self);
gint granite_widgets_static_notebook_append_page (GraniteWidgetsStaticNotebook* self, GtkWidget* widget, GtkLabel* label);
gint granite_widgets_mode_button_append (GraniteWidgetsModeButton* self, GtkWidget* w);
gint granite_widgets_mode_button_get_selected (GraniteWidgetsModeButton* self);
void granite_widgets_mode_button_set_selected (GraniteWidgetsModeButton* self, gint value);
void granite_widgets_static_notebook_remove_page (GraniteWidgetsStaticNotebook* self, gint number);
void granite_widgets_mode_button_remove (GraniteWidgetsModeButton* self, gint index);
gint granite_widgets_static_notebook_get_page (GraniteWidgetsStaticNotebook* self);
void granite_widgets_static_notebook_set_page (GraniteWidgetsStaticNotebook* self, gint value);
static void granite_widgets_static_notebook_finalize (GObject * obj);
static void _vala_granite_widgets_static_notebook_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_granite_widgets_static_notebook_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


/**
         * This creates a new StaticNotebook
         * 
         * @param show_separator whether or not to show a seperator
         */
static void _granite_widgets_static_notebook_on_mode_changed_granite_widgets_mode_button_mode_changed (GraniteWidgetsModeButton* _sender, GtkWidget* widget, gpointer self) {
	granite_widgets_static_notebook_on_mode_changed ((GraniteWidgetsStaticNotebook*) self, widget);
}


GraniteWidgetsStaticNotebook* granite_widgets_static_notebook_construct (GType object_type, gboolean show_separator) {
	GraniteWidgetsStaticNotebook * self = NULL;
	GtkNotebook* _tmp0_;
	GtkNotebook* _tmp1_;
	GraniteWidgetsModeButton* _tmp2_;
	GtkBox* _tmp3_;
	gboolean _tmp4_;
	GraniteWidgetsModeButton* _tmp16_;
	GraniteWidgetsModeButton* _tmp17_;
	GtkBox* _tmp18_;
	GtkNotebook* _tmp19_;
	GraniteWidgetsModeButton* _tmp20_;
	self = (GraniteWidgetsStaticNotebook*) g_object_new (object_type, NULL);
	gtk_orientable_set_orientation ((GtkOrientable*) self, GTK_ORIENTATION_VERTICAL);
	self->priv->switcher_hidden = FALSE;
	_tmp0_ = (GtkNotebook*) gtk_notebook_new ();
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->notebook);
	self->priv->notebook = _tmp0_;
	_tmp1_ = self->priv->notebook;
	gtk_notebook_set_show_tabs (_tmp1_, FALSE);
	_tmp2_ = granite_widgets_mode_button_new ();
	g_object_ref_sink (_tmp2_);
	_g_object_unref0 (self->priv->switcher);
	self->priv->switcher = _tmp2_;
	_tmp3_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
	g_object_ref_sink (_tmp3_);
	_g_object_unref0 (self->priv->switcher_box);
	self->priv->switcher_box = _tmp3_;
	_tmp4_ = show_separator;
	if (_tmp4_) {
		GtkSeparator* left_separator = NULL;
		GtkSeparator* _tmp5_;
		GtkSeparator* right_separator = NULL;
		GtkSeparator* _tmp6_;
		GtkBox* _tmp7_;
		GtkSeparator* _tmp8_;
		GtkBox* _tmp9_;
		GraniteWidgetsModeButton* _tmp10_;
		GtkBox* _tmp11_;
		GtkSeparator* _tmp12_;
		_tmp5_ = (GtkSeparator*) gtk_separator_new (GTK_ORIENTATION_HORIZONTAL);
		g_object_ref_sink (_tmp5_);
		left_separator = _tmp5_;
		_tmp6_ = (GtkSeparator*) gtk_separator_new (GTK_ORIENTATION_HORIZONTAL);
		g_object_ref_sink (_tmp6_);
		right_separator = _tmp6_;
		_tmp7_ = self->priv->switcher_box;
		_tmp8_ = left_separator;
		gtk_box_pack_start (_tmp7_, (GtkWidget*) _tmp8_, TRUE, TRUE, (guint) 0);
		_tmp9_ = self->priv->switcher_box;
		_tmp10_ = self->priv->switcher;
		gtk_box_pack_start (_tmp9_, (GtkWidget*) _tmp10_, FALSE, FALSE, (guint) 0);
		_tmp11_ = self->priv->switcher_box;
		_tmp12_ = right_separator;
		gtk_box_pack_end (_tmp11_, (GtkWidget*) _tmp12_, TRUE, TRUE, (guint) 0);
		_g_object_unref0 (right_separator);
		_g_object_unref0 (left_separator);
	} else {
		GraniteWidgetsModeButton* _tmp13_;
		GtkBox* _tmp14_;
		GraniteWidgetsModeButton* _tmp15_;
		_tmp13_ = self->priv->switcher;
		gtk_widget_set_halign ((GtkWidget*) _tmp13_, GTK_ALIGN_CENTER);
		_tmp14_ = self->priv->switcher_box;
		_tmp15_ = self->priv->switcher;
		gtk_box_pack_start (_tmp14_, (GtkWidget*) _tmp15_, TRUE, TRUE, (guint) 0);
	}
	_tmp16_ = self->priv->switcher;
	gtk_widget_set_margin_top ((GtkWidget*) _tmp16_, 5);
	_tmp17_ = self->priv->switcher;
	gtk_widget_set_margin_bottom ((GtkWidget*) _tmp17_, 5);
	_tmp18_ = self->priv->switcher_box;
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp18_, FALSE, FALSE, (guint) 0);
	_tmp19_ = self->priv->notebook;
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp19_, TRUE, TRUE, (guint) 0);
	_tmp20_ = self->priv->switcher;
	g_signal_connect_object (_tmp20_, "mode-changed", (GCallback) _granite_widgets_static_notebook_on_mode_changed_granite_widgets_mode_button_mode_changed, self, 0);
	return self;
}


GraniteWidgetsStaticNotebook* granite_widgets_static_notebook_new (gboolean show_separator) {
	return granite_widgets_static_notebook_construct (GRANITE_WIDGETS_TYPE_STATIC_NOTEBOOK, show_separator);
}


void granite_widgets_static_notebook_set_switcher_visible (GraniteWidgetsStaticNotebook* self, gboolean val) {
	GtkBox* _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp2_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->switcher_box;
	_tmp1_ = val;
	gtk_widget_set_no_show_all ((GtkWidget*) _tmp0_, !_tmp1_);
	_tmp2_ = val;
	self->priv->switcher_hidden = !_tmp2_;
	granite_widgets_static_notebook_update_switcher_visibility (self);
}


gint granite_widgets_static_notebook_append_page (GraniteWidgetsStaticNotebook* self, GtkWidget* widget, GtkLabel* label) {
	gint result = 0;
	gint index = 0;
	GtkNotebook* _tmp0_;
	GtkWidget* _tmp1_;
	gint _tmp2_;
	GtkLabel* _tmp3_;
	GtkLabel* _tmp4_;
	GraniteWidgetsModeButton* _tmp5_;
	GtkLabel* _tmp6_;
	GraniteWidgetsModeButton* _tmp7_;
	gint _tmp8_;
	gint _tmp9_;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (widget != NULL, 0);
	g_return_val_if_fail (label != NULL, 0);
	_tmp0_ = self->priv->notebook;
	_tmp1_ = widget;
	_tmp2_ = gtk_notebook_append_page (_tmp0_, _tmp1_, NULL);
	index = _tmp2_;
	_tmp3_ = label;
	gtk_widget_set_margin_right ((GtkWidget*) _tmp3_, 5);
	_tmp4_ = label;
	gtk_widget_set_margin_left ((GtkWidget*) _tmp4_, 5);
	_tmp5_ = self->priv->switcher;
	_tmp6_ = label;
	granite_widgets_mode_button_append (_tmp5_, (GtkWidget*) _tmp6_);
	_tmp7_ = self->priv->switcher;
	_tmp8_ = granite_widgets_mode_button_get_selected (_tmp7_);
	_tmp9_ = _tmp8_;
	if (_tmp9_ == -1) {
		GraniteWidgetsModeButton* _tmp10_;
		_tmp10_ = self->priv->switcher;
		granite_widgets_mode_button_set_selected (_tmp10_, 0);
	}
	granite_widgets_static_notebook_update_switcher_visibility (self);
	result = index;
	return result;
}


static void granite_widgets_static_notebook_on_mode_changed (GraniteWidgetsStaticNotebook* self, GtkWidget* widget) {
	GtkNotebook* _tmp0_;
	GraniteWidgetsModeButton* _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	GtkNotebook* _tmp4_;
	gint _tmp5_;
	gint _tmp6_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (widget != NULL);
	_tmp0_ = self->priv->notebook;
	_tmp1_ = self->priv->switcher;
	_tmp2_ = granite_widgets_mode_button_get_selected (_tmp1_);
	_tmp3_ = _tmp2_;
	g_object_set (_tmp0_, "page", _tmp3_, NULL);
	_tmp4_ = self->priv->notebook;
	g_object_get (_tmp4_, "page", &_tmp5_, NULL);
	_tmp6_ = _tmp5_;
	g_signal_emit (self, granite_widgets_static_notebook_signals[GRANITE_WIDGETS_STATIC_NOTEBOOK_PAGE_CHANGED_SIGNAL], 0, _tmp6_);
}


void granite_widgets_static_notebook_remove_page (GraniteWidgetsStaticNotebook* self, gint number) {
	GtkNotebook* _tmp0_;
	gint _tmp1_;
	GraniteWidgetsModeButton* _tmp2_;
	gint _tmp3_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->notebook;
	_tmp1_ = number;
	gtk_notebook_remove_page (_tmp0_, _tmp1_);
	_tmp2_ = self->priv->switcher;
	_tmp3_ = number;
	granite_widgets_mode_button_remove (_tmp2_, _tmp3_);
	granite_widgets_static_notebook_update_switcher_visibility (self);
}


static void granite_widgets_static_notebook_update_switcher_visibility (GraniteWidgetsStaticNotebook* self) {
	gboolean _tmp0_;
	gboolean switcher_visible = FALSE;
	GtkNotebook* _tmp2_;
	gint _tmp3_;
	GtkBox* _tmp4_;
	gboolean _tmp5_;
	gboolean _tmp6_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->switcher_hidden;
	if (_tmp0_) {
		GtkBox* _tmp1_;
		_tmp1_ = self->priv->switcher_box;
		gtk_widget_hide ((GtkWidget*) _tmp1_);
		return;
	}
	_tmp2_ = self->priv->notebook;
	_tmp3_ = gtk_notebook_get_n_pages (_tmp2_);
	switcher_visible = _tmp3_ > 1;
	_tmp4_ = self->priv->switcher_box;
	_tmp5_ = switcher_visible;
	gtk_widget_set_no_show_all ((GtkWidget*) _tmp4_, !_tmp5_);
	_tmp6_ = switcher_visible;
	if (_tmp6_) {
		GtkBox* _tmp7_;
		_tmp7_ = self->priv->switcher_box;
		gtk_widget_show_all ((GtkWidget*) _tmp7_);
	} else {
		GtkBox* _tmp8_;
		_tmp8_ = self->priv->switcher_box;
		gtk_widget_hide ((GtkWidget*) _tmp8_);
	}
}


gint granite_widgets_static_notebook_get_page (GraniteWidgetsStaticNotebook* self) {
	gint result;
	GtkNotebook* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->notebook;
	g_object_get (_tmp0_, "page", &_tmp1_, NULL);
	_tmp2_ = _tmp1_;
	result = _tmp2_;
	return result;
}


void granite_widgets_static_notebook_set_page (GraniteWidgetsStaticNotebook* self, gint value) {
	GraniteWidgetsModeButton* _tmp0_;
	gint _tmp1_;
	GtkNotebook* _tmp2_;
	gint _tmp3_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->switcher;
	_tmp1_ = value;
	granite_widgets_mode_button_set_selected (_tmp0_, _tmp1_);
	_tmp2_ = self->priv->notebook;
	_tmp3_ = value;
	g_object_set (_tmp2_, "page", _tmp3_, NULL);
	g_object_notify ((GObject *) self, "page");
}


static void granite_widgets_static_notebook_class_init (GraniteWidgetsStaticNotebookClass * klass) {
	granite_widgets_static_notebook_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GraniteWidgetsStaticNotebookPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_granite_widgets_static_notebook_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_granite_widgets_static_notebook_set_property;
	G_OBJECT_CLASS (klass)->finalize = granite_widgets_static_notebook_finalize;
	/**
	         * This currently selected page
	         */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_WIDGETS_STATIC_NOTEBOOK_PAGE_PROPERTY, g_param_spec_int ("page", "page", "page", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	granite_widgets_static_notebook_signals[GRANITE_WIDGETS_STATIC_NOTEBOOK_PAGE_CHANGED_SIGNAL] = g_signal_new ("page-changed", GRANITE_WIDGETS_TYPE_STATIC_NOTEBOOK, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__INT, G_TYPE_NONE, 1, G_TYPE_INT);
}


static void granite_widgets_static_notebook_instance_init (GraniteWidgetsStaticNotebook * self) {
	self->priv = GRANITE_WIDGETS_STATIC_NOTEBOOK_GET_PRIVATE (self);
}


static void granite_widgets_static_notebook_finalize (GObject * obj) {
	GraniteWidgetsStaticNotebook * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRANITE_WIDGETS_TYPE_STATIC_NOTEBOOK, GraniteWidgetsStaticNotebook);
	_g_object_unref0 (self->priv->notebook);
	_g_object_unref0 (self->priv->switcher);
	_g_object_unref0 (self->priv->switcher_box);
	G_OBJECT_CLASS (granite_widgets_static_notebook_parent_class)->finalize (obj);
}


/**
     * This class provides an easy way to manage tabs.
     */
GType granite_widgets_static_notebook_get_type (void) {
	static volatile gsize granite_widgets_static_notebook_type_id__volatile = 0;
	if (g_once_init_enter (&granite_widgets_static_notebook_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraniteWidgetsStaticNotebookClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) granite_widgets_static_notebook_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraniteWidgetsStaticNotebook), 0, (GInstanceInitFunc) granite_widgets_static_notebook_instance_init, NULL };
		GType granite_widgets_static_notebook_type_id;
		granite_widgets_static_notebook_type_id = g_type_register_static (gtk_box_get_type (), "GraniteWidgetsStaticNotebook", &g_define_type_info, 0);
		g_once_init_leave (&granite_widgets_static_notebook_type_id__volatile, granite_widgets_static_notebook_type_id);
	}
	return granite_widgets_static_notebook_type_id__volatile;
}


static void _vala_granite_widgets_static_notebook_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GraniteWidgetsStaticNotebook * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GRANITE_WIDGETS_TYPE_STATIC_NOTEBOOK, GraniteWidgetsStaticNotebook);
	switch (property_id) {
		case GRANITE_WIDGETS_STATIC_NOTEBOOK_PAGE_PROPERTY:
		g_value_set_int (value, granite_widgets_static_notebook_get_page (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_granite_widgets_static_notebook_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GraniteWidgetsStaticNotebook * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GRANITE_WIDGETS_TYPE_STATIC_NOTEBOOK, GraniteWidgetsStaticNotebook);
	switch (property_id) {
		case GRANITE_WIDGETS_STATIC_NOTEBOOK_PAGE_PROPERTY:
		granite_widgets_static_notebook_set_page (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



