/* GraniteDemo.c generated by valac 0.36.7, the Vala compiler
 * generated from GraniteDemo.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "granite.h"
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <gdk-pixbuf/gdk-pixbuf.h>


#define GRANITE_TYPE_DEMO (granite_demo_get_type ())
#define GRANITE_DEMO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_TYPE_DEMO, GraniteDemo))
#define GRANITE_DEMO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_TYPE_DEMO, GraniteDemoClass))
#define GRANITE_IS_DEMO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_TYPE_DEMO))
#define GRANITE_IS_DEMO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_TYPE_DEMO))
#define GRANITE_DEMO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_TYPE_DEMO, GraniteDemoClass))

typedef struct _GraniteDemo GraniteDemo;
typedef struct _GraniteDemoClass GraniteDemoClass;
typedef struct _GraniteDemoPrivate GraniteDemoPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _Block1Data Block1Data;

#define GRANITE_DEMO_TYPE_SOURCE_LIST_ITEM (granite_demo_source_list_item_get_type ())
#define GRANITE_DEMO_SOURCE_LIST_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_DEMO_TYPE_SOURCE_LIST_ITEM, GraniteDemoSourceListItem))
#define GRANITE_DEMO_SOURCE_LIST_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_DEMO_TYPE_SOURCE_LIST_ITEM, GraniteDemoSourceListItemClass))
#define GRANITE_DEMO_IS_SOURCE_LIST_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_DEMO_TYPE_SOURCE_LIST_ITEM))
#define GRANITE_DEMO_IS_SOURCE_LIST_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_DEMO_TYPE_SOURCE_LIST_ITEM))
#define GRANITE_DEMO_SOURCE_LIST_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_DEMO_TYPE_SOURCE_LIST_ITEM, GraniteDemoSourceListItemClass))

typedef struct _GraniteDemoSourceListItem GraniteDemoSourceListItem;
typedef struct _GraniteDemoSourceListItemClass GraniteDemoSourceListItemClass;

#define GRANITE_DEMO_TYPE_SOURCE_LIST_EXPANDABLE_ITEM (granite_demo_source_list_expandable_item_get_type ())
#define GRANITE_DEMO_SOURCE_LIST_EXPANDABLE_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_DEMO_TYPE_SOURCE_LIST_EXPANDABLE_ITEM, GraniteDemoSourceListExpandableItem))
#define GRANITE_DEMO_SOURCE_LIST_EXPANDABLE_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_DEMO_TYPE_SOURCE_LIST_EXPANDABLE_ITEM, GraniteDemoSourceListExpandableItemClass))
#define GRANITE_DEMO_IS_SOURCE_LIST_EXPANDABLE_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_DEMO_TYPE_SOURCE_LIST_EXPANDABLE_ITEM))
#define GRANITE_DEMO_IS_SOURCE_LIST_EXPANDABLE_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_DEMO_TYPE_SOURCE_LIST_EXPANDABLE_ITEM))
#define GRANITE_DEMO_SOURCE_LIST_EXPANDABLE_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_DEMO_TYPE_SOURCE_LIST_EXPANDABLE_ITEM, GraniteDemoSourceListExpandableItemClass))

typedef struct _GraniteDemoSourceListExpandableItem GraniteDemoSourceListExpandableItem;
typedef struct _GraniteDemoSourceListExpandableItemClass GraniteDemoSourceListExpandableItemClass;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define GRANITE_DEMO_TYPE_LLABEL (granite_demo_llabel_get_type ())
#define GRANITE_DEMO_LLABEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GRANITE_DEMO_TYPE_LLABEL, GraniteDemoLLabel))
#define GRANITE_DEMO_LLABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GRANITE_DEMO_TYPE_LLABEL, GraniteDemoLLabelClass))
#define GRANITE_DEMO_IS_LLABEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GRANITE_DEMO_TYPE_LLABEL))
#define GRANITE_DEMO_IS_LLABEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GRANITE_DEMO_TYPE_LLABEL))
#define GRANITE_DEMO_LLABEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GRANITE_DEMO_TYPE_LLABEL, GraniteDemoLLabelClass))

typedef struct _GraniteDemoLLabel GraniteDemoLLabel;
typedef struct _GraniteDemoLLabelClass GraniteDemoLLabelClass;
typedef struct _Block2Data Block2Data;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _GraniteDemoLLabelPrivate GraniteDemoLLabelPrivate;
typedef struct _GraniteDemoSourceListExpandableItemPrivate GraniteDemoSourceListExpandableItemPrivate;
typedef struct _GraniteDemoSourceListItemPrivate GraniteDemoSourceListItemPrivate;
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _GraniteDemo {
	GraniteApplication parent_instance;
	GraniteDemoPrivate * priv;
};

struct _GraniteDemoClass {
	GraniteApplicationClass parent_class;
};

struct _GraniteDemoPrivate {
	GtkGrid* main_layout;
	GraniteWidgetsModeButton* mode_button;
	gint dark_mode_index;
};

struct _Block1Data {
	int _ref_count_;
	GraniteDemo* self;
	GtkWindow* window;
	GtkNotebook* page_switcher;
	GtkLabel* pageone;
	GtkButton* popover_statusbar_item;
};

struct _Block2Data {
	int _ref_count_;
	GraniteDemo* self;
	gint i;
	GraniteWidgetsDynamicNotebook* dynamic_notebook;
};

struct _GraniteDemoLLabel {
	GtkLabel parent_instance;
	GraniteDemoLLabelPrivate * priv;
};

struct _GraniteDemoLLabelClass {
	GtkLabelClass parent_class;
};

struct _GraniteDemoSourceListExpandableItem {
	GraniteWidgetsSourceListExpandableItem parent_instance;
	GraniteDemoSourceListExpandableItemPrivate * priv;
};

struct _GraniteDemoSourceListExpandableItemClass {
	GraniteWidgetsSourceListExpandableItemClass parent_class;
};

struct _GraniteDemoSourceListItem {
	GraniteWidgetsSourceListItem parent_instance;
	GraniteDemoSourceListItemPrivate * priv;
};

struct _GraniteDemoSourceListItemClass {
	GraniteWidgetsSourceListItemClass parent_class;
};

struct _GraniteDemoSourceListItemPrivate {
	gint _page_num;
};


static gpointer granite_demo_parent_class = NULL;
static gpointer granite_demo_llabel_parent_class = NULL;
static gpointer granite_demo_source_list_expandable_item_parent_class = NULL;
static gpointer granite_demo_source_list_item_parent_class = NULL;
static GIcon* granite_demo_source_list_item_themed_icon;
static GIcon* granite_demo_source_list_item_themed_icon = NULL;

GType granite_demo_get_type (void) G_GNUC_CONST;
#define GRANITE_DEMO_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GRANITE_TYPE_DEMO, GraniteDemoPrivate))
enum  {
	GRANITE_DEMO_0_PROPERTY
};
static void granite_demo_real_activate (GApplication* base);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void __lambda4_ (Block1Data* _data1_, GraniteWidgetsSourceListItem* item);
static GType granite_demo_source_list_item_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static gint granite_demo_source_list_item_get_page_num (GraniteDemoSourceListItem* self);
static void ___lambda4__granite_widgets_source_list_item_selected (GraniteWidgetsSourceList* _sender, GraniteWidgetsSourceListItem* item, gpointer self);
static GType granite_demo_source_list_expandable_item_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static GraniteDemoSourceListExpandableItem* granite_demo_source_list_expandable_item_new (const gchar* name);
static GraniteDemoSourceListExpandableItem* granite_demo_source_list_expandable_item_construct (GType object_type, const gchar* name);
static GraniteWidgetsWelcome* granite_demo_create_welcome_screen (GraniteDemo* self);
static GraniteDemoSourceListItem* granite_demo_source_list_item_new (const gchar* title);
static GraniteDemoSourceListItem* granite_demo_source_list_item_construct (GType object_type, const gchar* title);
static void granite_demo_source_list_item_set_page_num (GraniteDemoSourceListItem* self, gint value);
static void granite_demo_show_light_window (GraniteDemo* self);
static void _granite_demo_show_light_window_gtk_tool_button_clicked (GtkToolButton* _sender, gpointer self);
static GtkWidget* granite_demo_get_overlay_bar_widget (GraniteDemo* self);
static void __lambda5_ (Block1Data* _data1_);
static void ___lambda5__granite_widgets_static_notebook_page_changed (GraniteWidgetsStaticNotebook* _sender, gint index, gpointer self);
static void granite_demo_on_theme_mode_button_changed (GraniteDemo* self);
static void _granite_demo_on_theme_mode_button_changed_granite_widgets_mode_button_mode_changed (GraniteWidgetsModeButton* _sender, GtkWidget* widget, gpointer self);
static void __lambda6_ (Block1Data* _data1_);
static void ___lambda6__gtk_button_clicked (GtkButton* _sender, gpointer self);
static GraniteWidgetsDynamicNotebook* granite_demo_create_dynamic_notebook (GraniteDemo* self);
static GType granite_demo_llabel_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static GraniteDemoLLabel* granite_demo_llabel_new (const gchar* label);
static GraniteDemoLLabel* granite_demo_llabel_construct (GType object_type, const gchar* label);
static GraniteDemoLLabel* granite_demo_llabel_new_markup (const gchar* label);
static GraniteDemoLLabel* granite_demo_llabel_construct_markup (GType object_type, const gchar* label);
static GraniteDemoLLabel* granite_demo_llabel_new_right (const gchar* label);
static GraniteDemoLLabel* granite_demo_llabel_construct_right (GType object_type, const gchar* label);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static void __lambda7_ (Block2Data* _data2_);
static void ___lambda7__granite_widgets_dynamic_notebook_new_tab_requested (GraniteWidgetsDynamicNotebook* _sender, gpointer self);
static void __lambda8_ (Block2Data* _data2_, const gchar* label, const gchar* data, GIcon* icon);
static void ___lambda8__granite_widgets_dynamic_notebook_tab_restored (GraniteWidgetsDynamicNotebook* _sender, const gchar* label, const gchar* data, GIcon* icon, gpointer self);
static void __lambda9_ (Block2Data* _data2_, GraniteWidgetsTab* t);
static void ___lambda9__granite_widgets_dynamic_notebook_tab_duplicated (GraniteWidgetsDynamicNotebook* _sender, GraniteWidgetsTab* duplicated_tab, gpointer self);
static void __lambda10_ (GraniteDemo* self, GraniteWidgetsTab* t, gint p);
static void ___lambda10__granite_widgets_dynamic_notebook_tab_moved (GraniteWidgetsDynamicNotebook* _sender, GraniteWidgetsTab* tab, gint x, gint y, gpointer self);
static void __lambda11_ (GraniteDemo* self, GraniteWidgetsTab* old_t, GraniteWidgetsTab* new_t);
static void ___lambda11__granite_widgets_dynamic_notebook_tab_switched (GraniteWidgetsDynamicNotebook* _sender, GraniteWidgetsTab* old_tab, GraniteWidgetsTab* new_tab, gpointer self);
static void __lambda12_ (GraniteDemo* self, GraniteWidgetsTab* t);
static void ___lambda12__granite_widgets_dynamic_notebook_tab_removed (GraniteWidgetsDynamicNotebook* _sender, GraniteWidgetsTab* tab, gpointer self);
gint granite_demo_main (gchar** args, int args_length1);
GraniteDemo* granite_demo_new (void);
GraniteDemo* granite_demo_construct (GType object_type);
static GObject * granite_demo_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
enum  {
	GRANITE_DEMO_LLABEL_0_PROPERTY
};
static GraniteDemoLLabel* granite_demo_llabel_new_indent (const gchar* label);
static GraniteDemoLLabel* granite_demo_llabel_construct_indent (GType object_type, const gchar* label);
static GraniteDemoLLabel* granite_demo_llabel_new_right_with_markup (const gchar* label);
static GraniteDemoLLabel* granite_demo_llabel_construct_right_with_markup (GType object_type, const gchar* label);
enum  {
	GRANITE_DEMO_SOURCE_LIST_EXPANDABLE_ITEM_0_PROPERTY
};
static gint granite_demo_source_list_expandable_item_real_compare (GraniteWidgetsSourceListExpandableItem* base, GraniteWidgetsSourceListItem* a, GraniteWidgetsSourceListItem* b);
#define GRANITE_DEMO_SOURCE_LIST_ITEM_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GRANITE_DEMO_TYPE_SOURCE_LIST_ITEM, GraniteDemoSourceListItemPrivate))
enum  {
	GRANITE_DEMO_SOURCE_LIST_ITEM_0_PROPERTY,
	GRANITE_DEMO_SOURCE_LIST_ITEM_PAGE_NUM_PROPERTY
};
static void granite_demo_source_list_item_finalize (GObject * obj);
static void _vala_granite_demo_source_list_item_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_granite_demo_source_list_item_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void granite_demo_finalize (GObject * obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		GraniteDemo* self;
		self = _data1_->self;
		_g_object_unref0 (_data1_->popover_statusbar_item);
		_g_object_unref0 (_data1_->pageone);
		_g_object_unref0 (_data1_->page_switcher);
		_g_object_unref0 (_data1_->window);
		_g_object_unref0 (self);
		g_slice_free (Block1Data, _data1_);
	}
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void __lambda4_ (Block1Data* _data1_, GraniteWidgetsSourceListItem* item) {
	GraniteDemo* self;
	GraniteDemoSourceListItem* sidebar_item = NULL;
	GraniteWidgetsSourceListItem* _tmp0_;
	GraniteDemoSourceListItem* _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	self = _data1_->self;
	_tmp0_ = item;
	_tmp1_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, GRANITE_DEMO_TYPE_SOURCE_LIST_ITEM) ? ((GraniteDemoSourceListItem*) _tmp0_) : NULL);
	sidebar_item = _tmp1_;
	_vala_assert (sidebar_item != NULL, "sidebar_item != null");
	_tmp2_ = granite_demo_source_list_item_get_page_num (sidebar_item);
	_tmp3_ = _tmp2_;
	gtk_notebook_set_current_page (_data1_->page_switcher, _tmp3_);
	_g_object_unref0 (sidebar_item);
}


static void ___lambda4__granite_widgets_source_list_item_selected (GraniteWidgetsSourceList* _sender, GraniteWidgetsSourceListItem* item, gpointer self) {
	__lambda4_ (self, item);
}


static void _granite_demo_show_light_window_gtk_tool_button_clicked (GtkToolButton* _sender, gpointer self) {
	granite_demo_show_light_window ((GraniteDemo*) self);
}


static void __lambda5_ (Block1Data* _data1_) {
	GraniteDemo* self;
	self = _data1_->self;
	gtk_label_set_text (_data1_->pageone, "Page changed");
}


static void ___lambda5__granite_widgets_static_notebook_page_changed (GraniteWidgetsStaticNotebook* _sender, gint index, gpointer self) {
	__lambda5_ (self);
}


static void _granite_demo_on_theme_mode_button_changed_granite_widgets_mode_button_mode_changed (GraniteWidgetsModeButton* _sender, GtkWidget* widget, gpointer self) {
	granite_demo_on_theme_mode_button_changed ((GraniteDemo*) self);
}


static void __lambda6_ (Block1Data* _data1_) {
	GraniteDemo* self;
	GraniteWidgetsPopOver* pop = NULL;
	GraniteWidgetsPopOver* _tmp0_;
	GtkContainer* pop_hbox = NULL;
	GtkBox* _tmp1_;
	GtkContainer* _tmp2_;
	GraniteWidgetsHintedEntry* _tmp3_;
	GraniteWidgetsHintedEntry* _tmp4_;
	GtkLabel* _tmp5_;
	GtkLabel* _tmp6_;
	GraniteWidgetsModeButton* mode_pop = NULL;
	GraniteWidgetsModeButton* _tmp7_;
	GtkLabel* _tmp8_;
	GtkLabel* _tmp9_;
	GtkLabel* _tmp10_;
	GtkLabel* _tmp11_;
	GtkLabel* _tmp12_;
	GtkLabel* _tmp13_;
	GraniteWidgetsDatePicker* _tmp14_;
	GraniteWidgetsDatePicker* _tmp15_;
	self = _data1_->self;
	_tmp0_ = granite_widgets_pop_over_new ();
	g_object_ref_sink (_tmp0_);
	pop = _tmp0_;
	_tmp1_ = (GtkBox*) gtk_dialog_get_content_area ((GtkDialog*) pop);
	_tmp2_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp1_, gtk_container_get_type ()) ? ((GtkContainer*) _tmp1_) : NULL);
	pop_hbox = _tmp2_;
	_tmp3_ = granite_widgets_hinted_entry_new ("This is an HintedEntry");
	g_object_ref_sink (_tmp3_);
	_tmp4_ = _tmp3_;
	gtk_container_add (pop_hbox, (GtkWidget*) _tmp4_);
	_g_object_unref0 (_tmp4_);
	_tmp5_ = (GtkLabel*) gtk_label_new ("Another label");
	g_object_ref_sink (_tmp5_);
	_tmp6_ = _tmp5_;
	gtk_container_add (pop_hbox, (GtkWidget*) _tmp6_);
	_g_object_unref0 (_tmp6_);
	_tmp7_ = granite_widgets_mode_button_new ();
	g_object_ref_sink (_tmp7_);
	mode_pop = _tmp7_;
	_tmp8_ = (GtkLabel*) gtk_label_new ("Mode 1");
	g_object_ref_sink (_tmp8_);
	_tmp9_ = _tmp8_;
	granite_widgets_mode_button_append (mode_pop, (GtkWidget*) _tmp9_);
	_g_object_unref0 (_tmp9_);
	_tmp10_ = (GtkLabel*) gtk_label_new ("Mode 2");
	g_object_ref_sink (_tmp10_);
	_tmp11_ = _tmp10_;
	granite_widgets_mode_button_append (mode_pop, (GtkWidget*) _tmp11_);
	_g_object_unref0 (_tmp11_);
	_tmp12_ = (GtkLabel*) gtk_label_new ("Mode 3");
	g_object_ref_sink (_tmp12_);
	_tmp13_ = _tmp12_;
	granite_widgets_mode_button_append (mode_pop, (GtkWidget*) _tmp13_);
	_g_object_unref0 (_tmp13_);
	gtk_container_add (pop_hbox, (GtkWidget*) mode_pop);
	_tmp14_ = granite_widgets_date_picker_new ();
	g_object_ref_sink (_tmp14_);
	_tmp15_ = _tmp14_;
	gtk_container_add (pop_hbox, (GtkWidget*) _tmp15_);
	_g_object_unref0 (_tmp15_);
	granite_widgets_pop_over_set_parent_pop (pop, _data1_->window);
	granite_widgets_pop_over_move_to_widget (pop, (GtkWidget*) _data1_->popover_statusbar_item, TRUE);
	gtk_widget_show_all ((GtkWidget*) pop);
	gtk_window_present ((GtkWindow*) pop);
	gtk_dialog_run ((GtkDialog*) pop);
	gtk_widget_destroy ((GtkWidget*) pop);
	_g_object_unref0 (mode_pop);
	_g_object_unref0 (pop_hbox);
	_g_object_unref0 (pop);
}


static void ___lambda6__gtk_button_clicked (GtkButton* _sender, gpointer self) {
	__lambda6_ (self);
}


static void granite_demo_real_activate (GApplication* base) {
	GraniteDemo * self;
	Block1Data* _data1_;
	GtkWindow* _tmp0_;
	GtkToolbar* main_toolbar = NULL;
	GtkToolbar* _tmp1_;
	GtkStyleContext* _tmp2_;
	GraniteWidgetsSourceList* sidebar = NULL;
	GraniteWidgetsSourceListExpandableItem* _tmp3_;
	GraniteWidgetsSourceListExpandableItem* _tmp4_;
	GraniteWidgetsSourceList* _tmp5_;
	GraniteWidgetsSourceList* _tmp6_;
	GtkNotebook* _tmp7_;
	GraniteDemoSourceListExpandableItem* widgets_category = NULL;
	GraniteDemoSourceListExpandableItem* _tmp8_;
	GraniteDemoSourceListExpandableItem* services_category = NULL;
	GraniteDemoSourceListExpandableItem* _tmp9_;
	GraniteWidgetsSourceListExpandableItem* _tmp10_;
	GraniteWidgetsSourceListExpandableItem* _tmp11_;
	GraniteWidgetsSourceListExpandableItem* _tmp12_;
	GraniteWidgetsSourceListExpandableItem* _tmp13_;
	GraniteWidgetsSourceListExpandableItem* _tmp14_;
	GraniteWidgetsSourceListExpandableItem* _tmp15_;
	GraniteWidgetsThinPaned* sidebar_paned = NULL;
	GraniteWidgetsThinPaned* _tmp16_;
	GraniteWidgetsStatusBar* statusbar = NULL;
	GraniteWidgetsStatusBar* _tmp17_;
	GtkGrid* _tmp18_;
	GtkGrid* _tmp19_;
	GtkGrid* _tmp20_;
	GtkGrid* _tmp21_;
	GtkGrid* _tmp22_;
	GtkGrid* _tmp23_;
	GtkGrid* _tmp24_;
	GraniteWidgetsWelcome* welcome_screen = NULL;
	GraniteWidgetsWelcome* _tmp25_;
	GraniteDemoSourceListItem* welcome_item = NULL;
	GraniteDemoSourceListItem* _tmp26_;
	gint _tmp27_;
	GtkImage* light_window_icon = NULL;
	GtkImage* _tmp28_;
	GtkToolButton* light_window_item = NULL;
	GtkToolButton* _tmp29_;
	GraniteWidgetsStaticNotebook* staticnotebook = NULL;
	GraniteWidgetsStaticNotebook* _tmp30_;
	GtkLabel* _tmp31_;
	GtkLabel* _tmp32_;
	GtkLabel* _tmp33_;
	GtkWidget* _tmp34_;
	GtkWidget* _tmp35_;
	GtkLabel* _tmp36_;
	GtkLabel* _tmp37_;
	GtkLabel* _tmp38_;
	GtkLabel* _tmp39_;
	GtkLabel* _tmp40_;
	GtkLabel* _tmp41_;
	GraniteDemoSourceListItem* static_notebook_item = NULL;
	GraniteDemoSourceListItem* _tmp42_;
	gint _tmp43_;
	GraniteWidgetsModeButton* _tmp44_;
	GraniteWidgetsModeButton* _tmp45_;
	GraniteWidgetsModeButton* _tmp46_;
	gint normal_mode_index = 0;
	GraniteWidgetsModeButton* _tmp47_;
	GtkLabel* _tmp48_;
	GtkLabel* _tmp49_;
	gint _tmp50_;
	gint _tmp51_;
	GraniteWidgetsModeButton* _tmp52_;
	GtkLabel* _tmp53_;
	GtkLabel* _tmp54_;
	gint _tmp55_;
	GraniteWidgetsModeButton* _tmp56_;
	GraniteWidgetsModeButton* _tmp57_;
	GtkToolItem* mode_button_item = NULL;
	GtkToolItem* _tmp58_;
	GraniteWidgetsModeButton* _tmp59_;
	GtkButton* _tmp60_;
	GtkImage* _tmp61_;
	GtkImage* _tmp62_;
	GtkToolItem* calendar_tool_item = NULL;
	GtkToolItem* _tmp63_;
	GraniteWidgetsDatePicker* date_button = NULL;
	GraniteWidgetsDatePicker* _tmp64_;
	GtkToolItem* time_tool_item = NULL;
	GtkToolItem* _tmp65_;
	GraniteWidgetsTimePicker* time_button = NULL;
	GraniteWidgetsTimePicker* _tmp66_;
	GraniteWidgetsDynamicNotebook* dynamic_notebook = NULL;
	GraniteWidgetsDynamicNotebook* _tmp67_;
	GraniteDemoSourceListItem* dynamic_notebook_item = NULL;
	GraniteDemoSourceListItem* _tmp68_;
	gint _tmp69_;
	GtkSeparatorToolItem* right_sep = NULL;
	GtkSeparatorToolItem* _tmp70_;
	GraniteWidgetsSearchBar* search_entry = NULL;
	GraniteWidgetsSearchBar* _tmp71_;
	GtkToolItem* search_item = NULL;
	GtkToolItem* _tmp72_;
	GraniteWidgetsAppMenu* main_menu = NULL;
	GtkMenu* _tmp73_;
	GtkMenu* _tmp74_;
	GraniteWidgetsAppMenu* _tmp75_;
	GraniteWidgetsAppMenu* _tmp76_;
	self = (GraniteDemo*) base;
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	_data1_->self = g_object_ref (self);
	_tmp0_ = (GtkWindow*) gtk_window_new (GTK_WINDOW_TOPLEVEL);
	g_object_ref_sink (_tmp0_);
	_data1_->window = _tmp0_;
	gtk_window_set_title (_data1_->window, "Granite Demo");
	g_object_set (_data1_->window, "window-position", GTK_WIN_POS_CENTER, NULL);
	gtk_application_add_window ((GtkApplication*) self, _data1_->window);
	_tmp1_ = (GtkToolbar*) gtk_toolbar_new ();
	g_object_ref_sink (_tmp1_);
	main_toolbar = _tmp1_;
	_tmp2_ = gtk_widget_get_style_context ((GtkWidget*) main_toolbar);
	gtk_style_context_add_class (_tmp2_, GTK_STYLE_CLASS_PRIMARY_TOOLBAR);
	gtk_widget_set_hexpand ((GtkWidget*) main_toolbar, TRUE);
	gtk_widget_set_vexpand ((GtkWidget*) main_toolbar, FALSE);
	_tmp3_ = granite_widgets_source_list_expandable_item_new ("");
	_tmp4_ = _tmp3_;
	_tmp5_ = granite_widgets_source_list_new (_tmp4_);
	g_object_ref_sink (_tmp5_);
	_tmp6_ = _tmp5_;
	_g_object_unref0 (_tmp4_);
	sidebar = _tmp6_;
	g_object_set ((GtkWidget*) sidebar, "width-request", 200, NULL);
	_tmp7_ = (GtkNotebook*) gtk_notebook_new ();
	g_object_ref_sink (_tmp7_);
	_data1_->page_switcher = _tmp7_;
	gtk_notebook_set_show_tabs (_data1_->page_switcher, FALSE);
	gtk_notebook_set_show_border (_data1_->page_switcher, FALSE);
	g_object_set ((GtkWidget*) _data1_->page_switcher, "expand", TRUE, NULL);
	g_signal_connect_data (sidebar, "item-selected", (GCallback) ___lambda4__granite_widgets_source_list_item_selected, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	_tmp8_ = granite_demo_source_list_expandable_item_new ("Widgets");
	widgets_category = _tmp8_;
	_tmp9_ = granite_demo_source_list_expandable_item_new ("Services");
	services_category = _tmp9_;
	_tmp10_ = granite_widgets_source_list_get_root (sidebar);
	_tmp11_ = _tmp10_;
	granite_widgets_source_list_expandable_item_add (_tmp11_, (GraniteWidgetsSourceListItem*) widgets_category);
	_tmp12_ = granite_widgets_source_list_get_root (sidebar);
	_tmp13_ = _tmp12_;
	granite_widgets_source_list_expandable_item_add (_tmp13_, (GraniteWidgetsSourceListItem*) services_category);
	_tmp14_ = granite_widgets_source_list_get_root (sidebar);
	_tmp15_ = _tmp14_;
	granite_widgets_source_list_expandable_item_expand_all (_tmp15_, TRUE, TRUE);
	_tmp16_ = granite_widgets_thin_paned_new (GTK_ORIENTATION_HORIZONTAL);
	g_object_ref_sink (_tmp16_);
	sidebar_paned = _tmp16_;
	gtk_paned_pack1 ((GtkPaned*) sidebar_paned, (GtkWidget*) sidebar, TRUE, FALSE);
	gtk_paned_pack2 ((GtkPaned*) sidebar_paned, (GtkWidget*) _data1_->page_switcher, TRUE, FALSE);
	g_object_set ((GtkWidget*) sidebar_paned, "expand", TRUE, NULL);
	_tmp17_ = granite_widgets_status_bar_new ();
	g_object_ref_sink (_tmp17_);
	statusbar = _tmp17_;
	granite_widgets_status_bar_set_text (statusbar, "Granite.Widgets.StatusBar");
	gtk_widget_set_hexpand ((GtkWidget*) statusbar, TRUE);
	gtk_widget_set_vexpand ((GtkWidget*) statusbar, FALSE);
	_tmp18_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp18_);
	_g_object_unref0 (self->priv->main_layout);
	self->priv->main_layout = _tmp18_;
	_tmp19_ = self->priv->main_layout;
	g_object_set ((GtkWidget*) _tmp19_, "expand", TRUE, NULL);
	_tmp20_ = self->priv->main_layout;
	gtk_orientable_set_orientation ((GtkOrientable*) _tmp20_, GTK_ORIENTATION_VERTICAL);
	_tmp21_ = self->priv->main_layout;
	gtk_container_add ((GtkContainer*) _tmp21_, (GtkWidget*) main_toolbar);
	_tmp22_ = self->priv->main_layout;
	gtk_container_add ((GtkContainer*) _tmp22_, (GtkWidget*) sidebar_paned);
	_tmp23_ = self->priv->main_layout;
	gtk_container_add ((GtkContainer*) _tmp23_, (GtkWidget*) statusbar);
	_tmp24_ = self->priv->main_layout;
	gtk_container_add ((GtkContainer*) _data1_->window, (GtkWidget*) _tmp24_);
	_tmp25_ = granite_demo_create_welcome_screen (self);
	welcome_screen = _tmp25_;
	_tmp26_ = granite_demo_source_list_item_new ("Welcome");
	welcome_item = _tmp26_;
	granite_widgets_source_list_expandable_item_add ((GraniteWidgetsSourceListExpandableItem*) widgets_category, (GraniteWidgetsSourceListItem*) welcome_item);
	_tmp27_ = gtk_notebook_append_page (_data1_->page_switcher, (GtkWidget*) welcome_screen, NULL);
	granite_demo_source_list_item_set_page_num (welcome_item, _tmp27_);
	granite_widgets_source_list_set_selected (sidebar, (GraniteWidgetsSourceListItem*) welcome_item);
	_tmp28_ = (GtkImage*) gtk_image_new_from_icon_name ("document-new", GTK_ICON_SIZE_LARGE_TOOLBAR);
	g_object_ref_sink (_tmp28_);
	light_window_icon = _tmp28_;
	_tmp29_ = (GtkToolButton*) gtk_tool_button_new ((GtkWidget*) light_window_icon, "Show LightWindow");
	g_object_ref_sink (_tmp29_);
	light_window_item = _tmp29_;
	gtk_tool_button_set_icon_name (light_window_item, "document-new");
	gtk_widget_set_tooltip_text ((GtkWidget*) light_window_item, "Show Light Window");
	gtk_widget_set_valign ((GtkWidget*) light_window_item, GTK_ALIGN_CENTER);
	gtk_widget_set_halign ((GtkWidget*) light_window_item, GTK_ALIGN_CENTER);
	g_signal_connect_object (light_window_item, "clicked", (GCallback) _granite_demo_show_light_window_gtk_tool_button_clicked, self, 0);
	gtk_toolbar_insert (main_toolbar, (GtkToolItem*) light_window_item, -1);
	_tmp30_ = granite_widgets_static_notebook_new (TRUE);
	g_object_ref_sink (_tmp30_);
	staticnotebook = _tmp30_;
	_tmp31_ = (GtkLabel*) gtk_label_new ("Page 1");
	g_object_ref_sink (_tmp31_);
	_data1_->pageone = _tmp31_;
	_tmp32_ = (GtkLabel*) gtk_label_new ("Page 1");
	g_object_ref_sink (_tmp32_);
	_tmp33_ = _tmp32_;
	granite_widgets_static_notebook_append_page (staticnotebook, (GtkWidget*) _tmp33_, _data1_->pageone);
	_g_object_unref0 (_tmp33_);
	_tmp34_ = granite_demo_get_overlay_bar_widget (self);
	_tmp35_ = _tmp34_;
	_tmp36_ = (GtkLabel*) gtk_label_new ("Overlay Bar");
	g_object_ref_sink (_tmp36_);
	_tmp37_ = _tmp36_;
	granite_widgets_static_notebook_append_page (staticnotebook, _tmp35_, _tmp37_);
	_g_object_unref0 (_tmp37_);
	_g_object_unref0 (_tmp35_);
	_tmp38_ = (GtkLabel*) gtk_label_new ("Page 3");
	g_object_ref_sink (_tmp38_);
	_tmp39_ = _tmp38_;
	_tmp40_ = (GtkLabel*) gtk_label_new ("Page 3");
	g_object_ref_sink (_tmp40_);
	_tmp41_ = _tmp40_;
	granite_widgets_static_notebook_append_page (staticnotebook, (GtkWidget*) _tmp39_, _tmp41_);
	_g_object_unref0 (_tmp41_);
	_g_object_unref0 (_tmp39_);
	g_signal_connect_data (staticnotebook, "page-changed", (GCallback) ___lambda5__granite_widgets_static_notebook_page_changed, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	_tmp42_ = granite_demo_source_list_item_new ("StaticNotebook");
	static_notebook_item = _tmp42_;
	_tmp43_ = gtk_notebook_append_page (_data1_->page_switcher, (GtkWidget*) staticnotebook, NULL);
	granite_demo_source_list_item_set_page_num (static_notebook_item, _tmp43_);
	granite_widgets_source_list_expandable_item_add ((GraniteWidgetsSourceListExpandableItem*) widgets_category, (GraniteWidgetsSourceListItem*) static_notebook_item);
	_tmp44_ = granite_widgets_mode_button_new ();
	g_object_ref_sink (_tmp44_);
	_g_object_unref0 (self->priv->mode_button);
	self->priv->mode_button = _tmp44_;
	_tmp45_ = self->priv->mode_button;
	gtk_widget_set_valign ((GtkWidget*) _tmp45_, GTK_ALIGN_CENTER);
	_tmp46_ = self->priv->mode_button;
	gtk_widget_set_halign ((GtkWidget*) _tmp46_, GTK_ALIGN_CENTER);
	_tmp47_ = self->priv->mode_button;
	_tmp48_ = (GtkLabel*) gtk_label_new ("Light");
	g_object_ref_sink (_tmp48_);
	_tmp49_ = _tmp48_;
	_tmp50_ = granite_widgets_mode_button_append (_tmp47_, (GtkWidget*) _tmp49_);
	_tmp51_ = _tmp50_;
	_g_object_unref0 (_tmp49_);
	normal_mode_index = _tmp51_;
	_tmp52_ = self->priv->mode_button;
	_tmp53_ = (GtkLabel*) gtk_label_new ("Dark");
	g_object_ref_sink (_tmp53_);
	_tmp54_ = _tmp53_;
	_tmp55_ = granite_widgets_mode_button_append (_tmp52_, (GtkWidget*) _tmp54_);
	self->priv->dark_mode_index = _tmp55_;
	_g_object_unref0 (_tmp54_);
	_tmp56_ = self->priv->mode_button;
	granite_widgets_mode_button_set_selected (_tmp56_, normal_mode_index);
	granite_demo_on_theme_mode_button_changed (self);
	_tmp57_ = self->priv->mode_button;
	g_signal_connect_object (_tmp57_, "mode-changed", (GCallback) _granite_demo_on_theme_mode_button_changed_granite_widgets_mode_button_mode_changed, self, 0);
	_tmp58_ = gtk_tool_item_new ();
	g_object_ref_sink (_tmp58_);
	mode_button_item = _tmp58_;
	_tmp59_ = self->priv->mode_button;
	gtk_container_add ((GtkContainer*) mode_button_item, (GtkWidget*) _tmp59_);
	gtk_toolbar_insert (main_toolbar, mode_button_item, -1);
	gtk_widget_set_valign ((GtkWidget*) mode_button_item, GTK_ALIGN_CENTER);
	gtk_widget_set_halign ((GtkWidget*) mode_button_item, GTK_ALIGN_CENTER);
	_tmp60_ = (GtkButton*) gtk_button_new ();
	g_object_ref_sink (_tmp60_);
	_data1_->popover_statusbar_item = _tmp60_;
	gtk_button_set_relief (_data1_->popover_statusbar_item, GTK_RELIEF_NONE);
	gtk_widget_set_tooltip_text ((GtkWidget*) _data1_->popover_statusbar_item, "Show PopOver");
	_tmp61_ = (GtkImage*) gtk_image_new_from_icon_name ("help-info-symbolic", GTK_ICON_SIZE_MENU);
	g_object_ref_sink (_tmp61_);
	_tmp62_ = _tmp61_;
	gtk_container_add ((GtkContainer*) _data1_->popover_statusbar_item, (GtkWidget*) _tmp62_);
	_g_object_unref0 (_tmp62_);
	granite_widgets_status_bar_insert_widget (statusbar, (GtkWidget*) _data1_->popover_statusbar_item, FALSE);
	g_signal_connect_data (_data1_->popover_statusbar_item, "clicked", (GCallback) ___lambda6__gtk_button_clicked, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	_tmp63_ = gtk_tool_item_new ();
	g_object_ref_sink (_tmp63_);
	calendar_tool_item = _tmp63_;
	gtk_widget_set_margin_left ((GtkWidget*) calendar_tool_item, 12);
	_tmp64_ = granite_widgets_date_picker_new_with_format ("%d-%m-%y");
	g_object_ref_sink (_tmp64_);
	date_button = _tmp64_;
	gtk_container_add ((GtkContainer*) calendar_tool_item, (GtkWidget*) date_button);
	gtk_toolbar_insert (main_toolbar, calendar_tool_item, -1);
	_tmp65_ = gtk_tool_item_new ();
	g_object_ref_sink (_tmp65_);
	time_tool_item = _tmp65_;
	gtk_widget_set_margin_left ((GtkWidget*) time_tool_item, 12);
	gtk_widget_set_valign ((GtkWidget*) time_tool_item, GTK_ALIGN_CENTER);
	_tmp66_ = granite_widgets_time_picker_new ();
	g_object_ref_sink (_tmp66_);
	time_button = _tmp66_;
	gtk_container_add ((GtkContainer*) time_tool_item, (GtkWidget*) time_button);
	gtk_toolbar_insert (main_toolbar, time_tool_item, -1);
	_tmp67_ = granite_demo_create_dynamic_notebook (self);
	dynamic_notebook = _tmp67_;
	_tmp68_ = granite_demo_source_list_item_new ("DynamicNotebook");
	dynamic_notebook_item = _tmp68_;
	granite_widgets_source_list_expandable_item_add ((GraniteWidgetsSourceListExpandableItem*) widgets_category, (GraniteWidgetsSourceListItem*) dynamic_notebook_item);
	_tmp69_ = gtk_notebook_append_page (_data1_->page_switcher, (GtkWidget*) dynamic_notebook, NULL);
	granite_demo_source_list_item_set_page_num (dynamic_notebook_item, _tmp69_);
	_tmp70_ = (GtkSeparatorToolItem*) gtk_separator_tool_item_new ();
	g_object_ref_sink (_tmp70_);
	right_sep = _tmp70_;
	gtk_separator_tool_item_set_draw (right_sep, FALSE);
	gtk_tool_item_set_expand ((GtkToolItem*) right_sep, TRUE);
	gtk_toolbar_insert (main_toolbar, (GtkToolItem*) right_sep, -1);
	_tmp71_ = granite_widgets_search_bar_new ("Search");
	g_object_ref_sink (_tmp71_);
	search_entry = _tmp71_;
	_tmp72_ = gtk_tool_item_new ();
	g_object_ref_sink (_tmp72_);
	search_item = _tmp72_;
	gtk_container_add ((GtkContainer*) search_item, (GtkWidget*) search_entry);
	gtk_widget_set_margin_left ((GtkWidget*) search_item, 12);
	gtk_toolbar_insert (main_toolbar, search_item, -1);
	_tmp73_ = (GtkMenu*) gtk_menu_new ();
	g_object_ref_sink (_tmp73_);
	_tmp74_ = _tmp73_;
	_tmp75_ = granite_application_create_appmenu ((GraniteApplication*) self, _tmp74_);
	_tmp76_ = _tmp75_;
	_g_object_unref0 (_tmp74_);
	main_menu = _tmp76_;
	gtk_widget_set_margin_left ((GtkWidget*) main_menu, 12);
	gtk_toolbar_insert (main_toolbar, (GtkToolItem*) main_menu, -1);
	gtk_window_set_default_size (_data1_->window, 800, 550);
	gtk_widget_show_all ((GtkWidget*) _data1_->window);
	_g_object_unref0 (main_menu);
	_g_object_unref0 (search_item);
	_g_object_unref0 (search_entry);
	_g_object_unref0 (right_sep);
	_g_object_unref0 (dynamic_notebook_item);
	_g_object_unref0 (dynamic_notebook);
	_g_object_unref0 (time_button);
	_g_object_unref0 (time_tool_item);
	_g_object_unref0 (date_button);
	_g_object_unref0 (calendar_tool_item);
	_g_object_unref0 (mode_button_item);
	_g_object_unref0 (static_notebook_item);
	_g_object_unref0 (staticnotebook);
	_g_object_unref0 (light_window_item);
	_g_object_unref0 (light_window_icon);
	_g_object_unref0 (welcome_item);
	_g_object_unref0 (welcome_screen);
	_g_object_unref0 (statusbar);
	_g_object_unref0 (sidebar_paned);
	_g_object_unref0 (services_category);
	_g_object_unref0 (widgets_category);
	_g_object_unref0 (sidebar);
	_g_object_unref0 (main_toolbar);
	block1_data_unref (_data1_);
	_data1_ = NULL;
}


static void granite_demo_on_theme_mode_button_changed (GraniteDemo* self) {
	GtkSettings* settings = NULL;
	GtkSettings* _tmp0_;
	GtkSettings* _tmp1_;
	GraniteWidgetsModeButton* _tmp2_;
	gint _tmp3_;
	gint _tmp4_;
	gint _tmp5_;
	g_return_if_fail (self != NULL);
	_tmp0_ = gtk_settings_get_default ();
	_tmp1_ = _g_object_ref0 (_tmp0_);
	settings = _tmp1_;
	_tmp2_ = self->priv->mode_button;
	_tmp3_ = granite_widgets_mode_button_get_selected (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = self->priv->dark_mode_index;
	g_object_set (settings, "gtk-application-prefer-dark-theme", _tmp4_ == _tmp5_, NULL);
	_g_object_unref0 (settings);
}


static GraniteWidgetsWelcome* granite_demo_create_welcome_screen (GraniteDemo* self) {
	GraniteWidgetsWelcome* result = NULL;
	GraniteWidgetsWelcome* welcome = NULL;
	GraniteWidgetsWelcome* _tmp0_;
	GdkPixbuf* pixbuf = NULL;
	GtkImage* image = NULL;
	GtkImage* _tmp7_;
	GdkPixbuf* _tmp8_;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = granite_widgets_welcome_new ("Granite's Welcome Screen", "This Is Granite's Welcome Widget.");
	g_object_ref_sink (_tmp0_);
	welcome = _tmp0_;
	pixbuf = NULL;
	{
		GdkPixbuf* _tmp1_ = NULL;
		GtkIconTheme* _tmp2_;
		GdkPixbuf* _tmp3_;
		GdkPixbuf* _tmp4_;
		_tmp2_ = gtk_icon_theme_get_default ();
		_tmp3_ = gtk_icon_theme_load_icon (_tmp2_, "document-new", 48, GTK_ICON_LOOKUP_GENERIC_FALLBACK, &_inner_error_);
		_tmp1_ = _tmp3_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			goto __catch0_g_error;
		}
		_tmp4_ = _tmp1_;
		_tmp1_ = NULL;
		_g_object_unref0 (pixbuf);
		pixbuf = _tmp4_;
		_g_object_unref0 (_tmp1_);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp5_;
		const gchar* _tmp6_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp5_ = e;
		_tmp6_ = _tmp5_->message;
		g_warning ("GraniteDemo.vala:322: Could not load icon, %s", _tmp6_);
		_g_error_free0 (e);
	}
	__finally0:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (pixbuf);
		_g_object_unref0 (welcome);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp7_ = (GtkImage*) gtk_image_new_from_icon_name ("document-open", GTK_ICON_SIZE_DIALOG);
	g_object_ref_sink (_tmp7_);
	image = _tmp7_;
	_tmp8_ = pixbuf;
	granite_widgets_welcome_append_with_pixbuf (welcome, _tmp8_, "Create", "Write a new document.");
	granite_widgets_welcome_append_with_image (welcome, image, "Open", "Select a file.");
	granite_widgets_welcome_append (welcome, "document-save", "Save", "With a much longer description.");
	result = welcome;
	_g_object_unref0 (image);
	_g_object_unref0 (pixbuf);
	return result;
}


static void granite_demo_show_light_window (GraniteDemo* self) {
	GraniteWidgetsLightWindow* light_window = NULL;
	GraniteWidgetsLightWindow* _tmp0_;
	GraniteWidgetsStaticNotebook* light_window_notebook = NULL;
	GraniteWidgetsStaticNotebook* _tmp1_;
	GtkEntry* entry = NULL;
	GtkEntry* _tmp2_;
	GtkComboBoxText* open_drop = NULL;
	GtkComboBoxText* _tmp3_;
	GraniteDemoLLabel* open_lbl = NULL;
	GraniteDemoLLabel* _tmp4_;
	GtkGrid* grid = NULL;
	GtkGrid* _tmp5_;
	GtkImage* _tmp6_;
	GtkImage* _tmp7_;
	GraniteDemoLLabel* _tmp8_;
	GraniteDemoLLabel* _tmp9_;
	GtkGrid* general = NULL;
	GtkGrid* _tmp10_;
	GraniteDemoLLabel* _tmp11_;
	GraniteDemoLLabel* _tmp12_;
	GraniteDemoLLabel* _tmp13_;
	GraniteDemoLLabel* _tmp14_;
	GraniteDemoLLabel* _tmp15_;
	GraniteDemoLLabel* _tmp16_;
	GraniteDemoLLabel* _tmp17_;
	GraniteDemoLLabel* _tmp18_;
	GraniteDemoLLabel* _tmp19_;
	GraniteDemoLLabel* _tmp20_;
	GraniteDemoLLabel* _tmp21_;
	GraniteDemoLLabel* _tmp22_;
	GraniteDemoLLabel* _tmp23_;
	GraniteDemoLLabel* _tmp24_;
	GraniteDemoLLabel* _tmp25_;
	GraniteDemoLLabel* _tmp26_;
	GraniteDemoLLabel* _tmp27_;
	GraniteDemoLLabel* _tmp28_;
	GraniteDemoLLabel* _tmp29_;
	GraniteDemoLLabel* _tmp30_;
	GraniteDemoLLabel* _tmp31_;
	GraniteDemoLLabel* _tmp32_;
	GraniteDemoLLabel* _tmp33_;
	GraniteDemoLLabel* _tmp34_;
	GtkLabel* _tmp35_;
	GtkLabel* _tmp36_;
	GtkLabel* _tmp37_;
	GtkLabel* _tmp38_;
	GtkLabel* _tmp39_;
	GtkLabel* _tmp40_;
	GtkLabel* _tmp41_;
	GtkLabel* _tmp42_;
	GtkLabel* _tmp43_;
	GtkLabel* _tmp44_;
	g_return_if_fail (self != NULL);
	_tmp0_ = granite_widgets_light_window_new ("");
	g_object_ref_sink (_tmp0_);
	light_window = _tmp0_;
	_tmp1_ = granite_widgets_static_notebook_new (TRUE);
	g_object_ref_sink (_tmp1_);
	light_window_notebook = _tmp1_;
	_tmp2_ = (GtkEntry*) gtk_entry_new ();
	g_object_ref_sink (_tmp2_);
	entry = _tmp2_;
	_tmp3_ = (GtkComboBoxText*) gtk_combo_box_text_new ();
	g_object_ref_sink (_tmp3_);
	open_drop = _tmp3_;
	_tmp4_ = granite_demo_llabel_new ("Alwas Open Mpeg Video Files with Audience");
	g_object_ref_sink (_tmp4_);
	open_lbl = _tmp4_;
	_tmp5_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp5_);
	grid = _tmp5_;
	_tmp6_ = (GtkImage*) gtk_image_new_from_icon_name ("video-x-generic", GTK_ICON_SIZE_DIALOG);
	g_object_ref_sink (_tmp6_);
	_tmp7_ = _tmp6_;
	gtk_grid_attach (grid, (GtkWidget*) _tmp7_, 0, 0, 1, 2);
	_g_object_unref0 (_tmp7_);
	gtk_grid_attach (grid, (GtkWidget*) entry, 1, 0, 1, 1);
	_tmp8_ = granite_demo_llabel_new ("1.13 GB, Mpeg Video File");
	g_object_ref_sink (_tmp8_);
	_tmp9_ = _tmp8_;
	gtk_grid_attach (grid, (GtkWidget*) _tmp9_, 1, 1, 1, 1);
	_g_object_unref0 (_tmp9_);
	gtk_grid_attach (grid, (GtkWidget*) light_window_notebook, 0, 2, 2, 1);
	_tmp10_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp10_);
	general = _tmp10_;
	_tmp11_ = granite_demo_llabel_new_markup ("<b>Info:</b>");
	g_object_ref_sink (_tmp11_);
	_tmp12_ = _tmp11_;
	gtk_grid_attach (general, (GtkWidget*) _tmp12_, 0, 0, 2, 1);
	_g_object_unref0 (_tmp12_);
	_tmp13_ = granite_demo_llabel_new_right ("Created:");
	g_object_ref_sink (_tmp13_);
	_tmp14_ = _tmp13_;
	gtk_grid_attach (general, (GtkWidget*) _tmp14_, 0, 1, 1, 1);
	_g_object_unref0 (_tmp14_);
	_tmp15_ = granite_demo_llabel_new_right ("Modified:");
	g_object_ref_sink (_tmp15_);
	_tmp16_ = _tmp15_;
	gtk_grid_attach (general, (GtkWidget*) _tmp16_, 0, 2, 1, 1);
	_g_object_unref0 (_tmp16_);
	_tmp17_ = granite_demo_llabel_new_right ("Opened:");
	g_object_ref_sink (_tmp17_);
	_tmp18_ = _tmp17_;
	gtk_grid_attach (general, (GtkWidget*) _tmp18_, 0, 3, 1, 1);
	_g_object_unref0 (_tmp18_);
	_tmp19_ = granite_demo_llabel_new_right ("Mimetype:");
	g_object_ref_sink (_tmp19_);
	_tmp20_ = _tmp19_;
	gtk_grid_attach (general, (GtkWidget*) _tmp20_, 0, 4, 1, 1);
	_g_object_unref0 (_tmp20_);
	_tmp21_ = granite_demo_llabel_new_right ("Location:");
	g_object_ref_sink (_tmp21_);
	_tmp22_ = _tmp21_;
	gtk_grid_attach (general, (GtkWidget*) _tmp22_, 0, 5, 1, 1);
	_g_object_unref0 (_tmp22_);
	_tmp23_ = granite_demo_llabel_new ("Today at 9:50 PM");
	g_object_ref_sink (_tmp23_);
	_tmp24_ = _tmp23_;
	gtk_grid_attach (general, (GtkWidget*) _tmp24_, 1, 1, 1, 1);
	_g_object_unref0 (_tmp24_);
	_tmp25_ = granite_demo_llabel_new ("Today at 9:50 PM");
	g_object_ref_sink (_tmp25_);
	_tmp26_ = _tmp25_;
	gtk_grid_attach (general, (GtkWidget*) _tmp26_, 1, 2, 1, 1);
	_g_object_unref0 (_tmp26_);
	_tmp27_ = granite_demo_llabel_new ("Today at 10:00 PM");
	g_object_ref_sink (_tmp27_);
	_tmp28_ = _tmp27_;
	gtk_grid_attach (general, (GtkWidget*) _tmp28_, 1, 3, 1, 1);
	_g_object_unref0 (_tmp28_);
	_tmp29_ = granite_demo_llabel_new ("video/mpeg");
	g_object_ref_sink (_tmp29_);
	_tmp30_ = _tmp29_;
	gtk_grid_attach (general, (GtkWidget*) _tmp30_, 1, 4, 1, 1);
	_g_object_unref0 (_tmp30_);
	_tmp31_ = granite_demo_llabel_new ("/home/daniel/Downloads");
	g_object_ref_sink (_tmp31_);
	_tmp32_ = _tmp31_;
	gtk_grid_attach (general, (GtkWidget*) _tmp32_, 1, 5, 1, 1);
	_g_object_unref0 (_tmp32_);
	_tmp33_ = granite_demo_llabel_new_markup ("<b>Open with:</b>");
	g_object_ref_sink (_tmp33_);
	_tmp34_ = _tmp33_;
	gtk_grid_attach (general, (GtkWidget*) _tmp34_, 0, 6, 2, 1);
	_g_object_unref0 (_tmp34_);
	gtk_grid_attach (general, (GtkWidget*) open_drop, 0, 7, 2, 1);
	gtk_grid_attach (general, (GtkWidget*) open_lbl, 0, 8, 2, 1);
	_tmp35_ = (GtkLabel*) gtk_label_new ("General");
	g_object_ref_sink (_tmp35_);
	_tmp36_ = _tmp35_;
	granite_widgets_static_notebook_append_page (light_window_notebook, (GtkWidget*) general, _tmp36_);
	_g_object_unref0 (_tmp36_);
	_tmp37_ = (GtkLabel*) gtk_label_new ("More");
	g_object_ref_sink (_tmp37_);
	_tmp38_ = _tmp37_;
	_tmp39_ = (GtkLabel*) gtk_label_new ("More");
	g_object_ref_sink (_tmp39_);
	_tmp40_ = _tmp39_;
	granite_widgets_static_notebook_append_page (light_window_notebook, (GtkWidget*) _tmp38_, _tmp40_);
	_g_object_unref0 (_tmp40_);
	_g_object_unref0 (_tmp38_);
	_tmp41_ = (GtkLabel*) gtk_label_new ("Sharing");
	g_object_ref_sink (_tmp41_);
	_tmp42_ = _tmp41_;
	_tmp43_ = (GtkLabel*) gtk_label_new ("Sharing");
	g_object_ref_sink (_tmp43_);
	_tmp44_ = _tmp43_;
	granite_widgets_static_notebook_append_page (light_window_notebook, (GtkWidget*) _tmp42_, _tmp44_);
	_g_object_unref0 (_tmp44_);
	_g_object_unref0 (_tmp42_);
	gtk_widget_set_margin_left ((GtkWidget*) open_lbl, 24);
	gtk_widget_set_margin_left ((GtkWidget*) open_drop, 12);
	gtk_combo_box_text_append (open_drop, "audience", "Audience");
	gtk_combo_box_set_active ((GtkComboBox*) open_drop, 0);
	g_object_set ((GtkWidget*) grid, "margin", 12, NULL);
	gtk_widget_set_margin_top ((GtkWidget*) grid, 24);
	gtk_widget_set_margin_bottom ((GtkWidget*) grid, 24);
	gtk_entry_set_text (entry, "Cool Hand Luke");
	gtk_grid_set_column_spacing (general, 6);
	gtk_grid_set_row_spacing (general, 6);
	granite_widgets_decorated_window_add ((GraniteWidgetsDecoratedWindow*) light_window, (GtkWidget*) grid);
	gtk_widget_show_all ((GtkWidget*) light_window);
	_g_object_unref0 (general);
	_g_object_unref0 (grid);
	_g_object_unref0 (open_lbl);
	_g_object_unref0 (open_drop);
	_g_object_unref0 (entry);
	_g_object_unref0 (light_window_notebook);
	_g_object_unref0 (light_window);
}


static Block2Data* block2_data_ref (Block2Data* _data2_) {
	g_atomic_int_inc (&_data2_->_ref_count_);
	return _data2_;
}


static void block2_data_unref (void * _userdata_) {
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
		GraniteDemo* self;
		self = _data2_->self;
		_g_object_unref0 (_data2_->dynamic_notebook);
		_g_object_unref0 (self);
		g_slice_free (Block2Data, _data2_);
	}
}


static void __lambda7_ (Block2Data* _data2_) {
	GraniteDemo* self;
	GraniteWidgetsTab* t = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	GThemedIcon* _tmp4_;
	GThemedIcon* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	GtkLabel* _tmp10_;
	GtkLabel* _tmp11_;
	GraniteWidgetsTab* _tmp12_;
	GraniteWidgetsTab* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gint _tmp16_;
	self = _data2_->self;
	_tmp0_ = g_strdup_printf ("%i", _data2_->i);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_strconcat ("user", _tmp1_, "@elementaryos: ~", NULL);
	_tmp3_ = _tmp2_;
	_tmp4_ = (GThemedIcon*) g_themed_icon_new ("empty");
	_tmp5_ = _tmp4_;
	_tmp6_ = g_strdup_printf ("%i", _data2_->i);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_strconcat ("Page ", _tmp7_, NULL);
	_tmp9_ = _tmp8_;
	_tmp10_ = (GtkLabel*) gtk_label_new (_tmp9_);
	g_object_ref_sink (_tmp10_);
	_tmp11_ = _tmp10_;
	_tmp12_ = granite_widgets_tab_new (_tmp3_, (GIcon*) _tmp5_, (GtkWidget*) _tmp11_);
	g_object_ref_sink (_tmp12_);
	_tmp13_ = _tmp12_;
	_g_object_unref0 (_tmp11_);
	_g_free0 (_tmp9_);
	_g_free0 (_tmp7_);
	_g_object_unref0 (_tmp5_);
	_g_free0 (_tmp3_);
	_g_free0 (_tmp1_);
	t = _tmp13_;
	_tmp14_ = g_strdup_printf ("%i", _data2_->i);
	_tmp15_ = _tmp14_;
	granite_widgets_tab_set_restore_data (t, _tmp15_);
	_g_free0 (_tmp15_);
	_tmp16_ = _data2_->i;
	_data2_->i = _tmp16_ + 1;
	granite_widgets_dynamic_notebook_insert_tab (_data2_->dynamic_notebook, t, -1);
	_g_object_unref0 (t);
}


static void ___lambda7__granite_widgets_dynamic_notebook_new_tab_requested (GraniteWidgetsDynamicNotebook* _sender, gpointer self) {
	__lambda7_ (self);
}


static void __lambda8_ (Block2Data* _data2_, const gchar* label, const gchar* data, GIcon* icon) {
	GraniteDemo* self;
	GraniteWidgetsTab* t = NULL;
	const gchar* _tmp0_;
	GIcon* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	GtkLabel* _tmp5_;
	GtkLabel* _tmp6_;
	GraniteWidgetsTab* _tmp7_;
	GraniteWidgetsTab* _tmp8_;
	const gchar* _tmp9_;
	const gchar* _tmp10_;
	self = _data2_->self;
	g_return_if_fail (label != NULL);
	g_return_if_fail (data != NULL);
	_tmp0_ = label;
	_tmp1_ = icon;
	_tmp2_ = data;
	_tmp3_ = g_strconcat ("Page ", _tmp2_, NULL);
	_tmp4_ = _tmp3_;
	_tmp5_ = (GtkLabel*) gtk_label_new (_tmp4_);
	g_object_ref_sink (_tmp5_);
	_tmp6_ = _tmp5_;
	_tmp7_ = granite_widgets_tab_new (_tmp0_, _tmp1_, (GtkWidget*) _tmp6_);
	g_object_ref_sink (_tmp7_);
	_tmp8_ = _tmp7_;
	_g_object_unref0 (_tmp6_);
	_g_free0 (_tmp4_);
	t = _tmp8_;
	_tmp9_ = data;
	granite_widgets_tab_set_restore_data (t, _tmp9_);
	granite_widgets_dynamic_notebook_insert_tab (_data2_->dynamic_notebook, t, -1);
	_tmp10_ = label;
	g_print ("Restored tab %s\n", _tmp10_);
	_g_object_unref0 (t);
}


static void ___lambda8__granite_widgets_dynamic_notebook_tab_restored (GraniteWidgetsDynamicNotebook* _sender, const gchar* label, const gchar* data, GIcon* icon, gpointer self) {
	__lambda8_ (self, label, data, icon);
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


static void __lambda9_ (Block2Data* _data2_, GraniteWidgetsTab* t) {
	GraniteDemo* self;
	gchar* num = NULL;
	GraniteWidgetsTab* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	GraniteWidgetsTab* t2 = NULL;
	const gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	GThemedIcon* _tmp7_;
	GThemedIcon* _tmp8_;
	const gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	GtkLabel* _tmp12_;
	GtkLabel* _tmp13_;
	GraniteWidgetsTab* _tmp14_;
	GraniteWidgetsTab* _tmp15_;
	GraniteWidgetsTab* _tmp16_;
	const gchar* _tmp17_;
	const gchar* _tmp18_;
	const gchar* _tmp19_;
	const gchar* _tmp20_;
	self = _data2_->self;
	g_return_if_fail (t != NULL);
	_tmp0_ = t;
	_tmp1_ = granite_widgets_tab_get_restore_data (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strdup (_tmp2_);
	num = _tmp3_;
	_tmp4_ = string_to_string (num);
	_tmp5_ = g_strconcat ("user", _tmp4_, "@elementaryos: ~", NULL);
	_tmp6_ = _tmp5_;
	_tmp7_ = (GThemedIcon*) g_themed_icon_new ("empty");
	_tmp8_ = _tmp7_;
	_tmp9_ = string_to_string (num);
	_tmp10_ = g_strconcat ("Page ", _tmp9_, NULL);
	_tmp11_ = _tmp10_;
	_tmp12_ = (GtkLabel*) gtk_label_new (_tmp11_);
	g_object_ref_sink (_tmp12_);
	_tmp13_ = _tmp12_;
	_tmp14_ = granite_widgets_tab_new (_tmp6_, (GIcon*) _tmp8_, (GtkWidget*) _tmp13_);
	g_object_ref_sink (_tmp14_);
	_tmp15_ = _tmp14_;
	_g_object_unref0 (_tmp13_);
	_g_free0 (_tmp11_);
	_g_object_unref0 (_tmp8_);
	_g_free0 (_tmp6_);
	t2 = _tmp15_;
	_tmp16_ = t;
	_tmp17_ = granite_widgets_tab_get_restore_data (_tmp16_);
	_tmp18_ = _tmp17_;
	granite_widgets_tab_set_restore_data (t2, _tmp18_);
	granite_widgets_dynamic_notebook_insert_tab (_data2_->dynamic_notebook, t2, -1);
	_tmp19_ = granite_widgets_tab_get_label (t2);
	_tmp20_ = _tmp19_;
	g_print ("Duplicated tab %s\n", _tmp20_);
	_g_object_unref0 (t2);
	_g_free0 (num);
}


static void ___lambda9__granite_widgets_dynamic_notebook_tab_duplicated (GraniteWidgetsDynamicNotebook* _sender, GraniteWidgetsTab* duplicated_tab, gpointer self) {
	__lambda9_ (self, duplicated_tab);
}


static void __lambda10_ (GraniteDemo* self, GraniteWidgetsTab* t, gint p) {
	GraniteWidgetsTab* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	gint _tmp3_;
	g_return_if_fail (t != NULL);
	_tmp0_ = t;
	_tmp1_ = granite_widgets_tab_get_label (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = p;
	g_print ("Moved tab %s to %i\n", _tmp2_, _tmp3_);
}


static void ___lambda10__granite_widgets_dynamic_notebook_tab_moved (GraniteWidgetsDynamicNotebook* _sender, GraniteWidgetsTab* tab, gint x, gint y, gpointer self) {
	__lambda10_ ((GraniteDemo*) self, tab, x);
}


static void __lambda11_ (GraniteDemo* self, GraniteWidgetsTab* old_t, GraniteWidgetsTab* new_t) {
	GraniteWidgetsTab* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	GraniteWidgetsTab* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	g_return_if_fail (new_t != NULL);
	_tmp0_ = old_t;
	_tmp1_ = granite_widgets_tab_get_label (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = new_t;
	_tmp4_ = granite_widgets_tab_get_label (_tmp3_);
	_tmp5_ = _tmp4_;
	g_print ("Switched from %s to %s\n", _tmp2_, _tmp5_);
}


static void ___lambda11__granite_widgets_dynamic_notebook_tab_switched (GraniteWidgetsDynamicNotebook* _sender, GraniteWidgetsTab* old_tab, GraniteWidgetsTab* new_tab, gpointer self) {
	__lambda11_ ((GraniteDemo*) self, old_tab, new_tab);
}


static void __lambda12_ (GraniteDemo* self, GraniteWidgetsTab* t) {
	GraniteWidgetsTab* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	g_return_if_fail (t != NULL);
	_tmp0_ = t;
	_tmp1_ = granite_widgets_tab_get_label (_tmp0_);
	_tmp2_ = _tmp1_;
	g_print ("Removed tab %s\n", _tmp2_);
}


static void ___lambda12__granite_widgets_dynamic_notebook_tab_removed (GraniteWidgetsDynamicNotebook* _sender, GraniteWidgetsTab* tab, gpointer self) {
	__lambda12_ ((GraniteDemo*) self, tab);
}


static GraniteWidgetsDynamicNotebook* granite_demo_create_dynamic_notebook (GraniteDemo* self) {
	GraniteWidgetsDynamicNotebook* result = NULL;
	Block2Data* _data2_;
	GraniteWidgetsDynamicNotebook* _tmp0_;
	GraniteWidgetsTab* tab = NULL;
	GThemedIcon* _tmp1_;
	GThemedIcon* _tmp2_;
	GtkLabel* _tmp3_;
	GtkLabel* _tmp4_;
	GraniteWidgetsTab* _tmp5_;
	GraniteWidgetsTab* _tmp6_;
	GraniteWidgetsTab* tab2 = NULL;
	GThemedIcon* _tmp7_;
	GThemedIcon* _tmp8_;
	GtkLabel* _tmp9_;
	GtkLabel* _tmp10_;
	GraniteWidgetsTab* _tmp11_;
	GraniteWidgetsTab* _tmp12_;
	GraniteWidgetsDynamicNotebook* _tmp13_;
	g_return_val_if_fail (self != NULL, NULL);
	_data2_ = g_slice_new0 (Block2Data);
	_data2_->_ref_count_ = 1;
	_data2_->self = g_object_ref (self);
	_data2_->i = 3;
	_tmp0_ = granite_widgets_dynamic_notebook_new ();
	g_object_ref_sink (_tmp0_);
	_data2_->dynamic_notebook = _tmp0_;
	granite_widgets_dynamic_notebook_set_allow_duplication (_data2_->dynamic_notebook, TRUE);
	granite_widgets_dynamic_notebook_set_allow_restoring (_data2_->dynamic_notebook, TRUE);
	granite_widgets_dynamic_notebook_set_max_restorable_tabs (_data2_->dynamic_notebook, 5);
	granite_widgets_dynamic_notebook_set_allow_pinning (_data2_->dynamic_notebook, TRUE);
	granite_widgets_dynamic_notebook_set_show_icons (_data2_->dynamic_notebook, TRUE);
	granite_widgets_dynamic_notebook_set_add_button_tooltip (_data2_->dynamic_notebook, "New user tab");
	_tmp1_ = (GThemedIcon*) g_themed_icon_new ("empty");
	_tmp2_ = _tmp1_;
	_tmp3_ = (GtkLabel*) gtk_label_new ("Page 1");
	g_object_ref_sink (_tmp3_);
	_tmp4_ = _tmp3_;
	_tmp5_ = granite_widgets_tab_new ("user1@elementaryos: ~", (GIcon*) _tmp2_, (GtkWidget*) _tmp4_);
	g_object_ref_sink (_tmp5_);
	_tmp6_ = _tmp5_;
	_g_object_unref0 (_tmp4_);
	_g_object_unref0 (_tmp2_);
	tab = _tmp6_;
	granite_widgets_tab_set_restore_data (tab, "1");
	granite_widgets_tab_set_working (tab, TRUE);
	granite_widgets_dynamic_notebook_insert_tab (_data2_->dynamic_notebook, tab, -1);
	_tmp7_ = (GThemedIcon*) g_themed_icon_new ("empty");
	_tmp8_ = _tmp7_;
	_tmp9_ = (GtkLabel*) gtk_label_new ("Page 2");
	g_object_ref_sink (_tmp9_);
	_tmp10_ = _tmp9_;
	_tmp11_ = granite_widgets_tab_new ("user2@elementaryos: ~", (GIcon*) _tmp8_, (GtkWidget*) _tmp10_);
	g_object_ref_sink (_tmp11_);
	_tmp12_ = _tmp11_;
	_g_object_unref0 (_tmp10_);
	_g_object_unref0 (_tmp8_);
	tab2 = _tmp12_;
	granite_widgets_tab_set_restore_data (tab2, "2");
	granite_widgets_dynamic_notebook_insert_tab (_data2_->dynamic_notebook, tab2, -1);
	g_signal_connect_data (_data2_->dynamic_notebook, "new-tab-requested", (GCallback) ___lambda7__granite_widgets_dynamic_notebook_new_tab_requested, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
	g_signal_connect_data (_data2_->dynamic_notebook, "tab-restored", (GCallback) ___lambda8__granite_widgets_dynamic_notebook_tab_restored, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
	g_signal_connect_data (_data2_->dynamic_notebook, "tab-duplicated", (GCallback) ___lambda9__granite_widgets_dynamic_notebook_tab_duplicated, block2_data_ref (_data2_), (GClosureNotify) block2_data_unref, 0);
	g_signal_connect_object (_data2_->dynamic_notebook, "tab-moved", (GCallback) ___lambda10__granite_widgets_dynamic_notebook_tab_moved, self, 0);
	g_signal_connect_object (_data2_->dynamic_notebook, "tab-switched", (GCallback) ___lambda11__granite_widgets_dynamic_notebook_tab_switched, self, 0);
	g_signal_connect_object (_data2_->dynamic_notebook, "tab-removed", (GCallback) ___lambda12__granite_widgets_dynamic_notebook_tab_removed, self, 0);
	_tmp13_ = _g_object_ref0 (_data2_->dynamic_notebook);
	result = _tmp13_;
	_g_object_unref0 (tab2);
	_g_object_unref0 (tab);
	block2_data_unref (_data2_);
	_data2_ = NULL;
	return result;
}


static GtkWidget* granite_demo_get_overlay_bar_widget (GraniteDemo* self) {
	GtkWidget* result = NULL;
	GtkOverlay* overlay = NULL;
	GtkOverlay* _tmp0_;
	GtkLabel* _tmp1_;
	GtkLabel* _tmp2_;
	GraniteWidgetsOverlayBar* overlay_bar = NULL;
	GraniteWidgetsOverlayBar* _tmp3_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = (GtkOverlay*) gtk_overlay_new ();
	g_object_ref_sink (_tmp0_);
	overlay = _tmp0_;
	_tmp1_ = (GtkLabel*) gtk_label_new ("Try to touch the Overlay Bar!");
	g_object_ref_sink (_tmp1_);
	_tmp2_ = _tmp1_;
	gtk_container_add ((GtkContainer*) overlay, (GtkWidget*) _tmp2_);
	_g_object_unref0 (_tmp2_);
	_tmp3_ = granite_widgets_overlay_bar_new (overlay);
	g_object_ref_sink (_tmp3_);
	overlay_bar = _tmp3_;
	granite_widgets_overlay_bar_set_status (overlay_bar, "Overlay Bar Example");
	result = (GtkWidget*) overlay;
	_g_object_unref0 (overlay_bar);
	return result;
}


gint granite_demo_main (gchar** args, int args_length1) {
	gint result = 0;
	GraniteDemo* application = NULL;
	GraniteDemo* _tmp0_;
	gchar** _tmp1_;
	gint _tmp1__length1;
	gint _tmp2_;
	_tmp0_ = granite_demo_new ();
	application = _tmp0_;
	_tmp1_ = args;
	_tmp1__length1 = args_length1;
	_tmp2_ = granite_application_run ((GraniteApplication*) application, _tmp1_, _tmp1__length1);
	result = _tmp2_;
	_g_object_unref0 (application);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return granite_demo_main (argv, argc);
}


GraniteDemo* granite_demo_construct (GType object_type) {
	GraniteDemo * self = NULL;
	self = (GraniteDemo*) granite_application_construct (object_type);
	return self;
}


GraniteDemo* granite_demo_new (void) {
	return granite_demo_construct (GRANITE_TYPE_DEMO);
}


static GObject * granite_demo_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	GraniteDemo * self;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar** _tmp8_;
	gchar* _tmp9_;
	gchar** _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar** _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
	parent_class = G_OBJECT_CLASS (granite_demo_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRANITE_TYPE_DEMO, GraniteDemo);
	g_application_set_application_id ((GApplication*) self, "org.pantheon.granite.demo");
	g_application_set_flags ((GApplication*) self, G_APPLICATION_FLAGS_NONE);
	_tmp0_ = g_strdup ("Granite Demo");
	_g_free0 (((GraniteApplication*) self)->program_name);
	((GraniteApplication*) self)->program_name = _tmp0_;
	_tmp1_ = g_strdup ("2011 - 2013");
	_g_free0 (((GraniteApplication*) self)->app_years);
	((GraniteApplication*) self)->app_years = _tmp1_;
	_tmp2_ = g_strdup ("0.2.3");
	_g_free0 (((GraniteApplication*) self)->build_version);
	((GraniteApplication*) self)->build_version = _tmp2_;
	_tmp3_ = g_strdup ("text-editor");
	_g_free0 (((GraniteApplication*) self)->app_icon);
	((GraniteApplication*) self)->app_icon = _tmp3_;
	_tmp4_ = g_strdup ("https://launchpad.net/granite");
	_g_free0 (((GraniteApplication*) self)->main_url);
	((GraniteApplication*) self)->main_url = _tmp4_;
	_tmp5_ = g_strdup ("https://bugs.launchpad.net/granite");
	_g_free0 (((GraniteApplication*) self)->bug_url);
	((GraniteApplication*) self)->bug_url = _tmp5_;
	_tmp6_ = g_strdup ("https://answers.launchpad.net/granite");
	_g_free0 (((GraniteApplication*) self)->help_url);
	((GraniteApplication*) self)->help_url = _tmp6_;
	_tmp7_ = g_strdup ("https://translations.launchpad.net/granite");
	_g_free0 (((GraniteApplication*) self)->translate_url);
	((GraniteApplication*) self)->translate_url = _tmp7_;
	_tmp8_ = g_new0 (gchar*, 1 + 1);
	_tmp8_[0] = NULL;
	((GraniteApplication*) self)->about_documenters = (_vala_array_free (((GraniteApplication*) self)->about_documenters, ((GraniteApplication*) self)->about_documenters_length1, (GDestroyNotify) g_free), NULL);
	((GraniteApplication*) self)->about_documenters = _tmp8_;
	((GraniteApplication*) self)->about_documenters_length1 = 1;
	_tmp9_ = g_strdup ("Daniel P. Fore <daniel@elementaryos.org>");
	_tmp10_ = g_new0 (gchar*, 1 + 1);
	_tmp10_[0] = _tmp9_;
	((GraniteApplication*) self)->about_artists = (_vala_array_free (((GraniteApplication*) self)->about_artists, ((GraniteApplication*) self)->about_artists_length1, (GDestroyNotify) g_free), NULL);
	((GraniteApplication*) self)->about_artists = _tmp10_;
	((GraniteApplication*) self)->about_artists_length1 = 1;
	_tmp11_ = g_strdup ("Maxwell Barvian <mbarvian@gmail.com>");
	_tmp12_ = g_strdup ("Daniel Foré <daniel@elementaryos.org>");
	_tmp13_ = g_strdup ("Avi Romanoff <aviromanoff@gmail.com>");
	_tmp14_ = g_strdup ("Lucas Baudin <xapantu@gmail.com>");
	_tmp15_ = g_strdup ("Victor Eduardo <victoreduardm@gmail.com>");
	_tmp16_ = g_strdup ("Tom Beckmann <tombeckmann@online.de>");
	_tmp17_ = g_new0 (gchar*, 6 + 1);
	_tmp17_[0] = _tmp11_;
	_tmp17_[1] = _tmp12_;
	_tmp17_[2] = _tmp13_;
	_tmp17_[3] = _tmp14_;
	_tmp17_[4] = _tmp15_;
	_tmp17_[5] = _tmp16_;
	((GraniteApplication*) self)->about_authors = (_vala_array_free (((GraniteApplication*) self)->about_authors, ((GraniteApplication*) self)->about_authors_length1, (GDestroyNotify) g_free), NULL);
	((GraniteApplication*) self)->about_authors = _tmp17_;
	((GraniteApplication*) self)->about_authors_length1 = 6;
	_tmp18_ = g_strdup ("A demo of the Granite toolkit");
	_g_free0 (((GraniteApplication*) self)->about_comments);
	((GraniteApplication*) self)->about_comments = _tmp18_;
	_tmp19_ = g_strdup ("Launchpad Translators");
	_g_free0 (((GraniteApplication*) self)->about_translators);
	((GraniteApplication*) self)->about_translators = _tmp19_;
	((GraniteApplication*) self)->about_license_type = GTK_LICENSE_GPL_3_0;
	return obj;
}


static GraniteDemoLLabel* granite_demo_llabel_construct (GType object_type, const gchar* label) {
	GraniteDemoLLabel * self = NULL;
	const gchar* _tmp0_;
	g_return_val_if_fail (label != NULL, NULL);
	self = (GraniteDemoLLabel*) g_object_new (object_type, NULL);
	_tmp0_ = label;
	gtk_label_set_label ((GtkLabel*) self, _tmp0_);
	gtk_widget_set_halign ((GtkWidget*) self, GTK_ALIGN_START);
	return self;
}


static GraniteDemoLLabel* granite_demo_llabel_new (const gchar* label) {
	return granite_demo_llabel_construct (GRANITE_DEMO_TYPE_LLABEL, label);
}


static GraniteDemoLLabel* granite_demo_llabel_construct_indent (GType object_type, const gchar* label) {
	GraniteDemoLLabel * self = NULL;
	const gchar* _tmp0_;
	g_return_val_if_fail (label != NULL, NULL);
	self = (GraniteDemoLLabel*) g_object_new (object_type, NULL);
	_tmp0_ = label;
	gtk_label_set_label ((GtkLabel*) self, _tmp0_);
	gtk_widget_set_margin_left ((GtkWidget*) self, 12);
	return self;
}


static GraniteDemoLLabel* granite_demo_llabel_new_indent (const gchar* label) {
	return granite_demo_llabel_construct_indent (GRANITE_DEMO_TYPE_LLABEL, label);
}


static GraniteDemoLLabel* granite_demo_llabel_construct_markup (GType object_type, const gchar* label) {
	GraniteDemoLLabel * self = NULL;
	const gchar* _tmp0_;
	g_return_val_if_fail (label != NULL, NULL);
	self = (GraniteDemoLLabel*) g_object_new (object_type, NULL);
	_tmp0_ = label;
	gtk_label_set_label ((GtkLabel*) self, _tmp0_);
	gtk_label_set_use_markup ((GtkLabel*) self, TRUE);
	return self;
}


static GraniteDemoLLabel* granite_demo_llabel_new_markup (const gchar* label) {
	return granite_demo_llabel_construct_markup (GRANITE_DEMO_TYPE_LLABEL, label);
}


static GraniteDemoLLabel* granite_demo_llabel_construct_right (GType object_type, const gchar* label) {
	GraniteDemoLLabel * self = NULL;
	const gchar* _tmp0_;
	g_return_val_if_fail (label != NULL, NULL);
	self = (GraniteDemoLLabel*) g_object_new (object_type, NULL);
	_tmp0_ = label;
	gtk_label_set_label ((GtkLabel*) self, _tmp0_);
	gtk_widget_set_halign ((GtkWidget*) self, GTK_ALIGN_END);
	return self;
}


static GraniteDemoLLabel* granite_demo_llabel_new_right (const gchar* label) {
	return granite_demo_llabel_construct_right (GRANITE_DEMO_TYPE_LLABEL, label);
}


static GraniteDemoLLabel* granite_demo_llabel_construct_right_with_markup (GType object_type, const gchar* label) {
	GraniteDemoLLabel * self = NULL;
	const gchar* _tmp0_;
	g_return_val_if_fail (label != NULL, NULL);
	self = (GraniteDemoLLabel*) g_object_new (object_type, NULL);
	_tmp0_ = label;
	gtk_label_set_label ((GtkLabel*) self, _tmp0_);
	gtk_widget_set_halign ((GtkWidget*) self, GTK_ALIGN_END);
	return self;
}


static GraniteDemoLLabel* granite_demo_llabel_new_right_with_markup (const gchar* label) {
	return granite_demo_llabel_construct_right_with_markup (GRANITE_DEMO_TYPE_LLABEL, label);
}


static void granite_demo_llabel_class_init (GraniteDemoLLabelClass * klass) {
	granite_demo_llabel_parent_class = g_type_class_peek_parent (klass);
}


static void granite_demo_llabel_instance_init (GraniteDemoLLabel * self) {
}


/**
     * Small helper class for constructing labels a bit faster.
     */
static GType granite_demo_llabel_get_type (void) {
	static volatile gsize granite_demo_llabel_type_id__volatile = 0;
	if (g_once_init_enter (&granite_demo_llabel_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraniteDemoLLabelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) granite_demo_llabel_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraniteDemoLLabel), 0, (GInstanceInitFunc) granite_demo_llabel_instance_init, NULL };
		GType granite_demo_llabel_type_id;
		granite_demo_llabel_type_id = g_type_register_static (gtk_label_get_type (), "GraniteDemoLLabel", &g_define_type_info, 0);
		g_once_init_leave (&granite_demo_llabel_type_id__volatile, granite_demo_llabel_type_id);
	}
	return granite_demo_llabel_type_id__volatile;
}


static GraniteDemoSourceListExpandableItem* granite_demo_source_list_expandable_item_construct (GType object_type, const gchar* name) {
	GraniteDemoSourceListExpandableItem * self = NULL;
	const gchar* _tmp0_;
	g_return_val_if_fail (name != NULL, NULL);
	_tmp0_ = name;
	self = (GraniteDemoSourceListExpandableItem*) granite_widgets_source_list_expandable_item_construct (object_type, _tmp0_);
	return self;
}


static GraniteDemoSourceListExpandableItem* granite_demo_source_list_expandable_item_new (const gchar* name) {
	return granite_demo_source_list_expandable_item_construct (GRANITE_DEMO_TYPE_SOURCE_LIST_EXPANDABLE_ITEM, name);
}


static gint granite_demo_source_list_expandable_item_real_compare (GraniteWidgetsSourceListExpandableItem* base, GraniteWidgetsSourceListItem* a, GraniteWidgetsSourceListItem* b) {
	GraniteDemoSourceListExpandableItem * self;
	gint result = 0;
	GCompareFunc _tmp0_;
	GraniteWidgetsSourceListItem* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	GraniteWidgetsSourceListItem* _tmp4_;
	const gchar* _tmp5_;
	const gchar* _tmp6_;
	gint _tmp7_;
	self = (GraniteDemoSourceListExpandableItem*) base;
	g_return_val_if_fail (a != NULL, 0);
	g_return_val_if_fail (b != NULL, 0);
	_tmp0_ = g_strcmp0;
	_tmp1_ = a;
	_tmp2_ = granite_widgets_source_list_item_get_name (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = b;
	_tmp5_ = granite_widgets_source_list_item_get_name (_tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = _tmp0_ (_tmp3_, _tmp6_);
	result = _tmp7_;
	return result;
}


static void granite_demo_source_list_expandable_item_class_init (GraniteDemoSourceListExpandableItemClass * klass) {
	granite_demo_source_list_expandable_item_parent_class = g_type_class_peek_parent (klass);
	((GraniteWidgetsSourceListExpandableItemClass *) klass)->compare = (gint (*) (GraniteWidgetsSourceListExpandableItem *, GraniteWidgetsSourceListItem*, GraniteWidgetsSourceListItem*)) granite_demo_source_list_expandable_item_real_compare;
}


static void granite_demo_source_list_expandable_item_instance_init (GraniteDemoSourceListExpandableItem * self) {
}


static GType granite_demo_source_list_expandable_item_get_type (void) {
	static volatile gsize granite_demo_source_list_expandable_item_type_id__volatile = 0;
	if (g_once_init_enter (&granite_demo_source_list_expandable_item_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraniteDemoSourceListExpandableItemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) granite_demo_source_list_expandable_item_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraniteDemoSourceListExpandableItem), 0, (GInstanceInitFunc) granite_demo_source_list_expandable_item_instance_init, NULL };
		GType granite_demo_source_list_expandable_item_type_id;
		granite_demo_source_list_expandable_item_type_id = g_type_register_static (GRANITE_WIDGETS_SOURCE_LIST_TYPE_EXPANDABLE_ITEM, "GraniteDemoSourceListExpandableItem", &g_define_type_info, 0);
		g_once_init_leave (&granite_demo_source_list_expandable_item_type_id__volatile, granite_demo_source_list_expandable_item_type_id);
	}
	return granite_demo_source_list_expandable_item_type_id__volatile;
}


static GraniteDemoSourceListItem* granite_demo_source_list_item_construct (GType object_type, const gchar* title) {
	GraniteDemoSourceListItem * self = NULL;
	const gchar* _tmp0_;
	GIcon* _tmp1_;
	GIcon* _tmp3_;
	g_return_val_if_fail (title != NULL, NULL);
	_tmp0_ = title;
	self = (GraniteDemoSourceListItem*) granite_widgets_source_list_item_construct (object_type, _tmp0_);
	granite_widgets_source_list_item_set_editable ((GraniteWidgetsSourceListItem*) self, TRUE);
	_tmp1_ = granite_demo_source_list_item_themed_icon;
	if (_tmp1_ == NULL) {
		GThemedIcon* _tmp2_;
		_tmp2_ = (GThemedIcon*) g_themed_icon_new_with_default_fallbacks ("help-info-symbolic");
		_g_object_unref0 (granite_demo_source_list_item_themed_icon);
		granite_demo_source_list_item_themed_icon = (GIcon*) _tmp2_;
	}
	_tmp3_ = granite_demo_source_list_item_themed_icon;
	granite_widgets_source_list_item_set_icon ((GraniteWidgetsSourceListItem*) self, _tmp3_);
	return self;
}


static GraniteDemoSourceListItem* granite_demo_source_list_item_new (const gchar* title) {
	return granite_demo_source_list_item_construct (GRANITE_DEMO_TYPE_SOURCE_LIST_ITEM, title);
}


static gint granite_demo_source_list_item_get_page_num (GraniteDemoSourceListItem* self) {
	gint result;
	gint _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_page_num;
	result = _tmp0_;
	return result;
}


static void granite_demo_source_list_item_set_page_num (GraniteDemoSourceListItem* self, gint value) {
	g_return_if_fail (self != NULL);
	if (granite_demo_source_list_item_get_page_num (self) != value) {
		gint _tmp0_;
		_tmp0_ = value;
		self->priv->_page_num = _tmp0_;
		g_object_notify ((GObject *) self, "page-num");
	}
}


static void granite_demo_source_list_item_class_init (GraniteDemoSourceListItemClass * klass) {
	granite_demo_source_list_item_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GraniteDemoSourceListItemPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_granite_demo_source_list_item_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_granite_demo_source_list_item_set_property;
	G_OBJECT_CLASS (klass)->finalize = granite_demo_source_list_item_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GRANITE_DEMO_SOURCE_LIST_ITEM_PAGE_NUM_PROPERTY, g_param_spec_int ("page-num", "page-num", "page-num", G_MININT, G_MAXINT, -1, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void granite_demo_source_list_item_instance_init (GraniteDemoSourceListItem * self) {
	self->priv = GRANITE_DEMO_SOURCE_LIST_ITEM_GET_PRIVATE (self);
	self->priv->_page_num = -1;
}


static void granite_demo_source_list_item_finalize (GObject * obj) {
	GraniteDemoSourceListItem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRANITE_DEMO_TYPE_SOURCE_LIST_ITEM, GraniteDemoSourceListItem);
	G_OBJECT_CLASS (granite_demo_source_list_item_parent_class)->finalize (obj);
}


/**
     * SourceList item. It stores the number of the corresponding page in the notebook widget.
     */
static GType granite_demo_source_list_item_get_type (void) {
	static volatile gsize granite_demo_source_list_item_type_id__volatile = 0;
	if (g_once_init_enter (&granite_demo_source_list_item_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraniteDemoSourceListItemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) granite_demo_source_list_item_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraniteDemoSourceListItem), 0, (GInstanceInitFunc) granite_demo_source_list_item_instance_init, NULL };
		GType granite_demo_source_list_item_type_id;
		granite_demo_source_list_item_type_id = g_type_register_static (GRANITE_WIDGETS_SOURCE_LIST_TYPE_ITEM, "GraniteDemoSourceListItem", &g_define_type_info, 0);
		g_once_init_leave (&granite_demo_source_list_item_type_id__volatile, granite_demo_source_list_item_type_id);
	}
	return granite_demo_source_list_item_type_id__volatile;
}


static void _vala_granite_demo_source_list_item_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	GraniteDemoSourceListItem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GRANITE_DEMO_TYPE_SOURCE_LIST_ITEM, GraniteDemoSourceListItem);
	switch (property_id) {
		case GRANITE_DEMO_SOURCE_LIST_ITEM_PAGE_NUM_PROPERTY:
		g_value_set_int (value, granite_demo_source_list_item_get_page_num (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_granite_demo_source_list_item_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	GraniteDemoSourceListItem * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GRANITE_DEMO_TYPE_SOURCE_LIST_ITEM, GraniteDemoSourceListItem);
	switch (property_id) {
		case GRANITE_DEMO_SOURCE_LIST_ITEM_PAGE_NUM_PROPERTY:
		granite_demo_source_list_item_set_page_num (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void granite_demo_class_init (GraniteDemoClass * klass) {
	granite_demo_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (GraniteDemoPrivate));
	((GApplicationClass *) klass)->activate = (void (*) (GApplication *)) granite_demo_real_activate;
	G_OBJECT_CLASS (klass)->constructor = granite_demo_constructor;
	G_OBJECT_CLASS (klass)->finalize = granite_demo_finalize;
}


static void granite_demo_instance_init (GraniteDemo * self) {
	self->priv = GRANITE_DEMO_GET_PRIVATE (self);
}


static void granite_demo_finalize (GObject * obj) {
	GraniteDemo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GRANITE_TYPE_DEMO, GraniteDemo);
	_g_object_unref0 (self->priv->main_layout);
	_g_object_unref0 (self->priv->mode_button);
	G_OBJECT_CLASS (granite_demo_parent_class)->finalize (obj);
}


/***
    Copyright (C) 2011-2013 Lucas Baudin <xapantu@gmail.com>,
                            Jaap Broekhuizen <jaapz.b@gmail.com>,
                            Victor Eduardo <victoreduardm@gmal.com>,
                            Tom Beckmann <tom@elementaryos.org>

    This program or library is free software; you can redistribute it
    and/or modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 3 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General
    Public License along with this library; if not, write to the
    Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301 USA.
***/
GType granite_demo_get_type (void) {
	static volatile gsize granite_demo_type_id__volatile = 0;
	if (g_once_init_enter (&granite_demo_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (GraniteDemoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) granite_demo_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GraniteDemo), 0, (GInstanceInitFunc) granite_demo_instance_init, NULL };
		GType granite_demo_type_id;
		granite_demo_type_id = g_type_register_static (GRANITE_TYPE_APPLICATION, "GraniteDemo", &g_define_type_info, 0);
		g_once_init_leave (&granite_demo_type_id__volatile, granite_demo_type_id);
	}
	return granite_demo_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



